### ISSUE TITLE
Audit alt text on Explore Data visuals

### ISSUE THREAD

**Issue by mcharg** [DOI-ONRR/nrrd#1166]
We should review what we have and make it more descriptive, if necessary, for accessibility.

**Comment by mcharg** [comment]
Jerome said we can do a do a search across the site and get a list of all images and their alt tag values.  For svgs, we could get their respective title, too.

**Comment by jkwonatx** [comment]
@mcharg how can I get started on this?

**Comment by mcharg** [comment]
@jlouis-onrr is it a quick thing for you to export the current alt text?

**Comment by eelzi-ONRR** [comment]
Closing this. We did a lot of work on the NRRD alt text last year so I don't think this needs to be done
