### ISSUE TITLE
Create Sales Year Data Download Page

### ISSUE THREAD

**Issue by mentastc** [DOI-ONRR/nrrd#126]
Create a download page for sales year and add sales year to the [main download page](https://revenuedata.doi.gov/downloads/).

Additional Items Needed:

- Update and add terms to the glossary

- Develop verbiage to explain the differences of sales year

**Comment by lpgoldstein** [comment]
@jennmalcolm we have a file! [Sales Year by year .docx](https://github.com/ONRR/nrrd/files/5008149/Sales.Year.by.year.docx)
