### ISSUE TITLE
Implement changes to How Datasets Fit Diagram

### ISSUE THREAD

**Issue by mcharg** [DOI-ONRR/nrrd#1686]
To make it less vertical.

Design: https://f4d09b.axshare.com/#id=dwpsbz&p=how_datasets_fit

Suggested arrows:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/6a4d3285-df1b-4023-b345-b0881e98b361)

**Comment by lpgoldstein** [comment]
Adding info to #3514 and close this one
