### ISSUE TITLE
August Analytics

### ISSUE THREAD

**Issue by ghost** [DOI-ONRR/nrrd#1697]

**Comment by daniel-coleman-1** [comment]
@mcharg I'm almost done with this one, but I'm not 100% sure how to approach Untrackable and Old users in the Page Views section

![Screenshot 2021-09-01 131320](https://user-images.githubusercontent.com/83892362/131730469-16ed0d75-a751-4ca3-8a22-808bccd26786.png)
![Screenshot 2021-09-01 131245](https://user-images.githubusercontent.com/83892362/131730472-fc8c57a2-e3fa-4336-94db-6c30ec2df313.png)

**Comment by mcharg** [comment]
@daniel-coleman-1 Drag down the formula from the previous row in column M.  Then copy and paste the total users, sessions, and page views numbers into the old users, sessions, and page views cells.

**Comment by daniel-coleman-1** [comment]
@mcharg this one is ready for your review:
https://github.com/ONRR/nrrd/wiki/Analytics

**Comment by mcharg** [comment]
@daniel-coleman-1 We only include browsers over 1%.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/2d47c330-077f-4f88-825c-81a082e3560d)

**Comment by mcharg** [comment]
@daniel-coleman-1 There were no downloads of the production yearly excel files.  The ones that show up are on the archive site.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/0165ae70-2279-46e1-8ef9-4e084d6b2861)

**Comment by mcharg** [comment]
Otherwise, looks good.
