### ISSUE TITLE
Add a minimum pixel for the bars on the Explore Data Page

### ISSUE THREAD

**Issue by cvojslavek** [DOI-ONRR/nrrd#1717]
This is to add a minimum pixel for the bars on the [Explore Data Page](https://revenuedata.doi.gov/explore/?dataType=Revenue&location=NF%2CNA&mapLevel=State&offshoreRegions=false&period=Calendar%20Year&year=2020), Nationwide revenue summary tab. See the example below, the Native American amount doesn't show up in the Rents section bar:
![image](https://user-images.githubusercontent.com/89403899/132401093-e91a59f5-8469-4e7d-82e3-9c286cf83d8a.png)

**Comment by lpgoldstein** [comment]
Still an issue

**Comment by AlexandracmONRR** [comment]
This problem has a prototype to fix in #1782
