### ISSUE TITLE
Fact Sheet PDF has accessibility errors

### ISSUE THREAD

**Issue by mcharg** [DOI-ONRR/nrrd#1915]
Not sure if there's anything we can do, since it's generated as a print job.  I'm getting 21 errors.
<br>
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/d450da82-aef3-468b-a2e5-4073725ed7e1)
<br>
[Fact Sheet PDF](https://app.zenhub.com/files/215585796/f938c558-07dc-4c43-a092-7f214d701d12/download)

**Comment by Maroyafaied** [comment]
The webpage itself is accessible.
