### ISSUE TITLE
Look at data type field analytics for query tool

### ISSUE THREAD

**Issue by mcharg** [DOI-ONRR/nrrd#2027]
It's returning multiple values.
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/ca87fbd7-f823-42df-a703-584252f7404f)

**Comment by lpgoldstein** [comment]
@cthomasONRR please close if no longer relevant.

**Comment by cthomasONRR** [comment]
This is from UA and this is no longer an issue in GA4. Closing.
