### ISSUE TITLE
Look into the 404 links in the analytics

### ISSUE THREAD

**Issue by mcharg** [DOI-ONRR/nrrd#2030]
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/ed27280b-e41e-4af9-aef2-79b2a157f350)

**Comment by lpgoldstein** [comment]
Issue with revenue downloads for historical data. You will get a 404 if you follow this path:  go to the data downloads page, then click on revenue downloads https://revenuedata.doi.gov/downloads/revenue/ then go back to the downloads page using the downloads link at the top of the page and then the historical revenue links starts doubling the "downloads" and giving you a 404. ![image.png](https://images.zenhubusercontent.com/5c59d3cd7592186396262002/4cbd9950-494b-46a0-a250-dd478420124e)https://revenuedata.doi.gov/downloads/downloads/historical_disbursements_FY1982-2002.xlsx

**Comment by mcharg** [comment]
We don't have all the 404 urls in the analytics for April that we had for March, so maybe it was an anomaly.

**Comment by mcharg** [comment]
@Maroyafaied Can we put this one back in the backlog, since we didn't see these urls in April?

**Comment by Maroyafaied** [comment]
@mcharg Yes, that's fine.
