### ISSUE TITLE
Create Power BI template instructions for monthly disbursements in wiki 

### ISSUE THREAD

**Issue by Isabelh99** [DOI-ONRR/nrrd#2056]

**Comment by Isabelh99** [comment]
Dropping relevant wikis to tweak or baseline:
Disbursements Monthly

 Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)
Note: Make sure both datasets have the same sum. If there are line items that have the same fund type, revenue type, and location, they will be 'rolled up' together so the line item count may differ between the raw data and downloaded data.
 Check Treasury Fund column is deleted
 Check Hidalgo Caounty is changed to Hidalgo County under county column
 Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column
Homepage - Yearly Breakdown

Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
 Breakout - Source
 Breakout - Recipient
Homepage - Monthly Breakdown

Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
 Period - Most recent 12 months
 Period - Fiscal Year
 Period - Calendar Year
 Breakout - Source
 Breakout - Recipient
Query Data - In the 'Period' category, filter to 'Monthly' and check the following:

 One Recipient
 One Source
 One State
 One to three Commodities if applicable
 Clear All and change grouping
 Downloads matches filtered data
Download Page

 Dates and file size are correct for csv and excel
Monthly Snap Shot

 Check graphs match homepage

**Comment by Isabelh99** [comment]
**Disbursements Fiscal Year**

Note that only certain years are updated beginning in 2003 to break U.S. Treasury data into onshore and offshore. Then several onshore, offshore, and offshore GOMESA amounts are updated through 2014. The raw data shows these updates.


- [ ]  Make sure the downloaded data matches the raw data. Raw data saved [here](https://teams.microsoft.com/l/file/5B3E6659-1CC2-417D-8145-73D632A6C67C?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FDisbursements%2FHistorical%20Disbursements%2FFinal%20proposed%20changes%20to%20NRRD.%20V.02%20(1).xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

Explore Data - Map and Detail Card

- With a fiscal year selected, verify the detail card and Disbursements Over Time are correct for the conditions below. Repeat with the current fiscal year.

- [ ]  State with data
- [ ]  State without data
- [ ]  County with data
- [ ]  County without data
- [ ]  Nationwide Federal Card
- [ ]  Native American Card

Explore Data - Nationwide Revenue Summary and Top Nationwide Locations

- Verify breakdowns by disbursement recipient and source are correct as well nationwide recipients for the conditions below.

 

- [ ] Not current Fiscal Year
- [ ]  Current Fiscal Year

Query Data - In the 'Period' category, filter to 'Fiscal Year' and check the following:

- [ ]  One Recipient
- [ ]  One Source
- [ ]  One State
- [ ]  Clear All and change grouping
- [ ]  Downloads matches filtered data

Download Page

- [ ]  Dates and file size are correct for csv and excel

**Comment by Isabelh99** [comment]
**Disbursements Fiscal Year** 	

Note that only certain years are updated beginning in 2003 to break U.S. Treasury data into onshore and offshore. Then several onshore, offshore, and offshore GOMESA amounts are updated through 2014. The raw data shows these updates. 

- [x] Make sure the downloaded data matches the raw data. Raw data saved [here](https://teams.microsoft.com/l/file/5B3E6659-1CC2-417D-8145-73D632A6C67C?tenantId=0693b5ba-4b18-4d7b-9341-f32f400a5494&fileType=xlsx&objectUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FNRRD%2FData%2FDisbursements%2FHistorical%20Disbursements%2FFinal%20proposed%20changes%20to%20NRRD.%20V.02%20(1).xlsx&baseUrl=https%3A%2F%2Fdoimspp.sharepoint.com%2Fsites%2FNRRD&serviceName=teams&threadId=19:34f9f9ee6b0441dbacab56bfd552f819@thread.skype&groupId=3dd7454f-a781-414f-b6f1-b6d10fadb64a)

Explore Data - Map and Detail Card
- With a fiscal year selected, verify the detail card and Disbursements Over Time are correct for the conditions below. Repeat with the current fiscal year.
    - [x] State with data
    - [x] State without data
    - [x] County with data
    - [x] County without data
    - [x] Nationwide Federal Card
    - [x] Native American Card

Explore Data - Nationwide Revenue Summary and Top Nationwide Locations
- Verify breakdowns by disbursement recipient and source are correct as well nationwide recipients for the conditions below.
    - [x] Not current Fiscal Year
    - [x] Current Fiscal Year

Query Data - In the 'Period' category, filter to 'Fiscal Year' and check the following:
- [x] One Recipient
- [x] One Source
- [x] One State
- [x] Clear All and change grouping
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

**Comment by Isabelh99** [comment]
**Revenue Monthly** 	

- [x] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout - Commodity
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout Commodity
 
Homepage - Source File
- [x] Check source file links are correct.
 
Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
   - [x] One Land Type filter
   - [x] One Revenue Type filter
   - [x] One State (for Yearly data only)
   - [x] One Offshore Region
   - [x] One to three Commodities
   - [x] Clear All and change grouping
   - [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

**Comment by Isabelh99** [comment]
**Production Monthly** 

- [x] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Commodity - Oil (bbl)
    - [x] Commodity - Gas (mcf)
    - [x] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Commodity - Oil (bbl)
    - [x] Commodity - Gas (mcf)
    - [x] Commodity - Coal (tons)

Homepage - Source File
- [x] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [x] One Land Type filter
- [x] One to three Products
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

**Comment by lpgoldstein** [comment]
@Isabelh99 Just one comment and an edit. Next step is to put the disbursements instructions in markdown and insert into the wiki. Then we can test out the instructions on our next round of disbursements data. [Instructions.for.using.the.PowerBI.Templates.to.check.data.docx](https://github.com/ONRR/nrrd/files/8701560/Instructions.for.using.the.PowerBI.Templates.to.check.data.docx)

Here's some markdown info: https://www.markdownguide.org/

**Comment by Isabelh99** [comment]
Pictures for the disbursements edit
<img width="233" alt="Picture2" src="https://user-images.githubusercontent.com/93946660/169442803-5e113d5c-7176-4257-84f7-8c963dd23473.png">
![Picture3](https://user-images.githubusercontent.com/93946660/169442805-9daa09a0-4db5-45f5-95f5-494dd7ad1e3e.png)
![Picture4](https://user-images.githubusercontent.com/93946660/169442806-d12454f5-8e82-4c83-a3a0-1b4133214f84.png)
![Picture5](https://user-images.githubusercontent.com/93946660/169442808-b598302c-763a-4c80-8cee-a997a65aea17.png)
![Picture6](https://user-images.githubusercontent.com/93946660/169442809-9c5141d0-c680-4855-9cd0-443d33d68643.png)
![Picture7](https://user-images.githubusercontent.com/93946660/169442814-8625d7a9-0aef-4111-aca7-2c87f69d64a5.png)
![Picture8](https://user-images.githubusercontent.com/93946660/169442817-a2bdc42c-e328-4baa-89e7-0bb7f4dac41a.png)
<img width="468" alt="Picture9" src="https://user-images.githubusercontent.com/93946660/169442818-60057c29-16c5-497f-9bba-35d1515e5df6.png">
![Picture10](https://user-images.githubusercontent.com/93946660/169442819-749fe3f0-2abb-4b4b-bd7a-44bde233d84a.png)
![Picture11](https://user-images.githubusercontent.com/93946660/169442820-999cc408-17f8-4eb7-87cc-2fd23fdc2277.png)
![Picture12](https://user-images.githubusercontent.com/93946660/169442824-988be302-a135-469b-b578-0bbbd1bf90aa.png)
<img width="468" alt="Picture1" src="https://user-images.githubusercontent.com/93946660/169442825-ea900348-2d30-435b-b9ce-620ffac3aee9.png">
:

**Comment by Isabelh99** [comment]
Uploaded and tweaked on wiki! Let me know any corrections! 
Also, if you have will search tips to make the resolution on these screenshots look less blurry.. let me know if you know of any

**Comment by lpgoldstein** [comment]
@Isabelh99 Looks great! Just a few edits: 
Omit this comment
![image](https://user-images.githubusercontent.com/39419003/169560018-4fd003f7-e3a5-45ac-b2d4-cbae860f317d.png)
If you use a smaller picture it will be less blurry 
![image](https://user-images.githubusercontent.com/39419003/169560142-b8c2364e-64d4-4c24-afbb-e813a47e3c93.png)
Replace the word revenue with disbursements and add the word data to January 2022 (I think?) I think this sentence should be rewritten. I think it's trying to say that the filters on the right hand side are connected to the January 2022 raw data. 
![image](https://user-images.githubusercontent.com/39419003/169561227-710dc861-da20-4544-8b5e-92514da29772.png)

**Comment by lpgoldstein** [comment]
Here this should be changed from 2021 to 2022
![image](https://user-images.githubusercontent.com/39419003/169561344-96ef9fe8-bdbd-4205-b2d6-cb2b20654627.png)

**Comment by lpgoldstein** [comment]
This picture in 4.3 has been resized improperly - that's why blurry. Do you know how to fix that? 
![image](https://user-images.githubusercontent.com/39419003/169561586-29650816-8b05-4c37-97d0-a280b5e36a3b.png)

**Comment by lpgoldstein** [comment]
Same here 
![image](https://user-images.githubusercontent.com/39419003/169561659-7a6d64b0-53ce-43e5-acfd-9159bff6ea1d.png)

**Comment by lpgoldstein** [comment]
5.2 resize smaller 
![image](https://user-images.githubusercontent.com/39419003/169561835-d71fe8bb-ce1a-4dd9-ba1b-efce7c3ee7d3.png)

**Comment by lpgoldstein** [comment]
@Isabelh99 how are you resizing and saving your images? Do you know how to save images as high resolution?

**Comment by Isabelh99** [comment]
Edited!
