### ISSUE TITLE
Review older renewable fact sheets for revenue & disbursements 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2173]

**Comment by Baymatt** [comment]
Reviewed the older renewable fact sheets for revenue, disbursements and production based on the files in the renewable snapshot folder in Teams. All the information is correct.

**Comment by Maroyafaied** [comment]
Matt's pivot table https://doimspp.sharepoint.com/:x:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7BB765264A-B65C-47B7-B5B7-09897A3E5512%7D&file=FY%20Production%20File%20as%20of%202-24-22_renewablescheck.xlsx&action=default&mobileredirect=true

**Comment by Maroyafaied** [comment]
@cthomasONRR  I'll be reviewing FY18 & FY19.

**Comment by cthomasONRR** [comment]
2019: replace current kwh with 3,195,518,756 kwh

![image](https://user-images.githubusercontent.com/72526208/228045904-2d4861e3-f725-4c4f-8350-95f612db04ce.png)

**Comment by cthomasONRR** [comment]
I finished checking revenue and disbursements. Everything looks good, no updates found.

At NRRD\Data\Renewable snapshot, I updated the 3 excel files to have all the recent data, plus FY22 data. @lpgoldstein You can cross check your FY22 data with these files.

![image](https://user-images.githubusercontent.com/72526208/228057061-4a4c1bc1-3939-4842-9761-2f299882e1bd.png)

**Comment by Maroyafaied** [comment]
@cthomasONRR I updated the pdfs in the power point templates, the templates allow you to edit the data as an excel field. https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/NRRD/Design/Renewables%20Fact%20Sheet/Renewables-Fact-Sheet-WORKING%20TEMPLATE.pptx?web=1
