### ISSUE TITLE
Explore Data: Build revenue top commodities chart

### ISSUE THREAD

**Issue by mcharg** [DOI-ONRR/nrrd#221]
Design:
![image.png](https://images.zenhubusercontent.com/5c589fe5e180620812ea22aa/0e99330b-bbec-4425-933e-06cb73338b64)

**Comment by jennmalcolm** [comment]
Legend can go below circle chart.

**Comment by mcharg** [comment]
This one's done.

**Comment by mcharg** [comment]
I thought this was done, but not seeing it in the current build.
