### ISSUE TITLE
Request approval to attend & travel to the CFA conference 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2287]

**Comment by lpgoldstein** [comment]
Emailed CFA to ask about cost of CFA summit this year. Website not updated yet.

**Comment by lpgoldstein** [comment]
Will probably have to move to next sprint. Haven't heard back from email and conference website not updated yet.

**Comment by lpgoldstein** [comment]
Will have more info next sprint so moving.

**Comment by Maroyafaied** [comment]
Everything has been submitted to the conference approval team. We will book travel once we have final approval.
