### ISSUE TITLE
Set up context variables in Circle Ci 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2359]
I set up the org-global and preview, I still need to finish setting up prod, dev, and QA. 

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/8ba23b38-eeeb-4ae3-8de2-09f628c3cb99)

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/6430a0a5-4b15-4f68-9f9b-f41238c83949)

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/9b99822b-4ff7-4a75-ae1c-ad2e8aa9002d)

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/36db5b6a-b51d-4695-bf91-1d02aa5786ce)

**Comment by greensomes** [comment]
Here's the context configuration I recommend for the DOI-ONRR organization:

org-global:
- CF_ORG
- CF_PASSWORD
- CF_USERNAME

prod: 
- CF_SPACE

dev:
- CF_SPACE

nrrd:
- NPS_AWS_ACCESS_KEY
- NPS_AWS_REGION
- NPS_AWS_SECRET_ACCESS_KEY
- NPS_BUCKET_NAME

onrr:
- NPS_AWS_ACCESS_KEY
- NPS_AWS_REGION
- NPS_AWS_SECRET_ACCESS_KEY
- NPS_BUCKET_NAME

**Comment by Maroyafaied** [comment]
@greensomes set up all the contexts needs for all the 3 repositories.  All environmental variables are not set as contexts at an organizational level rather than at a project level which was the case previously.  ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/422aac3c-b987-425a-b01d-01a77e28d061)
