### ISSUE TITLE
Fix Explore Data Add Location Dropdown

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#2375]
The Add Location dropdown has Alabama and California at the top, spaced above the rest of the list. When you select either one, nothing happens. Both states are also listed correctly in the alphabetical list and function as expected when selected from there.

![image.png](https://images.zenhubusercontent.com/63482c003bae1bf4351c6f26/c83c9cc9-74cb-48e8-9e29-fbdd0cac2655)![image.png]

**Comment by greensomes** [comment]
The qraphql query needs to be updated to exclude entries where the `county: {_eq: ""}`.

**Comment by greensomes** [comment]
Fixed!!
