### ISSUE TITLE
Heading and link overlap on explore disbursements nationwide federal card

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#2379]
On Explore data - Disbursements - Compare Disbursements -  Nationwide Federal

https://revenuedata.doi.gov/explore?dataType=Disbursements&location=NF%2CNA&mapLevel=State&offshoreRegions=false&period=Fiscal%20Year&year=2022

"Query disbursements by recipient" link overlaps with the "disbursements by source" heading. This happens in Chrome and Firefox, on desktop and mobile. This does not happen in Edge

![image.png](https://images.zenhubusercontent.com/63482c003bae1bf4351c6f26/8daedbd6-b26f-49d4-b21f-1309c9158e6e)

**Comment by lpgoldstein** [comment]
Removed link so no longer an issue
