### ISSUE TITLE
NRRD analytics

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#2387]

**Comment by cthomasONRR** [comment]
@lpgoldstein 
January analytics for NRRD are ready for your review:
https://github.com/DOI-ONRR/nrrd/wiki/Analytics

Check sheet link here (you should get an email allowing you access): https://doimspp-my.sharepoint.com/:w:/r/personal/thomasc_mms_gov/Documents/CLT%20Analytics/Analytics%20January%2023.docx?d=wb2c115de1ae84dad80f482581cdff4a4&csf=1&web=1&e=a5B98E

**Comment by lpgoldstein** [comment]
@cthomasONRR looks good!
