### ISSUE TITLE
Discuss NRRD content audit with Maroya

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#2389]

**Comment by cthomasONRR** [comment]
@Maroyafaied I created an Excel for FY23 content audit [here](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/NRRD/Content/[Content_Audit_FY23.xlsx](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/NRRD/Content/Content_Audit_FY23.xlsx?d=wef6ffe081c5244ad9c3ba28a218beb7a&csf=1&web=1&e=rL7mpr)?d=wef6ffe081c5244ad9c3ba28a218beb7a&csf=1&web=1&e=rL7mpr)

If you have time, you can review the headings. I have a few comments in the headings for what the categories would be.

**Comment by Maroyafaied** [comment]
@cthomasONRR This is a great start, I'm excited to finally have the sitemap and content audit tie in together
