### ISSUE TITLE
Disbursement NRRD vs Budget spreadsheet variance FY 2009

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2392]

**Comment by lpgoldstein** [comment]
Explanation: We updated the NRRD numbers, but never updated the disbursement matrix on the Pie Chart. The $871M is an accounting movement for Treasury that looks like a disbursement in Fund 2020. We move it on 09/30/2009, then move it back on 10/01/2009. So its just a temp fix to zero out our suspense account at year end.
