### ISSUE TITLE
Finish NRRD sitemap in Axure

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#2396]

**Comment by eelzi-ONRR** [comment]
This is ready for review. I've assigned each person a section or two based off how many pages and how complicted those sections are. I've added it to the Axure cloud - you can comment there or use the preivew link and comment in this issue.
http://127.0.0.1:32767/start.html#id=gy27ii&p=0_0_homepage

 All the purple and grey boxes and most of the peach boxes will link to the page it references. The exceptions are when it references a specific section of that page - I can only make the linked widgets work when they are going to pages listed in the menu, But in some cases it's important to know we're linking to a specific content, not just the entire page. 

I'd also love feedback on whether the design and format makes sense. My goal is for it to not need instructions :) 

@cthomasONRR Homepage (0.0) & Explore data (1.0)
@lpgoldstein Query data (2.0) & Footer (6.0)
@Maroyafaied Downlaod data (3.0) & Glossary (4.0)
@AlexandracmONRR How Revenue Works (5.0)

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Just FYI, that link didn't work for me. I had to go to the could and found the sitemap in the onrr.gov folder.

**Comment by eelzi-ONRR** [comment]
@cthomasONRR Thank you - I updated the link above with the one you showed me today

**Comment by lpgoldstein** [comment]
@eelzi-ONRR Looks great! I just left a few comments in my sections. Could follow without instructions!

**Comment by Maroyafaied** [comment]
@eelzi-ONRR I reviewed my sections, I only found one tiny thing. I'm amazed!!

**Comment by eelzi-ONRR** [comment]
I incorporated everyone's edits and uploaded the new version to the Axure cloud. 

I'm closing this ticket since the only person who had major revisions was Christine and she's already seen and approved them. Thank you all for your feeback!
