### ISSUE TITLE
SF_182 to renew O'Reilly membership

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2403]

**Comment by Maroyafaied** [comment]
@eelzi-ONRR @AlexandracmONRR please login and let me know if you'd like me to keep this subscription.

**Comment by Maroyafaied** [comment]
@eelzi-ONRR @AlexandracmONRR please login and let me know if you'd like me to keep this subscription.

**Comment by eelzi-ONRR** [comment]
@Maroyafaied My vote is to keep it. I looked around a bit and not only are there loads of UX and design resources, but lots of sources for software programming, project mangement, data anlysis tools - so much good stuff!

**Comment by Maroyafaied** [comment]
@eelzi-ONRR Thanks, I asked Carrie to pay for the renewal.

**Comment by Maroyafaied** [comment]
I've renewed the subscription until March 2024
