### ISSUE TITLE
Research Google Analytics 4

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#2406]
Gov sites are transitioning from Google Analytics 360 to Google Analytics 4. I want to better understand what we need to do to prepare. Will our saved dashboards and reports transition over, or do we have to recreate them?

**Comment by cthomasONRR** [comment]
There's a web analytics huddle on February 28. I'm going to wait to do this task until then. This meeting might help me with my questions.

**Comment by cthomasONRR** [comment]
NOTES FROM MEETING:
- Because we're part of DAP (Digital Analytics Program), and this is a paid version of Google Analytics, we don't have to worry about personally transitioning to GA4
- From the DAP mailing list- DAP code for GA4 is in beta testing
- Custom reports are set up differently, not really apples to apples
- We will likely have to recreate all our dashboards and custom reports

NEXT STEPS:
- We need to contact dap@gsa.gov to see if we are correct in having to recreate custom reports and dashboards, and ask if there is a way to test our GA4 account before having a hard-transition over.
- We need to document all settings we used to create our custom reports and dashboards. This way, we can more efficiently recreate them in GA4.

**Comment by cthomasONRR** [comment]
Resources from group chat:
https://support.google.com/analytics/answer/12799087?hl=en
https://www.analyticsmania.com/courses/google-analytics-4-course/
https://www.teamsimmer.com/
https://www.ga4bigquery.com/

**Comment by cthomasONRR** [comment]
@eelzi-ONRR @Maroyafaied Here's a draft email to DAP. Could you please review and let me know if I should change anything? Thanks!

"SUBJECT: ONRR transition from GA360 to GA4

Hello,
We attended GSA's web analytics community huddle on the Google Analytics transition. While we understand that no action is needed from ONRR to transition from GA360 to GA4, this meeting brought up several questions that we're hoping you can help answer.
- It appears that all of our currently saved dashboards and customized reports will NOT transition from GA360 to GA4. Can you confirm this?
- If they indeed do not make it over to GA4, we need to understand how we can prepare. In the meeting, we were told that the DAP code for GA4 is in beta testing. Will there be a way we can work on re-creating our customized reports in GA4 while still having access to GA360?
- Is it possible for us to transition to GA4 early (before July 2024) so we can properly test that it's working before losing access to GA360?
- Within DAP, I see the "GA4 Sandbox Account" and "Test Digital Analytics Program GA4" (pictured below), I tried playing around in them to test to see if I could recreate one of our dashboards or customized reports. I was not successful. Are these location meant for this sort of testing? Could you recommend how I can test to get familiar with GA4?
![image](https://user-images.githubusercontent.com/72526208/221963725-e60e6a5a-3f82-4a8f-afcb-df731eea28f7.png)
Any input or advice you can provide would be greatly appreciated.
We're also happy to have a meeting to discuss.
Thanks for your time and patience"

**Comment by eelzi-ONRR** [comment]
@cthomasONRR I think the email is great - I don't have any additional questions

Additional notes from the meeting:

- Let stakeholders know that some data points will not be able to be recreated. Take the time to educate them on metrics

- Inventory all current reports and dashoards. Some will be reproducable, but many will not

- Run both tools in paralell before a hard cut off - take lots of time to learn the new one

- Consdier how ong you need data and metrics stored. It's probably not as long as you initially think


I think this will be a good opportunity to reevaluate what reports and datapoints we need. If we don't need all of them, we don't have to reproduce them all

**Comment by Maroyafaied** [comment]
@cthomasONRR I have no changes as well.  It's good to send out!

**Comment by cthomasONRR** [comment]
@eelzi-ONRR @Maroyafaied Email sent! I'm going to close this issue. I made a new issue for doing an inventory of our current reports and dashboards. New issue here: https://github.com/DOI-ONRR/onrr.gov-site/issues/2514
