### ISSUE TITLE
NRRD Content Audit - Homepage

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#2408]
I want to start the content audit with the homepage and get feedback before doing the whole site.

**Comment by cthomasONRR** [comment]
@Maroyafaied This is ready for your review

**Comment by Maroyafaied** [comment]
@cthomasONRR I get this error with the link above 
![image](https://user-images.githubusercontent.com/40175688/218824430-9cfa23dd-aa8b-485b-982b-fd224e5c9326.png)

**Comment by cthomasONRR** [comment]
@Maroyafaied sorry about that. It's in the sharepoint location pictured. Here's [another link to try](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/NRRD/Content/FY23/Content%20Audit%20FY23/Content_Audit_FY23.xlsx?d=wef6ffe081c5244ad9c3ba28a218beb7a&csf=1&web=1&e=yImjtW)

**Comment by Maroyafaied** [comment]
@cthomasONRR This is perfect!

**Comment by cthomasONRR** [comment]
@Maroyafaied Awesome, thanks! I'll close this issue and start Query Data section tomorrow.
