### ISSUE TITLE
Create FTT presentation

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#2431]
Will draft 2/24 after the Fearless workshop using that content as the base. Will send to teammates for review/edit on Monday 2/27

**Comment by lpgoldstein** [comment]
@eelzi-ONRR @cthomasONRR @AlexandracmONRR here is the [draft presentation].(https://doimspp.sharepoint.com/:p:/r/sites/NRRD/Shared%20Documents/General/Outreach/Proposals%20%26%20Presentations/FY23/FSI%20Tech%20Talk%20March%202023.pptx?d=waede7ca04b6e4ceaac907bcbfc9ba8b2&csf=1&web=1&e=9Wxv6
Please review when you get a chance. A lot of formatting issues because I pulled from different presentations. We have 45 minutes to present and 15 minutes for questions. Probably too many slides.

**Comment by lpgoldstein** [comment]
@AlexandracmONRR ready for your review - [draft presentation](https://doimspp.sharepoint.com/:p:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7BAEDE7CA0-4B6E-4CEA-AC90-7BCBFC9BA8B2%7D&file=FSI%20Tech%20Talk%20March%202023.pptx&_DSL=1&action=edit&mobileredirect=true)
Also huge thanks to @cthomasONRR for bringing me back from the edge with her thoughtful comments.

**Comment by AlexandracmONRR** [comment]
@lpgoldstein I've added my comments into this presentation. Let me know if you have any questions about them!

Also, I'd be happy to help present next week. I'm sure I could cover a bunch of the more introductory material about the team and general process and you could cover the more website-detailed sections.

**Comment by lpgoldstein** [comment]
@AlexandracmONRR Thanks so much for your help! I've incorporated your comments and would love to have you present.
