### ISSUE TITLE
Redesign consent form

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#2434]
Look into what is required in our consent form. If possible, consider making a wiki page and get verbal consent that participants received and read it.

**Comment by eelzi-ONRR** [comment]
I looked at the DOI policies that seem applicable and none indicate that a signed form is required for consent. But they also don't expressedly say that verbal consent is okay.

[DOI Web Standards Handbook](https://www.doi.gov/sites/doi.gov/files/elips/documents/386-dm-3-web-handbook-rev-1-april-2007-2-1.pdf)
[DOI Information Collection Progam Requirements](https://www.doi.gov/sites/doi.gov/files/elips/documents/381-dm-11.pdf)
[DOI Privacy Act Disclosure Procedures](https://www.doi.gov/sites/doi.gov/files/elips/documents/383-dm-7_0.pdf)
[OMB Circular A-130: Fair Information Practices](https://www.doi.gov/sites/doi.gov/files/elips/documents/386-dm-3-web-handbook-rev-1-april-2007-2-1.pdf)

**Comment by Maroyafaied** [comment]
@Maroyafaied review

**Comment by Maroyafaied** [comment]
@lpgoldstein @eelzi-ONRR  This looks good, I have no changes. Feel free to close this issue and open another for adding this to the wiki. Thanks

**Comment by Maroyafaied** [comment]
@lpgoldstein @eelzi-ONRR  This looks good, I have no changes. Feel free to close this issue and open another for adding this to the wiki. Thanks
