### ISSUE TITLE
Q2 Metrics -  NRRD & Blog

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2437]

**Comment by lpgoldstein** [comment]
@Maroyafaied This is ready for your review: https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/NRRD/NRRD%20Metrics/FY23%20Q2%20Metrics%20Highlights.docx?d=w9aea6a6c2e584aff86760970170d172b&csf=1&web=1&e=vseulk
I can incorporate your comments and close on Friday. We can also create another issue to review metrics next sprint if needed.
