### ISSUE TITLE
Update powerpoint templates 

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#2441]
update bullets - spacing and color.

**Comment by AlexandracmONRR** [comment]
Hi @lpgoldstein and @eelzi-ONRR - I made some edits to the PowerPoint template to improve the formatting, please review here:
https://doimspp.sharepoint.com/:p:/r/sites/NRRD/Shared%20Documents/General/Outreach/Template/ONRR-ODDD-Template.pptx?d=w51a9d6f56a1d442ba429ef3a6f7d2f73&csf=1&web=1&e=QgAouU

**Comment by lpgoldstein** [comment]
@AlexandracmONRR I love it! Thank you.
