### ISSUE TITLE
Register for Code for America

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#2444]

**Comment by Maroyafaied** [comment]
@lpgoldstein @cthomasONRR @eelzi-ONRR @AlexandracmONRR We all need to fill out the SF-182 even the speakers. For Erin & Alex, after you fill out the SF-182 and I sign it then you can ask Carrie to pay for the registration, the deadline is tomorrow to get the early brid fee. I'll try to find an example SF-182 I filed out before to use as a reference.

**Comment by cthomasONRR** [comment]
@Maroyafaied Is the conference's primary purpose training? Looks like we only have to do the SF-182 if that's the case 
![image](https://user-images.githubusercontent.com/72526208/221684502-166d4804-f2d2-4c49-9e21-479defc49ebc.png)

**Comment by cthomasONRR** [comment]
Also, I'm unclear if I have to actually register? Or because we're speakers we're automatically registered?

**Comment by lpgoldstein** [comment]
@cthomasONRR I emailed my contact to ask what we should do.

**Comment by lpgoldstein** [comment]
@cthomasONRR Kiana said we will get more information soon.

**Comment by lpgoldstein** [comment]
@cthomasONRR @Maroyafaied we will get a special code to register so we don't have to worry about the early bird deadline today.

**Comment by Maroyafaied** [comment]
@cthomasONRR I was told before that an SF-182 is required for attending anything outside of DOI Talent, I'll confirm with the workforce development office if it's necessary or not to fill it out.

**Comment by Maroyafaied** [comment]
There's no need to fill out the SF-182. Carrie will be registering Erin. I'll keep this issue open for the rest of us to register once we have the code.

**Comment by cthomasONRR** [comment]
@Maroyafaied I was also able to register for free
![image](https://user-images.githubusercontent.com/72526208/222540815-91d3eb1f-46db-4a96-b893-d3810a8601c7.png)

**Comment by lpgoldstein** [comment]
@Maroyafaied just registered as well.
