### ISSUE TITLE
Code for America prep

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#2457]
- Figure out best format for slide template (stay in Google Slides or move to Microsoft PPT?)

- Decide on talk topics

- Create presentation for the talk

**Comment by cthomasONRR** [comment]
Meeting set for Wednesday 3/15 @ 9am.

**Comment by Maroyafaied** [comment]
Conference Track: People Power + Community

Breakout Sessions will take place on May 16 & 17. Specific information regarding the time, date, and room will be shared with you mid-April. For breakout sessions, you will need to bring your own laptop and manage your slide deck. In the case of multiple presenters, we suggest you combine slides into one presentation and bring any additional attachments you may need for your computer (i.e. dongles). We will provide A/V equipment such as projectors, screens, microphones, etc. 

Each session will be 45 minutes to 1 hour and should allow for 10-15 minutes of Q&A. 


Slide Template

Here is the Code for America [slide template](https://docs.google.com/presentation/d/1QFahCW7axJsntGePzIoQ2f6Bm7uYVuyafsnZICracPw/edit#slide=id.g7d674d7cb7_0_545). Please make a copy of the slide template and edit the copy with your content. This is the template for any slides you may use at Summit. Other templates are not allowed. For breakout sessions, your group is responsible for your slide deck.

**Comment by Maroyafaied** [comment]
https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Outreach/Proposals%20%26%20Presentations/FY23/CFA%20Brainstorming%20.docx?d=wed7a8f6d4f7b4fd3811d712e82ab5995&csf=1&web=1&e=P8bTm6

**Comment by cthomasONRR** [comment]
@Maroyafaied @lpgoldstein I'm going to close this issue and create a new one just for making the PowerPoint.
