### ISSUE TITLE
TOC link causes error

### ISSUE THREAD

**Issue by greensomes** [DOI-ONRR/nrrd#2458]
While reviewing the site during Gatsby upgrade, I observed that clicking the "Quartz crystal units" table of contents link on [Production by Year](https://revenuedata.doi.gov/downloads/production) results in a fatal page error.

To reproduce the error, go to the Production by Year page and scroll down until the About the data table of contents expands on the left. After clicking the "Quartz crystal units" link, a fatal message is shown.

The cause of the issue is the `/` in the `<h3>` with text "Why is quartz crystal measured in “tickets/pounds”?".

**Comment by cthomasONRR** [comment]
Fix is in PR #3660
