### ISSUE TITLE
Google Analytics - GA360 report inventory

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#2461]
- Inventory all current customized reports and dashboards. 

- Decide if any are irrelevant and do not need to be recreated in GA4.

- Document how these reports were created.

**Comment by cthomasONRR** [comment]
Summary of GA4 training resources:

[Google Analytics 4 Course (2023) - Plan, Setup, Reports, Insights (analyticsmania.com)](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.analyticsmania.com%2Fcourses%2Fgoogle-analytics-4-course%2F&data=05%7C01%7Cchristine.thomas%40ONRR.GOV%7Cc4b1bd4ab0784f9e156b08db3b8bfbad%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638169244639817781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iZwJy9AC0n7rq6%2Br29tEsBmfqKJZjiEC9QHaeqEdziM%3D&reserved=0)

[Google Analytics 4 (GA4) Essential Training - LinkedIn](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Flearning-login%2Fshare%3Faccount%3D107517418%26forceAccount%3Dfalse%26redirect%3Dhttps%253A%252F%252Fwww.linkedin.com%252Flearning%252Fgoogle-analytics-4-ga4-essential-training-14915362%253Ftrk%253Dshare_ent_url%2526shareId%253DO%25252BMrUdUCSMKDNFTYi8ZT5Q%25253D%25253D&data=05%7C01%7Cchristine.thomas%40ONRR.GOV%7Cc4b1bd4ab0784f9e156b08db3b8bfbad%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638169244639817781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=I%2FkarR9LREd9yzzAokf8faZK0krepqsX1HXTKJS2jUY%3D&reserved=0)

[Advanced Google Analytics 4 (GA4) - LinkedIn](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Flearning%2Fadvanced-google-analytics-4-ga4%3Fu%3D0&data=05%7C01%7Cchristine.thomas%40ONRR.GOV%7Cc4b1bd4ab0784f9e156b08db3b8bfbad%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638169244639817781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mzmmsWGuF0GL8IPiMOru4mCZxzTFHUoAI9Rx1CYwXNI%3D&reserved=0)

Google Analytics Playlist: [https://youtube.com/playlist?list=PLI5YfMzCfRtYX8la4_SjNOMa2SUvaioeB](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fyoutube.com%2Fplaylist%3Flist%3DPLI5YfMzCfRtYX8la4_SjNOMa2SUvaioeB&data=05%7C01%7Cchristine.thomas%40ONRR.GOV%7Cc4b1bd4ab0784f9e156b08db3b8bfbad%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638169244639817781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Fkn3bUmF8xwL2upazI%2BWXhbA3YVO%2FKCJqFU965QBY%2BM%3D&reserved=0)

Other You Tube training:
[https://youtu.be/cN1Jcfxi4qs](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fyoutu.be%2FcN1Jcfxi4qs&data=05%7C01%7Cchristine.thomas%40ONRR.GOV%7Cc4b1bd4ab0784f9e156b08db3b8bfbad%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638169244639817781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uXnZTHvmBNEeMLqxc5Agno3DyXspmZJYdovhzNM%2Bh9g%3D&reserved=0)
[https://youtu.be/Xzvn_kBmIRw](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fyoutu.be%2FXzvn_kBmIRw&data=05%7C01%7Cchristine.thomas%40ONRR.GOV%7Cc4b1bd4ab0784f9e156b08db3b8bfbad%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638169244639817781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0%2F6lbJ0x6R%2BTNOacJlwqQ96Xm1gYZFijW89t8wHx9ZI%3D&reserved=0)

Google Analytics Certification: 
[https://skillshop.exceedlms.com/student/catalog/list?category_ids=6431-google-analytics-4](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fskillshop.exceedlms.com%2Fstudent%2Fcatalog%2Flist%3Fcategory_ids%3D6431-google-analytics-4&data=05%7C01%7Cchristine.thomas%40ONRR.GOV%7Cc4b1bd4ab0784f9e156b08db3b8bfbad%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638169244639817781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=I4AeBPVt5URmSowYPBzlG7iVGYMrcz8JxxOQsm7ICd8%3D&reserved=0)

Guides:
[Google Analytics 4 Tutorial for Beginners (2023) - Analytics Mania](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.analyticsmania.com%2Fpost%2Fgoogle-analytics-4-tutorial-for-beginners%2F&data=05%7C01%7Cchristine.thomas%40ONRR.GOV%7Cc4b1bd4ab0784f9e156b08db3b8bfbad%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638169244639817781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9ISm4zIrm%2FxNjj4vo1wWJ%2FnFLkq427Ip4TFbOr7ecj8%3D&reserved=0)
[Get to Know Google Analytics 4: A Complete Guide (searchenginejournal.com)](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.searchenginejournal.com%2Fgoogle-analytics-4-guide%2F407452%2F&data=05%7C01%7Cchristine.thomas%40ONRR.GOV%7Cc4b1bd4ab0784f9e156b08db3b8bfbad%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638169244639817781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2R4vt%2FEgLrPGx3Gak%2BkuW4mWVK2qszkXoGeZPgY7P6c%3D&reserved=0)
[How to migrate to Google Analytics 4: A step-by-step guide (searchengineland.com)](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsearchengineland.com%2Fgoogle-analytics-4-migration-guide-386201&data=05%7C01%7Cchristine.thomas%40ONRR.GOV%7Cc4b1bd4ab0784f9e156b08db3b8bfbad%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C638169244639817781%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=musRWbfx3%2Bx8zCelxyxDpRb3S%2FpEQHoJ72mXN%2FCDvXg%3D&reserved=0)

**Comment by cthomasONRR** [comment]
GA4 Trainings by Google:
https://skillshop.exceedlms.com/student/catalog/list?category_ids=6431-google-analytics-4

**Comment by cthomasONRR** [comment]
@eelzi-ONRR 

I made a report inventory here: https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/NRRD/Content/FY23/GoogleAnalytics360_ReportInventory.docx?d=w0c4cc29cd04b47819d861c4a86fd8a47&csf=1&web=1&e=S4hJvu)?d=w0c4cc29cd04b47819d861c4a86fd8a47&csf=1&web=1&e=S4hJvu

The first part of this doc is a report inventory table, showing which analytics are used in which repo. I added some basic instructions on what we actually publish on the wiki. I also added a "Comments" column where I suggested which analytics we could likely remove for GA4. Please feel free to add your own comments here as well.

If you open the doc's Navigation pane, I have sections for each analytic type. In these sections, I put screen grabs that show how each report was made. I'm not sure if this will be helpful for GA4, but at least we have it all recorded now.

Please add in your comments and let me know if you'd like to discuss. Thanks!

**Comment by eelzi-ONRR** [comment]
@cthomasONRR I think you documented everything we need! 

I don't totally agree that we should remove the dashboards or any other metrics though. I absolutely think we can and should pare down what you pull for the monthly analytics. We can do that and still track things in Google Analytics that we might use less often, but are still really helpful (for example, I check the dashboards pretty regularly, and we might need to use device metrics to determine how much we need to prioritize our mobile sites). But I do think you're comments are a good starting point for how we can reconsider what we do with our anlytics!

**Comment by cthomasONRR** [comment]
@eelzi-ONRR 

Good points! I should have clarified that when I'm suggesting "Remove", it's to remove them from the monthly analytics that we publish. I clarified then the doc.

I'm definitely game for trying to replicate the analytics we currently collect on GA4.
