### ISSUE TITLE
Update ODDD page on onrresource

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#2467]

**Comment by eelzi-ONRR** [comment]
https://onrresource/Data-Display

I updated our team members, added our logo, added ODDD to the page title, updated the links that went to the old GitHub, and added onrr.gov to the resource links.

Our page is more minimal than most other teams, but since we have all our info in the open and on GitHub, I think it's good to keep our onrresource page simple.

@Maroyafaied @cthomasONRR @lpgoldstein  @AlexandracmONRR Can you all double check your name/email listing is correct? Thx!

**Comment by lpgoldstein** [comment]
@eelzi-ONRR mine looks good too. Thank you!

**Comment by AlexandracmONRR** [comment]
@eelzi-ONRR looks good for me!

**Comment by Maroyafaied** [comment]
@eelzi-ONRR my info is correct, can we add the onrrweb mailbox as well here , also Data Display is our old team name, is there a way to change the url to the new team name or just ODDD?

![image](https://user-images.githubusercontent.com/40175688/224835836-549be6a5-5d89-4a92-a3a0-2a21b210d94b.png)
![image](https://user-images.githubusercontent.com/40175688/224835930-ad2dbe9e-94bb-4494-88c3-0f990740cdfc.png)

**Comment by eelzi-ONRR** [comment]
@Maroyafaied 
Do you want to label our two mailboxes as "report issues for ..." [each respective website], or just list them both as team mailboxes?

**Comment by Maroyafaied** [comment]
@eelzi-ONRR Yes let's specify what each mailbox is for. Thanks

**Comment by eelzi-ONRR** [comment]
onrrweb added!

I've opened a ticket to request they change our URL. It is possible and very easy - I just don't have permissions to edit the Program Areas menu - so that will break if I change our URL alias

**Comment by eelzi-ONRR** [comment]
@Maroyafaied The drupal developer gave us a new URL and updated the menu accordingly, so I'll close this issue: 

https://onrresource/ODDD
