### ISSUE TITLE
Homepage comparison table - alter math equation to calculate absolute value 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2473]
Upper management noticed this bug in the homepage where the current value is negative or less than the previous year value so the arrow should be going up not down. I believe the code for this is here https://github.com/DOI-ONRR/nrrd/blob/dev/src/components/sections/ComparisonTable/ComparisonTable.js

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/0bc1d836-c8e3-4289-9078-434230651333)

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/4bc0a333-b317-49cb-b500-65456a73f14d)

**Comment by lpgoldstein** [comment]
@Maroyafaied @greensomes Proof of fix
![image](https://user-images.githubusercontent.com/39419003/224402906-7eab5a49-a1ae-4fb3-8d0c-07e9ac2c8d5f.png)
