### ISSUE TITLE
Enforce Https

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2476]
We received a request to enforce https on the NRRD site and was given the link below to reference 

https://www.cisa.gov/news-events/directives/binding-operational-directive-18-01

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/5d2c8966-a63f-4894-823d-6f4c6abc9755)

**Comment by Maroyafaied** [comment]
https://https.cio.gov/

**Comment by Maroyafaied** [comment]
I'm working with a DOI coordinator to resolve this so pulling it in this sprint.

**Comment by Maroyafaied** [comment]
I got confirmation that we are compliant now. ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/7e80470f-9d37-4a17-b28a-6eec1cb4d8a3)

**Comment by greensomes** [comment]
Closing issues even while on vacation! Ooh, here comes Stitch! Lol!On Apr 3, 2023, at 9:40 AM, Maroyafaied ***@***.***> wrote:﻿
Closed #2476 as completed.
