### ISSUE TITLE
Talk through acting 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2480]

**Comment by Maroyafaied** [comment]
@AlexandracmONRR here are some goals for next sprint:
Q2 Metrics for onrr.gov and nrrd, Fix ARIA attributes to match their role (onrr.gov), Fix heading tags (onrr.gov), Fix links from nrrd content audit, publish redesign process blog, Review CFA presentation, Continue gatsby upgrade (nrrd), Revisit user study findings for navigation menu (onrr.gov).

**Comment by AlexandracmONRR** [comment]
@Maroyafaied thanks for sending along - i've noted this and will use during sprint review!
