### ISSUE TITLE
Consent Form Hallway Interviews

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#2492]

**Comment by lpgoldstein** [comment]
We have one more interview next week so moving to next sprint

**Comment by eelzi-ONRR** [comment]
Spoke  with 3 users total - two internal and one external. All three thought the process was clear. 

As a result of hallway interviews, added a chart and details to the wiki for users on the process.  We can continue to ask if this process is clear when we use it in future research
