### ISSUE TITLE
Review Code for America PPT

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#2499]
https://doimspp.sharepoint.com/:p:/r/sites/NRRD/Shared%20Documents/General/Outreach/Proposals%20%26%20Presentations/FY23/CfA%20Presentation_ONRR.pptx?d=web85bc43de4943528df3e8208250acff&csf=1&web=1&e=7A8LdS

**Comment by cthomasONRR** [comment]
@Maroyafaied I finished changing slide templates and am done editing.

**Comment by Maroyafaied** [comment]
@cthomasONRR @lpgoldstein I reviewed and made a few edits and left a couple of comments. It's looking great, we can use it to start practicing our presentation and make any necessary edits as they come up but I don't have any other major edits.

**Comment by cthomasONRR** [comment]
@Maroyafaied Great, I just finished addressing your comments. I'll close this issue and we can set up new issues to practice presenting.
