### ISSUE TITLE
Alt text for svg elements

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#2524]
**OCIO Violation:** Provide alternative text for images

**OCIO Note:** This svg element does not have a mechanism that allows an accessible name value to be calculated

**OCIO priority:** 10

More info in [this sheet](https://doimspp.sharepoint.com/:x:/s/NRRD/Ea-CVbPsGDpDkDLSIe6kZS8BNeTJ7C8_M7yRS86t6VEU2g?e=IXABwa) or the [ocio/amp dashboard](https://departmentofinterior.levelaccess.us/login.php)

**Instances**

- [x] colored squares in the bar chart keys that indicate the unique recipeints, sources, etc. (found on [fact sheet](https://revenuedata.doi.gov/fact-sheet/), [homepage](https://revenuedata.doi.gov/))

- [x] disbursements bar chart ([fact sheet](https://revenuedata.doi.gov/fact-sheet/), [homepage](https://revenuedata.doi.gov/)) 

- [x] production bar chart ([homepage](https://revenuedata.doi.gov/)) 

- [x] file box icon ([audits & assurances](https://revenuedata.doi.gov/how-revenue-works/audits-and-assurances))

- [x] gas bar chart ([fact sheet](https://revenuedata.doi.gov/fact-sheet/))

- [x] Oil bar chart ([fact sheet](https://revenuedata.doi.gov/fact-sheet/))

- [x] revenue bar chart  ([fact sheet](https://revenuedata.doi.gov/fact-sheet/), [homepage](https://revenuedata.doi.gov/))

- [x] trend lines ([Query Data](https://revenuedata.doi.gov/query-data/?dataType=Disbursements))

- [x] line arrows that connect ownership, leasing, production, revenue, disbursements boxes ([How Revenue Works](https://revenuedata.doi.gov/how-revenue-works))

- [x] Map legend in lower left corner of map ([Explore Data](https://revenuedata.doi.gov/explore/?dataType=Revenue&location=NF,NA&mapLevel=State&offshoreRegions=false&period=Calendar%20Year&year=2022))

- [x] ONRR logo ([About](https://revenuedata.doi.gov/about/), [fact sheet](https://revenuedata.doi.gov/fact-sheet/), [Minerals](https://revenuedata.doi.gov/how-revenue-works/minerals))

- [x] Progress bar on the compare revenue cards, nationwide revenue summary, etc. ([Explore data](https://revenuedata.doi.gov/explore/?dataType=Revenue&location=NF,NA&mapLevel=State&offshoreRegions=false&period=Calendar%20Year&year=2022))

- [x] ribbon graphic - major commodities in the U.S. ([How Revenue Works](https://revenuedata.doi.gov/how-revenue-works))

- [x] Tool tip question mark icon (many many pages. Lots can be found on [How Revenue Works](https://revenuedata.doi.gov/how-revenue-works))

**Comment by AlexandracmONRR** [comment]
@greensomes - please see the following alt text for the different svg images.

**Colored squares in the bar chart keys that indicate the unique recipients, sources, etc. (found on fact sheet, homepage)** 

- **Disbursements by Recipient:** Small colored squares are used to indicate the different fund recipients, which are then associated with dollar amounts. Yellow represents other funds; lime green represents Historic Presentation Fund; medium green represents Land and Water Conservation Fund; teal represents Native American tribes and individuals; medium blue represents Reclamation Fund; dark blue represents state and local governments; and dark purple represents U.S. Treasury. 
- **Revenue by source:** Small colored squares are used to indicate the different revenue sources, which are then associated with dollar amounts. Yellow represents Federal that is not tied to a lease; green represents Native American; blue represents Federal offshore; and purple represents Federal onshore. 
- **Revenue by revenue type:** Small colored squares are used to indicate the different revenue types, which are then associated with dollar amounts. Yellow represents other revenues; lime green represents inspection feeds; medium green represents civil penalties; medium blue represents rents; dark blue represents bonus; and dark purple represents royalties. 
- **Production (Oil, Gas, and Coal):** Small colored squares are used to indicate the different production sources, which are then associated with dollar amounts. Yellow represents Native American; teal represents Federal offshore; and purple represents Federal onshore. 
- **Disbursements by Source (just in case we do not already have this description on Homepage):**  Small colored squares are used to indicate the different disbursement sources, which are then associated with dollar amounts. Yellow represents Native American; teal represents Federal offshore; and purple represents Federal onshore. 
- **Revenue by Commodity (just in case we do not already have this description on Homepage):** Small colored squares are used to indicate the different commodity types, which are then associated with dollar amounts. Yellow represents not tied to a commodity; lime green represents other commodities; teal represents coal; medium blue represents rents; dark blue represents gas; and dark purple represents oil. 

**Disbursements bar chart (fact sheet) - Disbursements by Recipient:** The bar chart shows the disbursements within the past 12 months, which often extend across 2 calendar years. The bar for each month shows the total amount of money paid to recipients, which is further broken down into money paid to recipients, and different recipients are represented by different colors.  

**File box icon (audits & assurances):** A simple black and white icon of a file box with lid and handle. 

**Gas bar chart (fact sheet):**  Production (Gas): The bar chart shows gas production in million cubic feet within the past 12 months, which often extends across 2 calendar years. The bar for each month shows the total gas produced, and different sources are represented by different colors. 

**Coal bar chart (Alex added in) - Production (Coal):** The bar chart shows coal production in tons within the past 12 months, which often extends across 2 calendar years. The bar for each month shows the total coal produced, and different sources are represented by different colors. 

**Oil bar chart (fact sheet) - Production (Oil):** The bar chart shows oil production in barrels within the past 12 months, which often extends across 2 calendar years. The bar for each month shows the total oil produced, and different sources are represented by different colors. 

**Revenue bar chart (fact sheet, homepage) - Revenue by source:** The bar chart shows the revenue within the past 12 months, which often extends across 2 calendar years. The bar for each month shows the total amount of money collected, and different revenue sources are represented by different colors.  

**Revenue by revenue type:** The bar chart shows the revenue within the past 12 months, which often extends across 2 calendar years. The bar for each month shows the total amount of money collected, and different revenue types are represented by different colors. 

**Trend lines (Query Data):** A simple line that shows the trend of dollars over a 20-year period. These lines often show fluctuations over this period. 

**Line arrows that connect ownership, leasing, production, revenue, disbursements boxes (How Revenue Works):** A black arrow centered over a black line that indicates where the user should go next in the content. 

**Map legend in lower left corner of map (Explore Data):** A long rectangular color swatch that ranges from light color to dark color. The light color represents low number in the value of the data and as the color becomes increasingly darker the value of the data increases. 

**ONRR logo (About, fact sheet, Minerals):** A six-color logo with the ONRR acronym in large text in the top left corner, and in smaller text below it, “Office of Natural Resources Revenue”. Behind the text is a partial sun with beams in a light blue and slightly darker blue color. Dark blue and dark purple mountains are located in the middle of the logo with white icons of a windmill, an oil pumpjack, and trees. A white offshore oil rig in the bottom-right corner is separated by the mountains by a two-tone green arc.  

**Progress bar on the compare revenue cards, nationwide revenue summary, etc. (Explore data):** A line graph that shows the change in the value of the data over time. This graph compares Nationwide Federal and Native American sources.  

**Ribbon graphic - major commodities in the U.S. (How Revenue Works):** A graphic with the title text in blue, “Major commodities in the U.S.”; this includes an icon of a fire with the label “Natural gas” below, an icon of an oil pumpjack with the label “Oil” below, an icon of a cart with a dark substance piled in it with the label “Coal” below, and a simple icon of a windmill with the label “Renewables”. 

**Tool tip question mark icon (many pages. Lots can be found on How Revenue Works):** An icon of a black question mark inside a circle that indicates more information.

**Comment by Maroyafaied** [comment]
@eelzi-ONRR is it only the revenue bar charts in the home page that are missing the alt text? I was curious if the disbursements and production charts are also missing the alt texts?

**Comment by eelzi-ONRR** [comment]
@Maroyafaied I double checked the report and the disbursements table on the homepage is not included. Howeveer, when I checked using ANDI, the disbursements table is the same as the revenue table - the SVG doesn't have any output for screen readers. So it seems that the OCIO report didn't pick up on the different tabs on the NRRD homepage. This means that the disbursements and production tables both need alt text as well. I'll add those to the list above

**Comment by greensomes** [comment]
The Access assistant is showing that the Commodities circle charts in explore data are also lacking alt text. @Maroyafaied or @eelzi-ONRR, can someone please provide this? Thanks!

**Comment by eelzi-ONRR** [comment]
@greensomes 
**Commodities:** Commodities bubble chart shows the top commodities for the location selected. Different sized circles are used to reflect the difference in revenue for each commodity. The accompanying text details the commodities and the revenue amounts.

**Comment by Maroyafaied** [comment]
@eelzi-ONRR thanks for providing alt text for the circle charts.  @greensomes  It looks like Alex already provided alt text that can be used for the bar charts on the homepage. Here's the alt text for each tab & breakouts. 

### Revenue Tab
**Revenue by source:** The bar chart shows the revenue within the past 12 months, which often extends across 2 calendar years. The bar for each month shows the total amount of money collected, and different revenue sources are represented by different colors.
**Revenue by revenue type:** The bar chart shows the revenue within the past 12 months, which often extends across 2 calendar years. The bar for each month shows the total amount of money collected, and different revenue types are represented by different colors.
**Revenue by Commodity:** Small colored squares are used to indicate the different commodity types, which are then associated with dollar amounts. Yellow represents not tied to a commodity; lime green represents other commodities; teal represents coal; medium blue represents rents; dark blue represents gas; and dark purple represents oil.

### Disbursements Tab
**Disbursements by Source:** Small colored squares are used to indicate the different disbursement sources, which are then associated with dollar amounts. Yellow represents Native American; teal represents Federal offshore; and purple represents Federal onshore.
**Disbursements by Recipient:** The bar chart shows the disbursements within the past 12 months, which often extend across 2 calendar years. The bar for each month shows the total amount of money paid to recipients, which is further broken down into money paid to recipients, and different recipients are represented by different colors.

### Production
 **Production (Gas):** The bar chart shows gas production in million cubic feet within the past 12 months, which often extends across 2 calendar years. The bar for each month shows the total gas produced, and different sources are represented by different colors.
**Production (Coal):** The bar chart shows coal production in tons within the past 12 months, which often extends across 2 calendar years. The bar for each month shows the total coal produced, and different sources are represented by different colors.
 **Production (Oil)**: The bar chart shows oil production in barrels within the past 12 months, which often extends across 2 calendar years. The bar for each month shows the total oil produced, and different sources are represented by different colors.

**Comment by greensomes** [comment]
The home page tabs have been updated to reflect the changes above. Also, the circle charts have been updated on explore data to include the description @eelzi-ONRR provided. Thanks!

**Comment by Maroyafaied** [comment]
@greensomes here's alt text for explore data horizontal charts, there are 2 charts for the revenue data type and 1 chart for disbursements.

**Nationwide revenue by revenue type and source:** A horizontal bar chart displaying nationwide revenue for the latest calendar year by revenue type and broken down by source. Each source is represented by a different color.
**Federal revenue by company:** A horizontal bar chart displaying federal revenue for the latest calendar year by company and broken down by revenue type. Each revenue type is represented by a different color  
**Nationwide disbursements by recipient and source:** A horizontal bar chart displaying nationwide disbursements for the latest fiscal year by recipient and broken down by source. Each source is represented by a different color.

**Comment by greensomes** [comment]
Making progress. The horizontal bar charts on the home page are done. I noticed that I applied the same text to the Revenue types bubble chart as I did for the Commodities chart. That's confusing. @eelzi-ONRR, can you provide text for the Revenue types bubble charts? ![image.png](https://images.zenhubusercontent.com/6361168797f5f7285b87509f/5db4371d-ffe9-43c9-8254-0b1ed1347504)

**Comment by Maroyafaied** [comment]
@greensomes I just realized that the royalty by revenue type table for the circle chart is mislabeled, the column on the left shouldn't say "commodity" it should be "revenue type". I'll confirm on slack

**Comment by Maroyafaied** [comment]
I'm adding screenshots of info I found on how to write effective alt txt for complex visuals. Here's an example I drafted based on this info 
**Revenue by source - monthly:** Bar chart displaying the amount of revenue collected on a monthly basis by source, refer to the data table following the chart for detailed data for each bar.  Source data

 ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/604c7a05-4577-4a8b-be3c-d659d86e318b) ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/20504a4a-c6b2-44ff-898a-0cbff9766d2c) ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/4544b387-67d8-44a9-9c64-e0cdb4578a9c)

**Comment by Maroyafaied** [comment]
@lpgoldstein @eelzi-ONRR please review the alt text description I've drafted below. Thanks

### Homepage monthly revenue charts
**Revenue by source - monthly:** Bar chart displaying the amount of revenue collected on a monthly basis by source, refer to the data table following the chart for detailed data for each bar.  [Source data](https://revenuedata.doi.gov/downloads/revenue/)
**Revenue by revenue type - monthly:** Bar chart displaying the amount of revenue collected on a monthly basis by revenue type, refer to the data table following the chart for detailed data for each bar.  [Source data](https://revenuedata.doi.gov/downloads/revenue/)
**Revenue by commodity - monthly:** Bar chart displaying the amount of revenue collected on a monthly basis by commodity, refer to the data table following the chart for detailed data for each bar.  [Source data](https://revenuedata.doi.gov/downloads/revenue/)
### Homepage monthly revenue charts
**Revenue by source -yearly:** Bar chart displaying the amount of revenue collected on a yearly basis by source, refer to the data table following the chart for detailed data for each bar.  [Source data](https://revenuedata.doi.gov/downloads/revenue/)
**Revenue by revenue type - yearly:** Bar chart displaying the amount of revenue collected on a yearly basis by revenue type, refer to the data table following the chart for detailed data for each bar.  [Source data](https://revenuedata.doi.gov/downloads/revenue/)
**Revenue by commodity - yearly:** Bar chart displaying the amount of revenue collected on a yearly basis by commodity, refer to the data table following the chart for detailed data for each bar.  [Source data](https://revenuedata.doi.gov/downloads/revenue/)
### Homepage monthly disbursements charts
**Disbursements by Recipient - monthly:** Bar chart displaying the amount of disbursements collected on a monthly basis by source, refer to the data table following the chart for detailed data for each bar.  [Source data](https://revenuedata.doi.gov/downloads/disbursements-by-month/)
**Disbursements by Source - monthly:** Bar chart displaying the amount of disbursements on a monthly basis by source, refer to the data table following the chart for detailed data for each bar.  [Source data](https://revenuedata.doi.gov/downloads/disbursements-by-month/)
### Homepage monthly disbursements charts
**Disbursements by Recipient - yearly:** Bar chart displaying the amount of disbursements collected on a yearly basis by source, refer to the data table following the chart for detailed data for each bar.  [Source data](https://revenuedata.doi.gov/downloads/disbursements-by-month/)
**Disbursements by Source - yearly:** Bar chart displaying the amount of disbursements on a yearly basis by source, refer to the data table following the chart for detailed data for each bar.  [Source data](https://revenuedata.doi.gov/downloads/disbursements-by-month/)
### Homepage monthly production charts
**Production gas - monthly:** Bar chart displaying the amount of gas produced on a monthly basis, refer to the data table following the chart for detailed data for each bar.  [Source data](https://revenuedata.doi.gov/downloads/production-by-month/)
**Production oil - monthly:** Bar chart displaying the amount of oil produced on a monthly basis, refer to the data table following the chart for detailed data for each bar.  [Source data](https://revenuedata.doi.gov/downloads/production-by-month/)
**Production coal - monthly:** Bar chart displaying the amount of coal produced on a monthly basis, refer to the data table following the chart for detailed data for each bar.  [Source data](https://revenuedata.doi.gov/downloads/production-by-month/)
### Homepage yearly production charts
**Production gas - yearly:** Bar chart displaying the amount of gas produced on a yearly basis, refer to the data table following the chart for detailed data for each bar.  [Source data](https://revenuedata.doi.gov/downloads/production-by-month/)
**Production oil - yearly:** Bar chart displaying the amount of oil produced on a yearly basis, refer to the data table following the chart for detailed data for each bar.  [Source data](https://revenuedata.doi.gov/downloads/production-by-month/)
**Production coal - yearly:** Bar chart displaying the amount of coal produced on a yearly basis, refer to the data table following the chart for detailed data for each bar.  [Source data](https://revenuedata.doi.gov/downloads/production-by-month/)
### Explore Data revenue circle charts
**Revenue by commodity circle chart** : Circle chart showing the top commodities generating revenue for the year and location selected.  Refer to the data table following the chart for detailed data for each circle.  [Source data](https://revenuedata.doi.gov/downloads/disbursements-by-month)
**Revenue by revenue type circle chart** : Circle chart showing the amount of revenue generated by revenue type for the year and location selected.  Refer to the data table following the chart for detailed data for each circle.  [Source data](https://revenuedata.doi.gov/downloads/disbursements-by-month)
### Explore Data production circle charts
**Production by location circle chart** : Circle chart showing the top producing locations for the year and commodity selected.  Refer to the data table following the chart for detailed data for each circle.  [Source data](https://revenuedata.doi.gov/downloads/production/)
### Explore Data disbursement circle charts
**Disbursements by recipient circle chart** : Circle chart showing the amount of disbursement by recipient for the year and location selected.  Refer to the data table following the chart for detailed data for each circle.  [Source data](https://revenuedata.doi.gov/downloads/disbursements/)
**Disbursements by source circle chart** : Circle chart showing the amount of disbursements by source for the year and location selected.  Refer to the data table following the chart for detailed data for each circle.  [Source data](https://revenuedata.doi.gov/downloads/disbursements/)

**Comment by lpgoldstein** [comment]
@maroyafaied looks good! Do we need to differentiate by calendar year, fiscal year, and most recent 12 months at all? Or is that too much detail?

**Comment by eelzi-ONRR** [comment]
@Maroyafaied Overall these are so much better! But I think we need to make it clear that the data in the chart can be found in the source file. So instead of just linking to the file, it should say something like, "Details available in the Source Data (.xlsx)" And I think the links need to go directly to the files, not the source data page.


@lpgoldstein from what we learned in Trusted Tester - does that sound right?

**Comment by lpgoldstein** [comment]
@Maroyafaied @eelzi-ONRR you are right. Let's link directly to the file and to the source data page? That page is important because it says what all of the data is.

**Comment by Maroyafaied** [comment]
@lpgoldstein I purposely didn't specify CY or FY or amount of months so the alt text can describe either. @eelzi-ONRR I made the change to source file text but there' s not  a way that I can link to the files directly that I can think of. I added "(.csv)" since data can be downloaded in that formatt as well. Here's the updated text 

### Homepage monthly revenue charts
**Revenue by source - monthly:** Bar chart displaying the amount of revenue collected on a monthly basis by source, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv) or  (.xlsx)](https://revenuedata.doi.gov/downloads/revenue/)
**Revenue by revenue type - monthly:** Bar chart displaying the amount of revenue collected on a monthly basis by revenue type, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv) or  (.xlsx)](https://revenuedata.doi.gov/downloads/revenue/)
**Revenue by commodity - monthly:** Bar chart displaying the amount of revenue collected on a monthly basis by commodity, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv) or  (.xlsx)](https://revenuedata.doi.gov/downloads/revenue/)
### Homepage yearly revenue charts
**Revenue by source -yearly:** Bar chart displaying the amount of revenue collected on a yearly basis by source, refer to the data table following the chart for detailed data for each bar.  [[Details available in the Source Data (.csv) or  (.xlsx)](https://revenuedata.doi.gov/downloads/revenue/)
**Revenue by revenue type - yearly:** Bar chart displaying the amount of revenue collected on a yearly basis by revenue type, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv) or  (.xlsx)](https://revenuedata.doi.gov/downloads/revenue/)
**Revenue by commodity - yearly:** Bar chart displaying the amount of revenue collected on a yearly basis by commodity, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv) or (.xlsx)](https://revenuedata.doi.gov/downloads/revenue/)
### Homepage monthly disbursements charts
**Disbursements by Recipient - monthly:** Bar chart displaying the amount of disbursements collected on a monthly basis by source, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv) or  (.xlsx)](https://revenuedata.doi.gov/downloads/disbursements-by-month/)
**Disbursements by Source - monthly:** Bar chart displaying the amount of disbursements on a monthly basis by source, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv) or  (.xlsx)](https://revenuedata.doi.gov/downloads/disbursements-by-month/)
### Homepage yearly disbursements charts
**Disbursements by Recipient - yearly:** Bar chart displaying the amount of disbursements collected on a yearly basis by source, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv) or  (.xlsx)](https://revenuedata.doi.gov/downloads/disbursements-by-month/)
**Disbursements by Source - yearly:** Bar chart displaying the amount of disbursements on a yearly basis by source, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv) or  (.xlsx)](https://revenuedata.doi.gov/downloads/disbursements-by-month/)
### Homepage monthly production charts
**Production gas - monthly:** Bar chart displaying the amount of gas produced on a monthly basis, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv) or  (.xlsx)](https://revenuedata.doi.gov/downloads/production-by-month/)
**Production oil - monthly:** Bar chart displaying the amount of oil produced on a monthly basis, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv) or  (.xlsx)](https://revenuedata.doi.gov/downloads/production-by-month/)
**Production coal - monthly:** Bar chart displaying the amount of coal produced on a monthly basis, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv) or (.xlsx)](https://revenuedata.doi.gov/downloads/production-by-month/)
### Homepage yearly production charts
**Production gas - yearly:** Bar chart displaying the amount of gas produced on a yearly basis, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv) or (.xlsx)](https://revenuedata.doi.gov/downloads/production-by-month/)
**Production oil - yearly:** Bar chart displaying the amount of oil produced on a yearly basis, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv) or (.xlsx)](https://revenuedata.doi.gov/downloads/production-by-month/)
**Production coal - yearly:** Bar chart displaying the amount of coal produced on a yearly basis, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv) or (.xlsx)](https://revenuedata.doi.gov/downloads/production-by-month/)
### Explore Data revenue circle charts
**Revenue by commodity circle chart** : Circle chart showing the top commodities generating revenue for the year and location selected.  Refer to the data table following the chart for detailed data for each circle.  [Details available in the Source Data (.csv) or (.xlsx)](https://revenuedata.doi.gov/downloads/disbursements-by-month)
**Revenue by revenue type circle chart** : Circle chart showing the amount of revenue generated by revenue type for the year and location selected.  Refer to the data table following the chart for detailed data for each circle.  [Details available in the Source Data (.csv) or (.xlsx)](https://revenuedata.doi.gov/downloads/disbursements-by-month)
### Explore Data production circle charts
**Production by location circle chart** : Circle chart showing the top producing locations for the year and commodity selected.  Refer to the data table following the chart for detailed data for each circle.  [Details available in the Source Data (.csv) or (.xlsx)](https://revenuedata.doi.gov/downloads/production/)
### Explore Data disbursement circle charts
**Disbursements by recipient circle chart** : Circle chart showing the amount of disbursement by recipient for the year and location selected.  Refer to the data table following the chart for detailed data for each circle.  [Details available in the Source Data (.csv) or  (.xlsx)](https://revenuedata.doi.gov/downloads/disbursements/)
**Disbursements by source circle chart** : Circle chart showing the amount of disbursements by source for the year and location selected.  Refer to the data table following the chart for detailed data for each circle.  [Details available in the Source Data (.csv) or (.xlsx)](https://revenuedata.doi.gov/downloads/disbursements/)

**Comment by Maroyafaied** [comment]
@greensomes @eelzi-ONRR This should the final text for alt text, I updated the links to the actual download files.

### Homepage monthly revenue charts
**Revenue by source - monthly:** Bar chart displaying the amount of revenue collected on a monthly basis by source, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv)](https://revenuedata.doi.gov/downloads/monthly_revenue.csv)
**Revenue by revenue type - monthly:** Bar chart displaying the amount of revenue collected on a monthly basis by revenue type, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv)](https://revenuedata.doi.gov/downloads/monthly_revenue.csv)
**Revenue by commodity - monthly:** Bar chart displaying the amount of revenue collected on a monthly basis by commodity, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv)](https://revenuedata.doi.gov/downloads/monthly_revenue.csv)
### Homepage yearly revenue charts
**Revenue by source -yearly:** Bar chart displaying the amount of revenue collected on a yearly basis by source, refer to the data table following the chart for detailed data for each bar.  [[Details available in the Source Data (.csv)](https://revenuedata.doi.gov/downloads/monthly_revenue.csv)
**Revenue by revenue type - yearly:** Bar chart displaying the amount of revenue collected on a yearly basis by revenue type, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv)](https://revenuedata.doi.gov/downloads/monthly_revenue.csv)
**Revenue by commodity - yearly:** Bar chart displaying the amount of revenue collected on a yearly basis by commodity, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv)](https://revenuedata.doi.gov/downloads/monthly_revenue.csv)
### Homepage monthly disbursements charts
**Disbursements by Recipient - monthly:** Bar chart displaying the amount of disbursements collected on a monthly basis by source, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv)](https://revenuedata.doi.gov/downloads/monthly_disbursements.csv)
**Disbursements by Source - monthly:** Bar chart displaying the amount of disbursements on a monthly basis by source, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv)](https://revenuedata.doi.gov/downloads/monthly_disbursements.csv)
### Homepage yearly disbursements charts
**Disbursements by Recipient - yearly:** Bar chart displaying the amount of disbursements collected on a yearly basis by source, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv)](https://revenuedata.doi.gov/downloads/monthly_disbursements.csv)
**Disbursements by Source - yearly:** Bar chart displaying the amount of disbursements on a yearly basis by source, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source (.csv)](https://revenuedata.doi.gov/downloads/monthly_disbursements.csv)
### Homepage monthly production charts
**Production gas - monthly:** Bar chart displaying the amount of gas produced on a monthly basis, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv)]( https://revenuedata.doi.gov/downloads/monthly_production.csv)
**Production oil - monthly:** Bar chart displaying the amount of oil produced on a monthly basis, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv)]( https://revenuedata.doi.gov/downloads/monthly_production.csv) 
**Production coal - monthly:** Bar chart displaying the amount of coal produced on a monthly basis, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv)]( https://revenuedata.doi.gov/downloads/monthly_production.csv)
 ### Homepage yearly production charts
**Production gas - yearly:** Bar chart displaying the amount of gas produced on a yearly basis, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv)]( https://revenuedata.doi.gov/downloads/monthly_production.csv) 
**Production oil - yearly:** Bar chart displaying the amount of oil produced on a yearly basis, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv)]( https://revenuedata.doi.gov/downloads/monthly_production.csv) 
**Production coal - yearly:** Bar chart displaying the amount of coal produced on a yearly basis, refer to the data table following the chart for detailed data for each bar.  [Details available in the Source Data (.csv)]( https://revenuedata.doi.gov/downloads/monthly_production.csv) 
### Explore Data revenue circle charts
**Revenue by commodity circle chart** : Circle chart showing the top commodities generating revenue for the year and location selected.  Refer to the data table following the chart for detailed data for each circle.  [Details available in the Source Data (.csv)](https://revenuedata.doi.gov/downloads/monthly_revenue.csv)
**Revenue by revenue type circle chart** : Circle chart showing the amount of revenue generated by revenue type for the year and location selected.  Refer to the data table following the chart for detailed data for each circle.  [Details available in the Source Data (.csv)](https://revenuedata.doi.gov/downloads/monthly_revenue.csv)
### Explore Data production circle charts
**Production by location circle chart** : Circle chart showing the top producing locations for the year and commodity selected.  Refer to the data table following the chart for detailed data for each circle.  [Details available in the Source Data (.csv)]( https://revenuedata.doi.gov/downloads/monthly_production.csv)
### Explore Data disbursement circle charts
**Disbursements by recipient circle chart** : Circle chart showing the amount of disbursement by recipient for the year and location selected.  Refer to the data table following the chart for detailed data for each circle.  [Details available in the Source Data (.csv)](https://revenuedata.doi.gov/downloads/monthly_disbursements.csv)
**Disbursements by source circle chart** : Circle chart showing the amount of disbursements by source for the year and location selected.  Refer to the data table following the chart for detailed data for each circle.  [Details available in the Source Data (.csv)](https://revenuedata.doi.gov/downloads/monthly_disbursements.csv)

**Comment by eelzi-ONRR** [comment]
@Maroyafaied I made corrections to these three. Otherwise they look great!

- Removed unncessary character beofre the link

**Revenue by source -yearly:** Bar chart displaying the amount of revenue collected on a yearly basis by source, refer to the data table following the chart for detailed data for each bar. [Details available in the Source Data (.csv)](https://revenuedata.doi.gov/downloads/monthly_revenue.csv)

- Changed "source" in the alt text to "recipient"

**Disbursements by Recipient - monthly:** Bar chart displaying the amount of disbursements collected on a monthly basis by recipient, refer to the data table following the chart for detailed data for each bar. [Details available in the Source Data (.csv)
](https://revenuedata.doi.gov/downloads/monthly_disbursements.csv)
**Disbursements by Recipient - yearly:** Bar chart displaying the amount of disbursements collected on a yearly basis by recipient refer to the data table following the chart for detailed data for each bar. [Details available in the Source Data (.csv)](https://revenuedata.doi.gov/downloads/monthly_disbursements.csv)

**Comment by Maroyafaied** [comment]
@eelzi-ONRR Do you think it's ok to have one general alt text for all the circle charts? It would say "Circle chart  for the year and location selected.  Refer to the data table following the chart for detailed data for each circle."  I only see one location in the code so not sure how to change it specific to each one.

**Comment by eelzi-ONRR** [comment]
@Maroyafaied I think the text for this one should be changed: 

**Map legend in lower left corner of map** (Explore Data): A long rectangular color swatch that ranges from light color to dark color. The light color represents low number in the value of the data and as the color becomes increasingly darker the value of the data increases.

Should be replaced with something like:: 

Map legend defining what the shades in the map coorelate to. The units and amounts in the legend change based on the selected data type, commodity, and period.

**Comment by eelzi-ONRR** [comment]
@Maroyafaied I think this could work for all the horizontal bar charts:

Stacked bar chart with one bar. See accompanying text for detailed units and amounts.
