### ISSUE TITLE
Remove "coal (tons) from commodity filter on Explore Data page in production data type

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#2529]
There is no "coal (tons)" in the production data set yet it appears in the commodity filter on the Explore Data page
https://revenuedata.doi.gov/explore/?commodity=Coal%20%28tons%29&dataType=Production&location=NF%2CNA&mapLevel=State&offshoreRegions=false&period=Fiscal%20Year&year=2021 

![image](https://user-images.githubusercontent.com/39419003/228792920-49f1da9a-5dd7-4262-bfeb-b84d8b3cec3e.png)
![image](https://user-images.githubusercontent.com/39419003/228793256-bf26e67d-319d-4dc3-ada5-f012f167ea31.png)

**Comment by Maroyafaied** [comment]
"tons" is used in the monthly data sets and in the monthly filter for production in the query tool but not used in the calendar year or fiscal year production data sets so it should be taken out from explore data. ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/58578488-1ff4-411f-82c2-87c9a0c5c18e)
