### ISSUE TITLE
Mid year accomplishments in DOI Talent

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2536]
Opening this for next sprint. Submitting mid-year  accomplishments is optional. If you'd like to submit your accomplishments please do so by  April 14th.

**Comment by cthomasONRR** [comment]
I submitted my mid-year accomplishments on DOI Talent.

**Comment by lpgoldstein** [comment]
I submitted my mid-year accomplishments in DOI Talent.
