### ISSUE TITLE
DHS Trusted Tester Certification, Module 4, part 2

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#2544]
**Trusted Tester Training for Web on Windows**

NOTE: We need ANDI and color contrast checker installed in order to complete most of this module.

Goal for this issue: Topics 2 -10.

- [x]  Student Code of Conduct
- [x]  Course Introduction
- [x]  Test Environment and Test Tools
- [x]  Topic 2: Auto-Playing and Auto-Updating Content
- [x]  Topic 3: Flashing
- [ ]  Topic 4: Keyboard Access and Focus
- [ ]  Topic 5: Forms
- [ ]  Topic 6: Links and Buttons
- [ ]  Topic 7: Images
- [ ]  Topic 8: Adjustable Time Limits
- [ ]  Topic 9: Repetitive Content
- [ ]  Topic 10: Content Structure
- [ ]  Topic 11: Language
- [ ]  Topic 12: Page Titles, Frames, and iFrames
- [ ]  Topic 13: Sensory Characteristics and Contrast
- [ ]  Topic 14: Tables
- [ ]  Topic 15: CSS Content and Positioning
- [ ]  Topic 16: Pre-Recorded Audio-Only, Video-Only, and Animations
- [ ]  Topic 17: Synchronized Media
- [ ]  Topic 18: Resize Text
- [ ]  Topic 19: Multiple Ways
- [ ]  Topic 20: Parsing
- [ ]  Topic 1: Conforming Alternate Version and Non-Interference
- [ ]  Conformance Reporting
- [ ]  Course Summary

**Comment by Maroyafaied** [comment]
@cthomasONRR this is the update I received when I asked yesterday
![image](https://user-images.githubusercontent.com/40175688/233133726-4668c684-ec76-4276-96f6-9c25e6e74734.png)

**Comment by cthomasONRR** [comment]
Closing as I don't think I will ever get back to this. Will reopen a new issue if I ever attempt DHS trusted tester again.
