### ISSUE TITLE
Develop Impact Expo Powerpoint - Intro to Usability Testing

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2581]

**Comment by AlexandracmONRR** [comment]
@eelzi-ONRR - I'm going to work on the powerpoint in this folder:

https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/Outreach/Proposals%20%26%20Presentations/FY23/ONRR%20Impact%20Expo%202023?csf=1&web=1&e=5ovKwf

**Comment by eelzi-ONRR** [comment]
@AlexandracmONRR Great! I'm add the the empty reserach plan template and the partially filled one for the activity to the folder

**Comment by eelzi-ONRR** [comment]
@Maroyafaied @lpgoldstein If you have time to review the powerpoint I would really appreciate it! There's a couple slides with weird spacing and I still need to run the accessibility check/add alt text, but if you can check for content and typos that would be great!

https://doimspp.sharepoint.com/:p:/r/sites/NRRD/Shared%20Documents/General/Outreach/Proposals%20%26%20Presentations/FY23/ONRR%20Impact%20Expo%202023/ONRR-ImpactExpo-UserResearch.pptx?d=wacd05014014b4977ac6fdddf247cfeac&csf=1&web=1&e=waY4Jf

**Comment by Maroyafaied** [comment]
@eelzi-ONRR Great job, it's very educational! I left a few comments but let's schedule a practice session since the comment about the random slide is probably not random and you have a plan for it during the presentation so it would be good for me to hear your presentation.

**Comment by eelzi-ONRR** [comment]
@Maroyafaied Thank you for your feedback! I made changes accordingly. I'll set up a time next sprint for a practice session

**Comment by eelzi-ONRR** [comment]
Send ppt to organizers on 5/31
