### ISSUE TITLE
Research and come up with plan for link targets

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/nrrd#2585]
WCAG best practice is to not have links open in a new tab unless it's necessary

https://www.w3.org/TR/WCAG20-TECHS/G200.html

**Comment by cthomasONRR** [comment]
This has been done within the following ONRR issue: https://github.com/DOI-ONRR/onrr.gov-site/issues/2564

All NRRD links open in the same tab. I created a separate issue for applying an external link indicator (#2941)
