### ISSUE TITLE
Write alt text descriptions for images 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2596]
Jeff needs the alt text for issue # 2524
More info in [this sheet](https://doimspp.sharepoint.com/:x:/s/NRRD/Ea-CVbPsGDpDkDLSIe6kZS8BNeTJ7C8_M7yRS86t6VEU2g?e=IXABwa) or the [ocio/amp dashboard](https://departmentofinterior.levelaccess.us/login.php)

**Instances**

- [x] colored squares in the bar chart keys that indicate the unique recipeints, sources, etc. (found on [fact sheet](https://revenuedata.doi.gov/fact-sheet/), [homepage](https://revenuedata.doi.gov/))

- [x] disbursements bar chart ([fact sheet](https://revenuedata.doi.gov/fact-sheet/))

- [x] file box icon ([audits & assurances](https://revenuedata.doi.gov/how-revenue-works/audits-and-assurances))

- [x] gas bar chart ([fact sheet](https://revenuedata.doi.gov/fact-sheet/))

- [x] Oil bar chart ([fact sheet](https://revenuedata.doi.gov/fact-sheet/))

- [x] revenue bar chart  ([fact sheet](https://revenuedata.doi.gov/fact-sheet/), [homepage](https://revenuedata.doi.gov/))

- [x] trend lines ([Query Data](https://revenuedata.doi.gov/query-data/?dataType=Disbursements))

- [x] line arrows that connect ownership, leasing, production, revenue, disbursements boxes ([How Revenue Works](https://revenuedata.doi.gov/how-revenue-works))

- [x] Map legend in lower left corner of map ([Explore Data](https://revenuedata.doi.gov/explore/?dataType=Revenue&location=NF,NA&mapLevel=State&offshoreRegions=false&period=Calendar%20Year&year=2022))

- [x] ONRR logo ([About](https://revenuedata.doi.gov/about/), [fact sheet](https://revenuedata.doi.gov/fact-sheet/), [Minerals](https://revenuedata.doi.gov/how-revenue-works/minerals))

- [x] Progress bar on the compare revenue cards, nationwide revenue summary, etc. ([Explore data](https://revenuedata.doi.gov/explore/?dataType=Revenue&location=NF,NA&mapLevel=State&offshoreRegions=false&period=Calendar%20Year&year=2022))

- [x] ribbon graphic - major commodities in the U.S. ([How Revenue Works](https://revenuedata.doi.gov/how-revenue-works))

- [x] Tool tip question mark icon (many many pages. Lots can be found on [How Revenue Works](https://revenuedata.doi.gov/how-revenue-works))

**Comment by AlexandracmONRR** [comment]
@Maroyafaied and @cthomasONRR - I've drafted the first versions of the alt text for the images. Could you review and make edits or comments within the document?

https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/NRRD/508/NRRD_Alt-Text-Images_Issue2596.docx?d=w242f2fc3d4be4c7f815b0d0c9a6cd8aa&csf=1&web=1&e=6f8lBZ

**Comment by cthomasONRR** [comment]
@AlexandracmONRR There are really good! My main question is that I think "Disbursements by Source" and "Revenue by Commodity" were left off the list for bar chart colored squares..

**Comment by AlexandracmONRR** [comment]
@cthomasONRR - it probably wasn't on purpose that they were left off. I will add those alt texts too so that there aren't any weird gaps in alt text (just in case).

**Comment by cthomasONRR** [comment]
@AlexandracmONRR Looks great, thanks!

**Comment by Maroyafaied** [comment]
@cthomasONRR @AlexandracmONRR Disbursement by source and Revenue by commodity are not in the monthly fact sheet. The list contained all the svg images that didn't have alt text

**Comment by cthomasONRR** [comment]
@Maroyafaied Ah sorry- there's a note on the list about them being found on the homepage, so that's why I thought they needed to be included.

**Comment by Maroyafaied** [comment]
@cthomasONRR It's actually good you pointed them out, in case they don't already have alt text on the homepage then we have them ready to add. @AlexandracmONRR Awesome job, I made a few very minor edits. Looks great.

**Comment by AlexandracmONRR** [comment]
@Maroyafaied and @cthomasONRR - great, Thanks for your review! I've accepted the changes and I will add this alt text to the other issue for Jeff.
