### ISSUE TITLE
Migrate applications to cflinuxfs4

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2610]
Hello! This notification is to make you aware that you are still running `cflinuxfs3` applications in your cloud.gov organization. Your applications will soon stop working unless you take action to migrate your applications to the cflinuxfs4, stack! Please follow the directions below to migrate your applications to the cflinuxfs4, stack. ## What should you do now for existing apps? For existing applications which were created under cflinuxfs3 you will need to update the stack declaration to cflinuxfs4, there are two common ways of doing this detailed below. The options below only have to be run once for each application on cflinuxfs3 , once the stack is set for an application, it is persistent until changed with any of these two steps. - Push the app manually and specify the stack with the cf cli: cf push MY-APP -s cflinuxfs4 - Use the stack-auditor cf cli plugin to change the stack without having to push the application. Documentation for using this plugin is at https://docs.cloudfoundry.org/adminguide/stack-auditor.html#change-stacks, the basic workflow is: - Install the plugin - Use the cf cli to target the org and space for your existing application - Run cf change-stack APP-NAME cflinuxfs4 to change the app to the cflinuxfs4 stack - Each application will take about a minute or so to run the cf change-stack... command depending on the size of the droplet. ## Additional information Please refer to the deprecation notice at https://cloud.gov/2023/04/27/cflinuxfs3-deprecation-update/ which will give you additional information.

We will also be hosting live demos on how to perform this process. These live demos will be hosted on a Zoom meeting once daily from Monday (5/15/2023) until Friday (5/19/2023) with the demos occurring from 1:30 PM ET to 2 PM ET. To attend this meeting please refer to the Zoom meeting information below.

Join ZoomGov Meeting
https://gsa.zoomgov.com/j/1602200070?pwd=SVFYU1Y5SEIzRGZ1OTZ3NlV6TitnZz09

**Comment by Maroyafaied** [comment]
@greensomes here's [an article](https://cloud.gov/2023/04/27/cflinuxfs3-deprecation-update/) explaining what this is about.  It mentions that if you push your Cloud Foundry applications as Docker containers with cf push --docker-image , these changes do not impact you. You did make an update to the image about 3 months ago for the nrrd so I'm not sure if this was the update is  needed. ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/5a196e93-98e3-496a-aa31-8d64d2d65a23)

**Comment by greensomes** [comment]
The following apps have been migrated to cflinuxfs4:

- hasura-sandbox-interface
- hasura-dev-interface
- hasura-prod-interface

**Comment by greensomes** [comment]
I'm investigating why the following apps error when I attempt to change the stack to cflinuxfs4:

- prod-onrr-cms
- onrr-psql-interface

**Comment by greensomes** [comment]
The list is now thus:

doi-onrr/prod/dev-onrr-cms cflinuxfs3 stopped
doi-onrr/dev/nrrd cflinuxfs3 stopped
doi-onrr/prod/onrr-psql-interface cflinuxfs3 started
doi-onrr/dev/preview-onrr-cms cflinuxfs3 started
doi-onrr/prod/preview-onrr-frontend cflinuxfs3 stopped
doi-onrr/prod/prod-onrr-cms cflinuxfs3 started

I've reached out to cloud.gov support for assistance on updating these.

**Comment by greensomes** [comment]
I observed that there was an error related to memory resources when I attempted to restate one of the above apps. After scaling down memory, I was able to migrate the remaining apps to cflinuxfs4.
