### ISSUE TITLE
Start agency-wide accessibiilty assessment

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#2620]
Complete what we are able to before passing along to other ONRR teams to complete sections relevant to them

**Comment by Maroyafaied** [comment]
@eelzi-ONRR would it be ok with you to close this issue since you did the work of answering the questions related to our team and opening an issue for next sprint to identify SME's for the remaining questions and contacting them?

**Comment by eelzi-ONRR** [comment]
@Maroyafaied I was waiting to ask you the same question :) I'll close it out and make a separate one for next sprint
