### ISSUE TITLE
Investigate why some applications failed restaging 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2624]
We recently updated buildpacks in use by your applications. You should
restage or redeploy your applications to take advantage of the update.

A rolling restage operation is the quickest way to upgrade without incurring
downtime. You may still want to leverage your deployment infrastructure to
perform the upgrade if you have compliance requirements for redeployment operations.

You can restage your applications by opening the command line and entering
the following commands:

  cf target -o doi-onrr -s dev ; cf restage --strategy rolling dev-nrrd

  cf target -o doi-onrr -s prod ; cf restage --strategy rolling nrrd

  cf target -o doi-onrr -s prod ; cf restage --strategy rolling blog-nrrd

  cf target -o doi-onrr -s dev ; cf restage --strategy rolling dev-blog-nrrd

  cf target -o doi-onrr -s prod ; cf restage --strategy rolling doi-extractives-data

  cf target -o doi-onrr -s dev ; cf restage --strategy rolling dev-onrr-frontend

  cf target -o doi-onrr -s staging ; cf restage --strategy rolling onrr-preview

  cf target -o doi-onrr -s dev ; cf restage --strategy rolling dev-onrr-cms

  cf target -o doi-onrr -s dev ; cf restage --strategy rolling preview-onrr-frontend

  cf target -o doi-onrr -s prod ; cf restage --strategy rolling prod-onrr-cms

  cf target -o doi-onrr -s prod ; cf restage --strategy rolling onrr-psql-interface

  cf target -o doi-onrr -s prod ; cf restage --strategy rolling prod-onrr-frontend

  cf target -o doi-onrr -s prod ; cf restage --strategy rolling beta-onrr-frontend

  cf target -o doi-onrr -s dev ; cf restage --strategy rolling hasura-sandbox-interface

  cf target -o doi-onrr -s prod ; cf restage --strategy rolling hasura-dev-interface

  cf target -o doi-onrr -s prod ; cf restage --strategy rolling hasura-prod-interface

  cf target -o doi-onrr -s prod ; cf restage --strategy rolling ssh-app

For more information about the buildpack update(s), please see the following release notes:

**Comment by greensomes** [comment]
The following apps have successfully restaged after updating to cflinuxfs4:

- hasura-sandbox-interface
- hasura-dev-interface
- hasura-prod-interface

**Comment by greensomes** [comment]
After updating the remaining apps to cflinuxfs4, the restagings were successful.
