### ISSUE TITLE
DAP code for NRRD and blog: include agency parameter

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#2661]
For revenuedata.doi.gov and blog-nrrd.doi.gov:

The DAP implementation on these pages appears to be non-standard. In particular, there is no 'agency' parameter being passed by these pages. Please review the implementation guidelines for including the 'agency' parameter located in the Code Capabilities Summary at the [DAP GitHub Repo](https://github.com/digital-analytics-program/gov-wide-code). This is not related to the GA4 transition.

**Comment by cthomasONRR** [comment]
Blog: ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/3ee83f99-2a91-472d-a43e-5baddb47af66)

NRRD: ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/d8da590b-b14e-4570-8bdb-e3c7976a69e3)

**Comment by Maroyafaied** [comment]
@greensomes this is onrr.gov code that has the agency parameter so I believe we need to add the id ![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/3df9fdbf-0aa8-439a-87d6-922f46733c10)
