### ISSUE TITLE
Agency-wide Accessibility Assessment - SME follow up

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#2672]
follow up to issue #2653 . Initial email sent to owners to answer their assigned questions. 

[spreadsheet](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7B3B854182-8F7D-4599-BBA0-3930C66C14AB%7D&file=FY-23%20Government-wide%20Section%20508%20Assessment%20Criteria%20-%20SME.xlsx&action=default&mobileredirect=true)

**Comment by Maroyafaied** [comment]
I sent a reminder email this morning and received out of office messages from Deb, Joe, Bill, and Christa.

**Comment by eelzi-ONRR** [comment]
We have all the SME answers. I'll make another issue to compile and submit next sprint
