### ISSUE TITLE
Q3 metrics

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#2673]

**Comment by lpgoldstein** [comment]
https://doimspp.sharepoint.com/:w:/s/NRRD/EQlpDXFLFDNBlJDmE-vO_a0Br97Ebiw4DsXTaD3W9pI66g?email=Maroya.Faied%40onrr.gov&e=plplUK

**Comment by Maroyafaied** [comment]
@lpgoldstein Great job! I left a couple minor comments.
