### ISSUE TITLE
Research Adobe accessibility upgrades & training options

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#2677]

**Comment by Maroyafaied** [comment]
This is the only feature I found related to accessibility. I don't think I have the adobe maker so not sure if this upgrade was implemented or not  
![image](https://github.com/DOI-ONRR/nrrd/assets/40175688/48212d09-5a9f-497a-9e7b-c5e18b8ffd6f)

**Comment by Maroyafaied** [comment]
@eelzi-ONRR and @lpgoldstein confirmed that we have the latest version and the above comment is the only change related to accessibility. Here's the [training link](https://www.microassist.com/classroom-training/course-schedule/) that Christina recommended. She's took the intermediate course and a couple of ONRR employees will be taking the intermediate one in September. Let me know if anyone is interested in taking the training and what level then we can take next steps. Tagging @cthomasONRR in case she's interested in taking the training. https://www.microassist.com/classroom-training/course-schedule/

**Comment by cthomasONRR** [comment]
@Maroyafaied These are the classes I took in summer 2021. They're really good, and they're why I can quickly remediate most documents. There are probably course updates that would be good for me to refresh on, but I probably don't need to take all thee (basic, intermediate, advanced, all each 1 day long) again so soon.
