### ISSUE TITLE
Investigate builds failing in CircleCi 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2684]
Builds are failing at nrrd-preview in the building gatsby step.

![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/cc6af5a3-30fc-4b8f-9623-3bcc7fe7b096)

**Comment by greensomes** [comment]
I've confirmed that the cimg/node-12.13-browsers [Docker image](https://hub.docker.com/layers/cimg/node/12.13-browsers/images/sha256-bec911491b07b4e4505c6094de1afbae817c283ff1b1fe3fd644f4aab781ed4d?context=explore) has not been updated in a year.

**Comment by Maroyafaied** [comment]
To fix this issue, @greensomes  pushed the following 
- Updated the image for nrrd-preview to cimg/node:12.13.1-browsers 
-  reinstalled all node dependencies after removing the node_modules directory and deleting package-lock.json. It's effectively a clean install of all node dependencies that installs minor version updates to outdated packages.
