### ISSUE TITLE
Digital Object Identifier (DOI) - unique persistent ID for a dataset (metadata requirement)

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2685]
To be able publish our data on data.gov, each data set needs to have a unique persistent ID.  Notes from meeting with Jennifer in DG can be found [here ](https://doimspp-my.sharepoint.com/:w:/r/personal/walterj_mms_gov/_layouts/15/doc.aspx?sourcedoc=%7Ba2895238-185e-4ba5-a017-f336d315d386%7D&action=edit&CID=3b097490-c7ae-1d0e-384b-e1b577fcfcc5)

Digital Object Identifiers (DOI) - unique persistent ID for a dataset. 

Example (publication asset):  

DOI = https://doi.org/10.3133/tm11B2 

Resource URL = https://pubs.er.usgs.gov/publication/tm11B2 

(resolveable DOI, meaning when the DOI is entered into a browser a valid URL is returned where the end-user can access the resource) 

What is ODDD currently doing? 

Options to meet this requirement: 

USGS-USFWS-NPS DOI Consortium (paid subscription) for DataCite and CrossRef 

Discussion DataCite or CrossRef: https://support.datacite.org/docs/datacite-or-crossref 

DOE OSTI DOI Consortium (paid subscription)  

Others – requires research to evaluate (includes, but is not limited to: DOI EDI, EDG, existing ONRR IDs, create our own, etc.)

**Comment by eelzi-ONRR** [comment]
@lpgoldstein I don't think we need this anymore?
