### ISSUE TITLE
Discuss data.json and harvest endpoint (metadata requirements for data.gov)

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2686]
We need to let Jennifer know when to set up a meeting with a contractor from Get Image Matters and ODDD to discuss requirements to publish our datasets on data.gov.  Below are the options  available and we'd like to pursue the JSON file option. 

Metadata must conform to the DOI EDI Metadata Standard. (Note the DOI EDI Standard is a profile of DCAT-US 1.1 (Data.gov), DCAT AP 1.1 (European Union), and DCAT 2.0). 

Metadata can be manually entered, directly, into EDI, OR  

Metadata can be structured as a JSON file (data.json file), which is made available to DOI EDI through a JSON endpoint for automatic harvest into EDI.

**Comment by lpgoldstein** [comment]
Done
