### ISSUE TITLE
Respond to Herocrat questions

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#2687]

**Comment by cthomasONRR** [comment]
@Maroyafaied This is ready for your review: https://doimspp-my.sharepoint.com/:w:/r/personal/thomasc_mms_gov/Documents/Documents/Herocrat%20Profile.docx?d=w8129ce07ff604e8f8e4d3ceebf8f9c50&csf=1&web=1&e=Xw4jyN

This profile's questions are definitely more work-oriented and less of a personal profile.

**Comment by Maroyafaied** [comment]
@cthomasONRR I thought all your answers were great and a very good summary. I made one small edit and commented with an idea for the last question

**Comment by cthomasONRR** [comment]
@Maroyafaied I incorporated your edits and added to the last question. Please let me know if you're ok with me sending it to Ethics. Thanks!

**Comment by Maroyafaied** [comment]
@cthomasONRR Looks great, please go ahead and send it to Ethics.

**Comment by cthomasONRR** [comment]
I sent my responses to Ethics. I'll close this issue now, and open another if I need to make any modifications.
