### ISSUE TITLE
Learn about publishing effective royalty rate recommendation 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2692]

**Comment by cthomasONRR** [comment]
Here are my notes based off reading the draft report. I provided some background in the ONRR rulemakings, which are not mentioned in the OIG report, but do change offshore deductions from October 2020 onward. My main question/suggestion is at the end.

I'm happy to talk through any of this as well :)

	• Royalty payment = (Volume sold × Sales price × Royalty rate) ─ Deductions
	• History of offshore/deepwater deductions:
		○ Deductions were part of Bush-era rulemakings when deepwater drilling was a new (and much more expensive) innovation. (1988, 2000, and 2004 rulemakings.)
		○ Part of the "2016 Valuation Rule" aimed to remove some of these deepwater provisions, as they were outdated.
		○ Part of the "2020 Valuation Rule" tried to put these deductions back in place. Nothing new in this rulemaking, just trying to re-implement the original deductions. This rule focused on bringing back certain parts of the transportation allowance (gathering costs), and allowance limits (extraordinary processing allowance).
		○ Not discussed in the OIG Report: Previous Request to Exceed Allowance Limits. Research done by me in 2020, for years 2010-2019. For transportation and processing, for onshore and offshore. 45 requests total. 31 approved. Of those 31, 19 were for processing.
	• This is why the valuation regulations page showing what commodity is under what regulation is so important (https://www.onrr.gov/references/valuation?tabs=valuation-regulations)
		○ Indian Oil is the 2015 Rule
		○ Indian Gas is the 2000 Rule
		○ Coal is back to the 1989 Rule
	• Federal Oil and Gas are under the 2016 Rule
		○ This rule has been implemented since October 2020. 
		○ The OIG report was for information from January 2016-December 2020.
		○ Most of the OIG report was done when industry was reporting under the older regulations.
		○ The December 2020 example should have been reporting under the 2016 Rule, but since it had recently been implemented, not sure how well it was done. 
	• QUESTION: 
		○ We define Offshore as: Submerged lands located farther than three miles off a state’s coastline, or three marine leagues into the Gulf of Mexico off of Texas and Western Florida
		○ We define OCS as: All submerged lands within the jurisdiction and control of the United States Government as defined in section 2 of the Outer Continental Shelf Lands Act (43 U.S.C. 1331(a)).
		○ OIG Report: The OCS is the area between State jurisdiction to 200 nautical miles from shore. State jurisdiction over the seafloor extends from the shoreline out to 3 nautical miles, except for in Texas and the Florida Gulf Coast, where it extends to 9 nautical miles
		○ Should we revise how we have this worded in NRRD?
	• The implied royalty rate is derived by dividing the royalty value by the sales value without considering deductions.
	• The effective royalty rate accounts for royalty relief, deductions, and other adjustments before the royalty value is divided by the sales value.
	• QUESTION:
		○ We know - and data is readily available for - total deductions.
		○ Why can't we publish total deductions, instead of messing with royalty rate definition?
		○ Show ALL components of the royalty payment calculation, each as their own excel column. THEN you can show "effective royalty rate" as a resulting calculation.
		○ I think focus on the royalty rate terminology is distracting from the fact that the REAL issue is the amount of deductions/allowances and other relief being applied.

**Comment by cthomasONRR** [comment]
Here are my notes on the ASLM response to the OIG Report:

ASLM Comments to OIG Report:
	• Overall, I agree with these comments.
	• Her second point about the OCS Deepwater Royalty Relief Act is especially on point.
	• I believe this is less about actually calculating effective royalty relief, and mainly about being more transparent about the deductions/allowances/relief that companies are utilizing.
	• It's important to note that most companies are legally taking these deductions, as per our regulations.
	• If OIG wants to decrease the amount of deductions, it had to be done via rulemaking. 
	• The implementation of the 2016 Valuation Rule attempts to correct some of this in the deepwater, but I do personally believe ONRR could write stricter rules for this purpose.
	• I agree that publishing more transparent data is necessary.
I believe that publishing deductions broken down by type would be way more transparent that just publishing an effective royalty rate.

**Comment by eelzi-ONRR** [comment]
I finished reviewing the documents - I don't have questions or comments like Christine did since this is fairly new to me. However, I do feel like I have a much better understanding now of what the effective royalty rate is and why they want it published.

**Comment by lpgoldstein** [comment]
@cthomasONRR I really appreciate your notes and comments! Thank you. Also finished reviewing.
