### ISSUE TITLE
Query Data - Federal Revenue by Company - Revenue Type list

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#2702]
In Query Data - Federal Revenue by Company - Revenue Type list, there are 2 instances of "AML Fees including Audits and Late Charges". We need to figure out why there are 2 instances and make sure there is only 1 present.

Note: in the downloaded Excel, there is only 1 instance labeled "OSMRE - AML Fees including Audits and Late Charges"

![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/b7fd629c-ccde-4c11-8a88-6e947a6e845b)

**Comment by greensomes** [comment]
Fixed with Liquibase anonymous changelog to update `revenue_type` by applying `TRIM` function to all instances. See [branch preview site](https://nrrd-preview.app.cloud.gov/sites/2702-revenue-type-list).
