### ISSUE TITLE
Query Data - Federal Revenue by Company - Commodity list

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#2703]
In Query Data - Federal Revenue by Company - Commodity list, there is a commodity listed as "Mlrs mining claims". This isn't listed in the data dictionary (https://revenuedata.doi.gov/downloads/federal-revenue-by-company/). It's only associated with "BLM - Permit Fees" for the year 2022. I need to follow up with DORC to see if this commodity type is correct, and if so, add it to the data dictionary

![image.png](https://images.zenhubusercontent.com/60f9807ebc2bf779cc3921f2/57d482cf-cfd6-4f91-949d-69eb612365a9)

**Comment by cthomasONRR** [comment]
Email sent today, to Donna and Andrew, with Nick cc'ed.

**Comment by cthomasONRR** [comment]
@Maroyafaied What do you think of this definition? I'm planning to send it to the BLM contact for approval.

MLRS Mining Claims: The Bureau of Land Management (BLM) maintains the [Mineral and Land Records System (MLRS)](https://www.blm.gov/services/land-records/mlrs), which is an online platform containing mineral and land records transactions. Mining claim information from MLRS contains revenue data (permit fees) from companies mining on BLM lands.

**Comment by Maroyafaied** [comment]
@cthomasONRR sorry I missed this somehow. I think your definition is fine but I still wonder what the commodity is since it's listed under that column. Hopefully BLM can clarify.

**Comment by cthomasONRR** [comment]
I got the definition approved by the BLM contact and have the updates in PR #2735. Closing this issue.
