### ISSUE TITLE
Make sure DAP code is implemented correctly for all sites

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#2712]
From Jack  at DAP:

> I'm not exactly sure how DAP is being implemented on onrr.gov -- I would recommend reaching out to your whomever is the web administrator for this site, and ask them to repeat the process for the other sites. You can find additional implementation details in the Quick Guide at our DAP Github Repo.

https://github.com/digital-analytics-program/gov-wide-code/blob/master/documentation/GSA%20DAP%204.1%20-%20Quick%20Guide.pdf

**Comment by greensomes** [comment]
The DAP script is not included in onrr.gov. I'm working on adding this now.

**Comment by greensomes** [comment]
The agency has been set to DOI and sub-agency to ONRR for the blog, NRRD, and ONRR.gov. The blog and NRRD were missing the async and type attributes in the script tag initially, but this was corrected. We've validated that all three sites are showing analytics in the DAP dashboard.
