### ISSUE TITLE
DOI logo in footer needs better alt text

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#2727]
The alt text needs include that it's a logo

**Comment by eelzi-ONRR** [comment]
Looking into this this - all the logos on the About page also need better alt text. I'll do those as well.

**Comment by Maroyafaied** [comment]
@eelzi-ONRR , Christine already opened a PR #2850 to implement other Trusted Tester fixes so you can add the alt text in that same PR.
