### ISSUE TITLE
2023 Ally Engagement and Enrichment Week (doi.gov)

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2730]
To register for the course, go to:  2023 Ally Engagement and Enrichment Week (doi.gov)

 https://doitalent.ibc.doi.gov/enrol/index.php?id=22043

**Comment by cthomasONRR** [comment]
Here's the sharepoint site link, they should be posting the meeting recordings here. https://doimspp.sharepoint.com/sites/doi-AEEW
