### ISSUE TITLE
Review new Research and Accessibility Wikis

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#2751]

**Comment by eelzi-ONRR** [comment]
Accessibility Wiki: https://github.com/DOI-ONRR/nrrd/wiki/Accessibility

Research Wiki: https://github.com/DOI-ONRR/research/wiki

The User Research & Design pages are still up on the [NRRD wiki ](https://github.com/DOI-ONRR/nrrd/wiki)is you want to compare. We want to remove them after the new research wiki is approved: 
User centered design process
Research norms and processes
Design Standards
Usability testing process
User research participant guide
User research agreement
Observing user research
Design and research in the federal government
Shaping process

**Comment by Maroyafaied** [comment]
@lpgoldstein @eelzi-ONRR I reviewed and found one minor spelling error but would like to take another look since it's a lot of content. Also, I think we should have this content in the NRRD and ONRR wiki as well rather than only in the research wiki since a lot of times people outside of our team refer to this information and I'm not sure if they'd know to look for it in the research wiki. 


![image.png](https://images.zenhubusercontent.com/5c58acad07cc4d6f39e54f67/b11e1286-cea4-4b14-aa08-69e49416178e)

**Comment by cthomasONRR** [comment]
@lpgoldstein @eelzi-ONRR 

For the Accessibility wiki:
- Maybe add a table of contents at the beginning so people can easily jump to the topic of their interest.
- This is located in the NRRD wiki, but also link to it within the ONRR wiki. Maybe somewhere in the Design Resources section (maybe a link just in the right-hand menu)

For the Research wiki:
- I agree with Maroya about having this at least linked somewhere in the ONRR and NRRD wikis
- Some of this material seems repeated from other design/research sections in the ONRR and NRRD wikis. I'd just make sure there's no redundance so we're not having to update multiple pages if/when we want to change something.
- Missing a period in this section: https://github.com/DOI-ONRR/research/wiki/Doing-design-and-research-in-the-federal-government
![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/bd8e1437-247d-4364-8eb1-70c9ad1937e3)
- Missing periods in the user research agreement section:
![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/492b9b94-06dd-484a-be73-c2bc016389e6)
![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/c66a3b3e-19a0-4fd3-8cca-73d27eedab97)

**Comment by eelzi-ONRR** [comment]
Adding Alex and moving to next spring so she has time to review

**Comment by AlexandracmONRR** [comment]
@lpgoldstein and @eelzi-ONRR 

For the Accessibility Wiki, I found just 2 things:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamRkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4dc157e6ac58ddadce9ec027ca8d7539ff7165de/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalZkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d7bb34ba6e1c5735c549fc9d25b2447f2272a39e/image.png)


Do you want to mention the Microsoft Word language level tool? I don't know if it is necessary, but it could be helpful to readers.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalpkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8cc74cd20abd8a7e276024487d434724326cec27/image.png)

**Comment by AlexandracmONRR** [comment]
For the Research Wiki, I don't have any edits/comments.

**Comment by lpgoldstein** [comment]
Incorporated all edits, added TOC to accessibility wiki, linked both wikis in all repos. Will remove other redundant research content next sprint.
