### ISSUE TITLE
Explore conferences & trainings for FY 24

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2762]
I'd like for everyone to look into conferences and trainings they would be interested in for FY 24 and to let me know. This will help me plan and justify the team's budget request.  I understand that most conferences are not yet planned for next year but we can estimate cost based on previous years.

**Comment by AlexandracmONRR** [comment]
My training and conference ideas can be found [here](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Admin/Training/FY24-Training/McNally-FY24%20Planning%20-%20Training%20and%20Conferences.docx?d=w43f05866bc3f4e3e9efd7e458e7d411c&csf=1&web=1&e=Agdzse)

**Comment by eelzi-ONRR** [comment]
I'll just put mine here - maybe we can put them all in a shared doc?

Accessibility + Design Summit - Nov 14-17 2023, all virtual, $495 one day, $745 2 day, $995 3-day, 1195 4-day https://creativepro.com/design-accessibility-summit/
UXPA - July 8-11, 2024 in person (Fort Lauderdale), $2925 w/ govt dicount, $1571 one day w/ govt discount https://uxpa2024.org/
IA Conference - no 2024 announced yet. https://www.theiaconference.com/, for 2023 - $1,100. 
Wey Wey Web - Nov 23-24, 2023, $137, I just want to go to Spain https://www.weyweyweb.com/

GA4 Complete Course $225 https://www.lovesdata.com/courses/google-analytics-4
Project Management for UX/UI Design - Design Master Class - udemy, $64.99, https://www.udemy.com/course/project-management-for-uxui-design-design-master-class/
Axure 10 Core Skills - Rapid CX and UX Prototyping - udemy, $19.99, https://www.udemy.com/course/axure-10-core-skills-rapid-cx-and-ux-prototyping/

**Comment by Maroyafaied** [comment]
@eelzi-ONRR lol I'm going to Wey Wey Web with you!
