### ISSUE TITLE
Plan Design Studio - Effective Royalty Rate

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2766]
We've received the data set and can start planning for design studio sessions. Here's a link to[ the wiki explaining](https://github.com/DOI-ONRR/nrrd/wiki/Shaping-Process#whats-working-for-us) how we've done the shaping process in the past and here's the [link to the data](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/NRRD/Data/Sales%20Data/Data/CY13-CY22%20Federal%20Effective%20Rates%20as%20of%208-16-2023.xlsx?d=w001fa77bfe9341148061e42c80e427d6&csf=1&web=1&e=SJzZhE).

**Comment by AlexandracmONRR** [comment]
[Some notes](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/NRRD/Data/Sales%20Data/Project%20plan/NRRD-SalesData-DesignStudio.docx?d=w76f3ee4473824d1f8fd9cc12ae1b8a22&csf=1&web=1&e=yJeanr) related to our (Erin and Alex) discussion yesterday.
