### ISSUE TITLE
Review sales data and document any questions

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2772]
The dataset is [located here](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/NRRD/Data/Sales%20Data/Data/CY13-CY22%20Federal%20Effective%20Rates%20as%20of%208-16-2023%20.xlsx?d=w0e69c1f653e0475496148ccd964ad763&csf=1&web=1&e=rxehPc) and I started [a note doc with questions.](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/NRRD/Data/Sales%20Data/Data/Notes%20on%20data.docx?d=we13c41eedde346f3a0bdf923edd3304d&csf=1&web=1&e=IRsTtLl) Feel free to add to it

**Comment by cthomasONRR** [comment]
@Maroyafaied I added my comments/questions/concerns to your notes doc.
