### ISSUE TITLE
Add data publication section for production by year download page

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2779]
DORC requested we add a section in the production by year download page similar to the the production by month download page for  the “Data publication” that explains  the data is only updated once a year

**Comment by cthomasONRR** [comment]
@Maroyafaied This is super basic but I think this is all they're asking for:

"Data publication
We update both the calendar year and fiscal year datasets on an annual basis. Final production numbers aren't available for 3-4 months, so these datasets are updated 3-4 months after the end of the fiscal and calendar years."

Doc is located here if you want to edit the text: https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/NRRD/Content/FY23/Production%20by%20year-%20data%20publication%20update.docx?d=w7ad670ead52e454095c3ff8fbfe2aa13&csf=1&web=1&e=CucOFk

**Comment by cthomasONRR** [comment]
Bumping this to a 2 since I also added a new section for annual vs monthly dataset differences.
