### ISSUE TITLE
Add DORC email to NRRD footer

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#2792]
DORC would like their "onrrdatarequests@onrr.gov" email to be in the NRRD footer. The footer is in the gadsby-config.js file, and I don't think the property string language allows for 2 emails to be listed. Might need dev attention.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWRaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9da86ebc6f7154bc1a375b9d136de8f9988622e2/image.png)

**Comment by Maroyafaied** [comment]
@cthomasONRR I was able to add DORCs email, I had to add code in 3 different places.  I added "contact" as a prop in the footer.mdx file, then added "contact" to the default layout.js file, then added the information to the gatsby-config.js file.  Below is screen shots of everything so we can have documentation of how to edit the footer. 
![image](https://github.com/DOI-ONRR/nrrd/assets/40175688/5b5a6c57-cf36-4c05-8b37-03e8ce4afb1b)
![image](https://github.com/DOI-ONRR/nrrd/assets/40175688/fd10dbf7-393b-4a90-99ae-bd11b0a24928)
![image](https://github.com/DOI-ONRR/nrrd/assets/40175688/04892944-460e-4206-a6f9-0e42603e0825)
![image](https://github.com/DOI-ONRR/nrrd/assets/40175688/b646a952-2db5-4c81-a685-9f1c979cdd38)

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks so much!! I will let DORC know, and show them the preivew!
