### ISSUE TITLE
Compare monthly August GA360 analytics to GA4 results

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#2794]
For all 3 repos.

**Comment by cthomasONRR** [comment]
- I created a word doc to compile comparison screengrabs of GA360 and GA4. 
- I update my excel and added questions
- I contacted Jack Avery/DAP to set up another meeting for next sprint.

**Comment by Maroyafaied** [comment]
@cthomasONRR moving this to next sprint but feel free to close if you're done comparing.
