### ISSUE TITLE
Outline for IAAF presentation

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#2799]

**Comment by Maroyafaied** [comment]
@lpgoldstein Here's a draft of an outline, I added to the top of the document. Feel free to make changes! https://doimspp.sharepoint.com/:w:/s/NRRD/ETce15kyxLpAqhLBJLuXU6YB5ZL_EWSBh1LpZW-nQTljAQ?email=Maroya.Faied%40onrr.gov&e=4%3Avy54IF&fromShare=true&CID=8cd6cfea-cd41-9fa8-b2fd-7669787f2cde

**Comment by lpgoldstein** [comment]
@Maroyafaied I left a comment in the document but I think we can close this issue and I'll open one for the slide deck. I can do the the first draft of slides this sprint.

**Comment by Maroyafaied** [comment]
sounds good
