### ISSUE TITLE
Review FY24 goals and provide input

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2831]
Please familiarize yourself with the FY24 goals and provide any input you may have. Thanks

https://doimspp.sharepoint.com/❌/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7B2FBE43D3-8EF5-4CDC-A8B4-F80B96CD3866%7D&file=FY%2024%20Goals.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1&login_hint=faiedm%40mms.gov&ct=1695124689089&wdOrigin=OFFICECOM-WEB.START.EDGEWORTH&cid=a6874b63-0ea2-40da-a9e9-f46948b7dc14&wdPreviousSessionSrc=HarmonyWeb&wdPreviousSession=e1d93b53-e0bd-43ad-8487-977597259194

**Comment by cthomasONRR** [comment]
@Maroyafaied The link in this issue isn't working for me. Could you try to resend it? It' super annoying that the links get formatted with this emoji and prevents them from working properly 
![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/bcf9098c-f66f-43c2-af6a-5d2f9e2dbd87)

**Comment by Maroyafaied** [comment]
@cthomasONRR [Here it is ](https://doimspp.sharepoint.com/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7B2FBE43D3-8EF5-4CDC-A8B4-F80B96CD3866%7D&file=FY+24+Goals.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1&login_hint=faiedm%40mms.gov&ct=1695650057930&wdOrigin=OFFICECOM-WEB.START.EDGEWORTH&cid=e5783003-5170-46a9-b112-97fb4090eb20&wdPreviousSessionSrc=HarmonyWeb&wdPreviousSession=e1d93b53-e0bd-43ad-8487-977597259194)

**Comment by cthomasONRR** [comment]
I reviewed and added a few comments.

**Comment by Maroyafaied** [comment]
@cthomasONRR Thanks for reviewing, I responded to your comments and made adjustments.

**Comment by eelzi-ONRR** [comment]
@Maroyafaied I reviewed and just added one question

**Comment by AlexandracmONRR** [comment]
@Maroyafaied - I also reviewed and just left one comment.

**Comment by Maroyafaied** [comment]
@eelzi-ONRR @AlexandracmONRR Thanks, I responded to your comments and made adjustments.

**Comment by AlexandracmONRR** [comment]
@Maroyafaied - thanks, I have no more questions/feedback.

**Comment by greensomes** [comment]
I added a few comments and an item to onrr.gov goals.

**Comment by Maroyafaied** [comment]
@greensomes Thanks, I implemented your comments.
