### ISSUE TITLE
Develop feedback form for Design Studio 2 prototypes

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/nrrd#2835]

**Comment by AlexandracmONRR** [comment]
@eelzi-ONRR - i'm assigning you since you're reviewing and editing.

**Comment by eelzi-ONRR** [comment]
I just now finished with it so I'll wait until tomorrow morning to send to everyone. 

I made the following changes: 

- Consolidated cards and map group in both the survey and the spreadsheet
- Fixed minor typos
- Combined 2 of the prototypes into 1 in photoshop (one was presented as a detail of the other)
- Added reminder about the data download content feedback to the Thank You message after it's submitted
- Added more info about how the survey works to the intro
- Set a end date of EOD on 9/29 (and added a note about that to the intro)
- Removed the ranking from the content section and added more clarity on how to give feedback on that section

**Comment by eelzi-ONRR** [comment]
Sent to participants on 9/21
