### ISSUE TITLE
Submit UXPA proposal

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/nrrd#2836]
Due September 24

**Comment by AlexandracmONRR** [comment]
Hi @Maroyafaied - please see the [UXPA proposal here](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Outreach/Proposals%20%26%20Presentations/FY24/UXPA%20July%202024/[UXPA-July2024-Proposal.docx](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Outreach/Proposals%20%26%20Presentations/FY24/UXPA%20July%202024/UXPA-July2024-Proposal.docx?d=w138ab9511776480e94450edf9e8898a9&csf=1&web=1&e=4GobJx)?d=w138ab9511776480e94450edf9e8898a9&csf=1&web=1&e=4GobJx) (which pulls a lot from the Interaction 24 proposal). All comments and edits are welcome - thank you!

**Comment by Maroyafaied** [comment]
@AlexandracmONRR I get this error with the link 
![image](https://github.com/DOI-ONRR/nrrd/assets/40175688/6f3c2384-003d-4994-a471-02eaa2f276c9)

**Comment by AlexandracmONRR** [comment]
Does [this link](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Outreach/Proposals%20%26%20Presentations/FY24/UXPA%20July%202024/[UXPA-July2024-Proposal.docx](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Outreach/Proposals%20%26%20Presentations/FY24/UXPA%20July%202024/UXPA-July2024-Proposal.docx?d=w138ab9511776480e94450edf9e8898a9&csf=1&web=1&e=g5BU9U)?d=w138ab9511776480e94450edf9e8898a9&csf=1&web=1&e=g5BU9U) work?

**Comment by AlexandracmONRR** [comment]
@Maroyafaied Here is the link to the folder:
https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/Outreach/Proposals%20%26%20Presentations/FY24/UXPA%20July%202024?csf=1&web=1&e=kq4M5v

**Comment by Maroyafaied** [comment]
@AlexandracmONRR Good job! I made a couple minor comments. Thanks

**Comment by AlexandracmONRR** [comment]
@Maroyafaied - thank you! Proposal was submitted.
