### ISSUE TITLE
Finish IAAF slides

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#2842]

**Comment by AlexandracmONRR** [comment]
@eelzi-ONRR - I've added the presentation content that we discussed in our meeting today. Let me know if you have any comments/edits and I will get to them tomorrow morning.

**Comment by eelzi-ONRR** [comment]
@AlexandracmONRR I worked on it this afternoon - I think everything is done except for slides 30 and 31.

**Comment by eelzi-ONRR** [comment]
@lpgoldstein or @Maroyafaied do either of you have time to review before we submit tomorrow? I'd happily review yours in exchange!

https://doimspp.sharepoint.com/:p:/r/sites/NRRD/Shared%20Documents/General/Outreach/Proposals%20%26%20Presentations/FY24/IAAF%20FY24/Testing%20methods%20and%20testing%20management%20%20presentation/IAAF%202023%20Testing.pptx?d=wdcc092a4750c46c7b8ab9456dbe0dd70&csf=1&web=1&e=hV8hdC

**Comment by lpgoldstein** [comment]
@eelzi-ONRR I can take a look!

**Comment by Maroyafaied** [comment]
@eelzi-ONRR This is GREAT, it's super informative and I learned a lot. I love the idea of sharing a word doc with everyone to add to. I left a few minor comments but super impressive presentation overall! And feel free to review our presentation if you have time.

**Comment by lpgoldstein** [comment]
@eelzi-ONRR Thanks for letting me read! I learned a lot. No mistakes and I left a comment in there.

**Comment by eelzi-ONRR** [comment]
@Maroyafaied @lpgoldstein Thank you both so much for reviewing! I've incorporated your changes

**Comment by eelzi-ONRR** [comment]
Slides have been submitted
