### ISSUE TITLE
Refactor monthly production data update process

### ISSUE THREAD

**Issue by greensomes** [DOI-ONRR/nrrd#2852]

**Comment by greensomes** [comment]
The monthly production process consists of the following:

- Load CSV into monthly_production_etl
- Sanitize commodity (change "ton" to "tons" for Coal)
- Remove empty rows
- Format negative volume values
- Populate location table
- Populate commodity table
- Populate period table
- Load production table from monthly_production_etl

**Comment by Maroyafaied** [comment]
@greensomes for CY and FY production , the raw dataset that DORC gives us has **Land Class in column B** and **Land Category in Column C** , when we upload the file we have to switch these columns and put **Land Class in column C** and **Land Category in Column B**. If we don't switch the order of the columns, the database freaks out.  The last note to add to the confusion is that after we switch the columns while uploading, the database will generate a download with the columns ordered the way DORC gave it to us originally ( Land class in B and Land Category in C). Let me know how confused I made you from 1 to 10 lol

**Comment by greensomes** [comment]
I would say confusion level is 1. Lol. I'm not concerned about the ordering on the upload since the changeset config YAML specifies the CSV to database table column mapping, making the ordering irrelevant. Yay!

**Comment by greensomes** [comment]
I realized that the production features on the web site rely on materialized views. The load change log for monthly production has been amended to include the refresh of the following materialized views:

- _mview_commodity_qtp
- _mview_location_commodity_qtp
- _mview_location_qtp
- query_tool_production
- total_production_summary
