### ISSUE TITLE
Finish IAAF presentation

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#2856]

**Comment by Maroyafaied** [comment]
https://doimspp.sharepoint.com/:p:/r/sites/NRRD/Shared%20Documents/General/Outreach/Proposals%20%26%20Presentations/FY24/IAAF%20FY24/Inclusive%20culture%20presentation/IAAF%202023%20Presentation%20-ONRR%20inclusive%20culture.pptx?d=wc7354d2ebbcd4db3ba1596828e07548e&csf=1&web=1&e=2fwOeX

**Comment by lpgoldstein** [comment]
@eelzi-ONRR ready for review: https://doimspp.sharepoint.com/:p:/s/NRRD/ES5NNcfNu7NNuhWWgo4HVI4B1nnk61xeUP4jcQFyRvbuIA?email=Erin.Elzi%40onrr.gov&e=5f1cve

**Comment by eelzi-ONRR** [comment]
@lpgoldstein @Maroyafaied This is great! I made a few minor comments but I also think it's good as is!
