### ISSUE TITLE
NRRD FY 23 analytics

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#2867]
Pull FY23 analytics, and also update the analytics archive by moving FY22 monthly data there.

**Comment by cthomasONRR** [comment]
@lpgoldstein 
Do you have time to review?
https://github.com/DOI-ONRR/nrrd/wiki/Analytics

Check doc here: 
[NRRD_FY23_ALL.xlsx](https://github.com/DOI-ONRR/nrrd/files/12819575/NRRD_FY23_ALL.xlsx)

Let me know if you have any questions

**Comment by lpgoldstein** [comment]
@cthomasONRR looks good!
