### ISSUE TITLE
Performance/Metrics visuals for FY23

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2868]
Nathan asked if we have any graphs or visuals to show our team's performance for FY23 that he can present to upper management.  We can look at overall pageview analytics or specific webpage analytics to see if anything stands out from last year. I also thought of showing accessibility scores improving for certain webpages that we enhanced. Any ideas are welcome! And this doesn't have to be completed this sprint.

**Comment by cthomasONRR** [comment]
@Maroyafaied I should have FY23 analytics tomorrow- I requested the unsampled reports today and due to the token issue I should receive them tomorrow.

**Comment by Maroyafaied** [comment]
@cthomasONRR ok sounds good, thanks!

**Comment by lpgoldstein** [comment]
@Maroyafaied I'll have metrics for at least NRRD tomorrow.

**Comment by lpgoldstein** [comment]
@Maroyafaied We completed around 70 accessibility issues this year! [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHNTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3face4466354bf7b0fded8e3283b6c982654286b/image.png)

**Comment by cthomasONRR** [comment]
@Maroyafaied Here are the FY23 analytics Excels for NRRD and ONRR. For pageviews, sessions, and users, I pulled in the data from the monthly spreadsheet to show some FY22 vs FY23 comparisons. For all other metrics, I visualized the top 10 results.

[NRRD_FY23_ALL.xlsx](https://github.com/DOI-ONRR/nrrd/files/12833056/NRRD_FY23_ALL.xlsx)

[ONRR_FY23_ALL.xlsx](https://github.com/DOI-ONRR/nrrd/files/12833061/ONRR_FY23_ALL.xlsx)

**Comment by Maroyafaied** [comment]
@cthomasONRR this is great, thanks for putting these graphs together. I'll def be using the pageviews comparison charts
 for both websites.

**Comment by Maroyafaied** [comment]
I'm adding @eelzi-ONRR [outreach and pageview comparison sheet](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7B5B9C2CB8-00C6-47F8-858E-E3FEDE244811%7D&file=Analytics%20and%20outreach.xlsx&action=default&mobileredirect=true) to this issue, I added a tab with @cthomasONRR charts for pageview FY 22 & FY 23 comparison to Erin's spreadsheet.

**Comment by Maroyafaied** [comment]
I started this template for FY 23, it's very basic but I made an issue to create templates for the future. Since we're on a short deadline , I'll schedule a meeting for tomorrow to get this sheet filled up. https://doimspp.sharepoint.com/:b:/r/sites/NRRD/Shared%20Documents/General/Admin/Goals%20%26%20Accomplishments/FY%2023/FY%2023%20accomplishments.pdf?csf=1&web=1&e=HeXfTJ

**Comment by Maroyafaied** [comment]
Sent the ppt and snapshot to Nathan. 

https://doimspp.sharepoint.com/:b:/r/sites/NRRD/Shared%20Documents/General/Admin/Goals%20%26%20Accomplishments/FY%2023/ODDD-Accomplishments-Factsheet.pdf?csf=1&web=1&e=upD6sT

https://doimspp.sharepoint.com/:p:/r/sites/NRRD/Shared%20Documents/General/Admin/Goals%20%26%20Accomplishments/FY%2023/content%20for%20FY23%20sheet%20.pptx?d=w16223c3d3b664db1a6c84256052b1541&csf=1&web=1&e=KdwRwr
