### ISSUE TITLE
Demo the new uploading data process 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2871]

**Comment by cthomasONRR** [comment]
Monthly production upload process:

- Open monthly Prd file
- Save as .csv file
- Replace "monthly_production.csv" file
- VSCode: database > changelog > changelog-data > production_monthly.yaml
    - 1 ID to update, very top. "production-monthly-YY-MONTH"
    - 1 author to update, very top.
- Commit
