### ISSUE TITLE
Login to cloud.gov using PIV

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2899]
Jeff and I successfully logged in so please try logging in using these instructions. 

If you are getting an error when you login using SAML (onrr's logo) then you need to clear browsing data in Chrome by following these instructions:

1. Click the Tools menu (three dotted lines in the upper-right corner).
2. Select Clear Browsing Data
3. Set the Time Range drop down to  set to last 7 days or last 4 weeks

Then go cloud.gov login and select ONRR's logo, if it asks you for an email put your email with the "mms.gov" . For example, mine is faiedm@mms.gov.

**Comment by lpgoldstein** [comment]
I'm in! I did have to make sure that I cleared my cookies to get in.

**Comment by eelzi-ONRR** [comment]
I was able to get it to work in Chrome and Firefox, but not in Edge. That's not really important though

**Comment by AlexandracmONRR** [comment]
I was able to sign in!

**Comment by cthomasONRR** [comment]
@Maroyafaied I was able to sign in
