### ISSUE TITLE
Identify digital experience delivery lead - 21st Century IDEA

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2904]
As included in OMB M-23-22 (Delivering a Digital-First Public Experience), each agency must identify a single digital experience delivery lead. This lead will be responsible for communicating information to the relevant stakeholders across the agency, providing requested information to OMB, engaging with other agencies to share best practices for implementation, and overseeing delivery of the requirements and recommendations of this memorandum. Once designated, leads from larger agencies may work with OMB to designate secondary points of contact for agency subcomponents, but the overall lead will remain responsible for the above.
[
This form is required to be filled ](https://touchpoints.app.cloud.gov/touchpoints/37ac6817/submit)

**Comment by Maroyafaied** [comment]
@AlexandracmONRR  please fill out this form : https://digital.gov/resources/delivering-digital-first-public-experience/?utm_source=state&utm_medium=email#what-are-the-agency-reporting-requirements-2

Information on action items and due dates: https://digital.gov/resources/delivering-digital-first-public-experience/?utm_source=state&utm_medium=email#what-are-the-agency-reporting-requirements-2

**Comment by AlexandracmONRR** [comment]
Form submitted
