### ISSUE TITLE
Document any links to non-federal websites 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2908]
Links to Non-Federal Web sites
**From DOI:** 
All links and pointers to sites that are not part of the U.S. Federal Government are considered "non-Federal links". DOI and bureau Web sites will attempt to disclaim these “non-Federal” Web sites to the citizen.
In rare instances, DOI and bureau Web sites may link to Web sites that are not government-owned or government-sponsored if these Web sites provide government information and/or services in a way that is not available on an official government Web site. DOI and the bureaus provide these non-government websites as a public service only. The U.S. Government, including the Department of the Interior, neither endorses nor guarantees in any way the external organizations, services, advice, or products included in these Web site links. Furthermore, the U.S. Government neither controls nor guarantees the accuracy, relevance, timeliness, or completeness of the information contained in non-government Web site links.

**From 21st Century IDEA Act** 
Clearly label non-governmental content: Agencies should establish processes to label
or distinguish non-governmental content (e.g., third-party information or research,
user-generated content) that is disseminated on an agency website or digital service,
including links to third-party websites,
27 in a manner that minimizes the impact of such
labeling on the usability of their websites and digital services.

**Comment by eelzi-ONRR** [comment]
@cthomasONRR I found guidance from USWDS on how to meet this requirement. Their examples either contextualize the link within a sentence (eg. "source code on Github.com") or add the domain for the non-govt site at the end of the link (eg. "source code (Github.com)")

https://designsystem.digital.gov/components/link/#what-you-should-do-2

**Comment by cthomasONRR** [comment]
Completed via the ONRR content audit.
