### ISSUE TITLE
Get input on and refine sales/ERR data query prototype

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#2921]

**Comment by eelzi-ONRR** [comment]
@Maroyafaied Here's the link to the first round of prototypes: https://sx3k8u.axshare.com/

Changes we already discussed are to remove the year and revenue type filters, move the commodity filter further to the left, and change "select year" to "select calendar year"

**Comment by Maroyafaied** [comment]
I put input from Nathan in axure as comments.
