### ISSUE TITLE
Troubleshoot query tool not pulling all the funds in query tool in PR#2910

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2926]

**Comment by Maroyafaied** [comment]
@greensomes There are 3 funds missing from Oct-Dec of 2014 (Reclamation fund, State and Local Government, and U.S Treasury)

**Comment by greensomes** [comment]
This has been resolved by updating the trigger function `transform_fund_class_and_recipient_disbursement`. The change has been committed to the `fyuploads` branch.
