### ISSUE TITLE
Handbook redesign discussion 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2927]
Meeting is on Oct.31st

**Comment by cthomasONRR** [comment]
I filtered the FY23 total pageviews to get the table below. Total pageviews for interactive examples plus the Indian payor handbook. 

![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/c310714e-d4d0-4460-b0fd-7c92c3abcee4)

**Comment by cthomasONRR** [comment]
Project/notes folder located [here](https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/ONRR.gov/Content/FY24/RV%20Examples?csf=1&web=1&e=fbleEu).

**Comment by Maroyafaied** [comment]
Jodie will open an issue with the changes we discussed.
