### ISSUE TITLE
Document coal excise tax wiki manual process 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2929]

**Comment by cthomasONRR** [comment]
https://github.com/DOI-ONRR/nrrd/wiki/Releasing-changes-to-production#manual-updates-to-the-coal-excise-tax-webpage

**Comment by cthomasONRR** [comment]
@Maroyafaied This is ready for your review:
https://github.com/DOI-ONRR/nrrd/wiki/Releasing-changes-to-production#manual-updates-to-the-coal-excise-tax-webpage-to-be-done-each-fiscal-year

**Comment by cthomasONRR** [comment]
@lpgoldstein This is ready for your review:
https://github.com/DOI-ONRR/nrrd/wiki/Releasing-changes-to-production#manual-updates-to-the-coal-excise-tax-webpage-to-be-done-each-fiscal-year

**Comment by lpgoldstein** [comment]
@cthomasONRR looks good! Glad we are documenting all of these updates and not relying on memory.
