### ISSUE TITLE
Document in wiki how database changes are applied 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2930]

**Comment by greensomes** [comment]
A wiki page has been created [here](https://github.com/DOI-ONRR/nrrd/wiki/Database-change-management).

**Comment by Maroyafaied** [comment]
@greensomes This looks great, I don't have any changes. I can't follow these steps but not because of how they are written but because I have no technical skills lol. Thanks for documenting.
