### ISSUE TITLE
Finalize wiki instruction on uploading data sets 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2931]

**Comment by cthomasONRR** [comment]
@lpgoldstein I reviewed, and no additional modifications are needed for production and revenue instructions. Could you review to see if anything specific to disbursements needs to be added?
https://github.com/DOI-ONRR/nrrd/wiki/Releasing-changes-to-production#how-to-upload-monthly-datasets

**Comment by lpgoldstein** [comment]
I added one note about updating disbursements yaml for a new fiscal year but I was able to upload data using the instructions.
