### ISSUE TITLE
Review prototypes for Sales Data/ERR Calculation

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/nrrd#2939]
Hi all, please review the following prototypes:

- Prototype 1: https://42xozl.axshare.com/?id=jdcfib&p=p1_-_document_download&g=1
(loosely followed the format of How Revenue Works diagram with interactive elements)
- Prototype 2: https://42xozl.axshare.com/?id=4ft1gu&p=p3_-_document_download&g=1
(different diagram look with interactive elements)

The text within the prototypes can be found [here](https://doimspp.sharepoint.com/:w:/s/NRRD/EUR3LSseLNVNrDmKZNS-mhwBKpSD8vPeK5LMWYwvl6cPnQ?e=X29J94).

Feel free to post feedback in this issue. We can also discuss during sync up next week. Thank you!

**Comment by AlexandracmONRR** [comment]
Hi all - please note that two links bring you to the same file, but two different pages within the file: P1 and P3.

**Comment by cthomasONRR** [comment]
@AlexandracmONRR All my comments are in Axure, please let me know if you have any questions about them. Thanks!

**Comment by AlexandracmONRR** [comment]
Feedback from 10/31:

**General:**
- Terminology - use "adjustments" not "deductions"
- We should include some introductory text to ONRR 2014 reporting and potentially the ERR calculation related to the OIG rec.
- Representation of how money changes is misleading, likely better to show the equations
- Terminology - use "citation" rather than "source"
- Data tab/section is likely unnecessary - the description is sufficient
- Section with the diagram should be called "How data was developed"

**P3:** 
- The simplicity of this prototype is preferred.
- Helpful to think of it as Steps 1 through 3 are industry - actual reported values and Step 4 is a required calculation by OIG
- Should we think about assigning transaction codes as a step in this process?
- If we include ONRR 2014 Reporting as a step, this could be an open accordion. Then the 3 sub-steps below could be closed accordions.
- How do we want to include the OIG Recommendation and ERR calculation as a part of this process? Is it one step or should it be more than one?

**Other takeaways:**
- Diagram requires review by SMEs.
- Content should be shaped/edited by SMEs.
