### ISSUE TITLE
Resolve data issues for September revenue and FY 15 disbursements 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2940]
I'm posting here some issues I found in dev in both the September 2023 monthly revenue and the FY 15 disbursements. 

**Revenue**

1. Homepage yearly fiscal year commodity chart : The comparison table is blank and the total is wrong, it should be 18,118,455,254 as it shows in the query tool. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHg4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--41bf996f20285a87bc691fa1d0187816682cd69b/image.png)

2.  Download page, Query tool, and Explore Data: Fiscal year revenue should start at year 2004 not 2003

**Disbursements**

1. The "State" fund is only pulling data with the disbursement type as "Geothermal", it's not pulling the State fund with disbursement types as 8(g), GoMESA, or State. See pic of raw data vs database generated data [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemw4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--98265203af38eddd48ab666dd2d32d9a09d7a384/image.png)

2. For the "other funds" issue, it seems liked the database generated data is not displaying all the funds that have state name as blank. See pic of raw data vs database generated data where I filtered for states that are blank. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjk4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--19b4a58ccb30387dee0aff72697ca48441280b4a/image.png)

**Comment by greensomes** [comment]
After restoring the database trigger functions for populating the location and fund reference tables, it appears that the FY 2015 disbursement numbers and figures related to the September revenue load are accurate.

**Comment by cthomasONRR** [comment]
@greensomes I went to https://nrrd-preview.app.cloud.gov/sites/fyuploads/ and I'm still seeing the same issue in Revenue-FY-Commodity 

![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/87ef949f-471d-4fe7-b697-15c13df1cb11)

**Comment by greensomes** [comment]
The reason for the revenue issue on the landing page is that the materialized view refresh for `_mview_fy_commodity` was mistakenly excluded from the revenue.yaml file.
