### ISSUE TITLE
Code for America Proposal

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#2943]
Open November 3-14 

https://summit.codeforamerica.org/call-for-proposals/?utm_campaign=cfa-newsletter&utm_medium=email&_hsmi=279697999&_hsenc=p2ANqtz-_b0JYYhDFwo2ckxnlBlZ_2nI6VMo2oP0IXKzCN4Whign_0KDlASHGVefXUtSjOtkkT2GRyzx_L9qFxilSHLqgNxGSkcPWmn__QmzBjAD1ujHhdP0w&utm_content=279697528&utm_source=hs_email

Just putting Erin and I on this so that we don't lose it for next sprint. Can submit none/all

**Comment by lpgoldstein** [comment]
Submitted metrics proposal

**Comment by cthomasONRR** [comment]
Submitted plain language and content audit proposals :)

**Comment by eelzi-ONRR** [comment]
Accessibility workshop submitted and I sent Alex everything she needs to easily submit her co-presenter form tomorrow
