### ISSUE TITLE
Finalize content for Sales Data process diagram

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/nrrd#2954]
Consult with SMEs to receive feedback and finalize content for the Sales Data process diagram.

**Comment by Maroyafaied** [comment]
https://doimspp.sharepoint.com/:w:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7BE613E8DD-9ECF-40CC-8793-159D18936A61%7D&file=sales%20data%20diagram%20-%20Maroya%20content.docx&action=default&mobileredirect=true
