### ISSUE TITLE
Meet with DORC supervisor on diagram content and download page 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2961]

**Comment by AlexandracmONRR** [comment]
Helpful conversation with Nick:

- The high level explanation with option for more details is helpful
- 1st main step: a few edits to the language of the sub-steps
- 2nd main step: ONRR aggregation of data
- 3rd main step: make sure last step is clear that it is OIG's calculation: "ONRR using OIG's calculation to publish ERR"
- Preference of using icons: writing, calculate, OIG logo, etc. (don't use numbers)
- Helpful to break up steps by who the actor is
- I've noted that we can change colors to team's liking


Content edited: https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/NRRD/Design/Sales%20Data/sales%20data%20diagram%20-%20Maroya%20content.docx?d=we613e8dd9ecf40cc8793159d18936a61&csf=1&web=1&e=SXT0ry

**Comment by Maroyafaied** [comment]
@AlexandracmONRR thanks for summarizing the meeting. I'll close this issue.
