### ISSUE TITLE
Add definition to "land type" in query tool 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2977]
DORC team suggested that we explain that land type is land class and land category combined in the query tool

**Comment by cthomasONRR** [comment]
@Maroyafaied Here are the definitions I'd like to add to the Glossary. The 3 land definitions are lightly altered to be inclusive of all datasets. Onshore and offshore are the same as in the data dictionary.

- Land Category:  Distinguishes between data collected onshore and offshore within NRRD datasets.
- Land Class: Distinguishes federal lands and waters from Native American lands within NRRD datasets.
- Land Type: Combines land class and land category within NRRD's Query Data tool. 
- Onshore: Situated or occurring on land.
- Offshore: Submerged lands located farther than three miles off a state’s coastline, or three marine leagues into the Gulf of Mexico off Texas and western Florida.
