### ISSUE TITLE
Look into React.js script with DAP UA tag "UA-33523145-1"

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#2978]
Here's information from DAP. This tag could be contributing to differences in observed values between GA360(UA) and GA4, specifically for pageviews, sessions, and users. This question was for NRRD, but we might want to double check ONRR code too.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3pZQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d59b73c82f552ee058de2d6596033f223b10704a/image.png)

**Comment by Maroyafaied** [comment]
@cthomasONRR For nrrd, was pageviews, sessions, and users results  very different between GA360 and GA4 for November analytics? I know they were very different for October but want to make sure this is still an issue before @greensomes makes code changes.

**Comment by cthomasONRR** [comment]
@Maroyafaied @greensomes Yes, NRRD pageviews were still off for November. Here's the info:

![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/a2198903-1948-4ff4-be24-0aaf8794a23d)

**Comment by Maroyafaied** [comment]
@cthomasONRR when I use the explore feature in 360 like how we use it for GA4, I actually get very close results for both websites pageveiws, here's screenshots

Onrr.gov 360
![image](https://github.com/DOI-ONRR/nrrd/assets/40175688/9cb8dfb4-f6ce-4490-b55c-c4d1811f99f3)

Onrr.gov GA4
![image](https://github.com/DOI-ONRR/nrrd/assets/40175688/2fb403b2-1dda-45bd-83e3-b60a9603203a)

NRRD 360
![image](https://github.com/DOI-ONRR/nrrd/assets/40175688/b3a43605-1f65-490e-a0d7-a8d86c49b3ec)

NRRD GA4
![image](https://github.com/DOI-ONRR/nrrd/assets/40175688/510cd740-cdea-419b-a359-ffa056b0f7b7)

**Comment by cthomasONRR** [comment]
@Maroyafaied I'm not sure I'm following. We can discuss at checkin.

**Comment by Maroyafaied** [comment]
@cthomasONRR Jeff implemented DAP's recommendation and removed the UA tag from the react.js script. This went live on 12/28
