### ISSUE TITLE
Watch/Listen to Radical Participatory Design Video/Podcast

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#2982]
To prepare for discussion at the December Team meeting (12/4), watch/listen to the following: 

[A radically different approach to participatory design / Victor Udoewa / Episode #154](https://www.youtube.com/watch?v=ixeNahaPsHY)

[Victor Udoewa: Giving Up Power In Your Space](https://www.youtube.com/watch?v=ZF3y1WC49pk)

**Comment by cthomasONRR** [comment]
I watched both videos and took notes.

**Comment by AlexandracmONRR** [comment]
I listened to both and took notes. Great discussions!

**Comment by eelzi-ONRR** [comment]
@Maroyafaied @greensomes @AlexandracmONRR @cthomasONRR Lindsay and I were thinking everyone could come up with one or two talking points or questions to help direct our discussion at the team meeting next week.
