### ISSUE TITLE
Identify and add terms for sales data in Glossary

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2995]

**Comment by lpgoldstein** [comment]
@Maroyafaied Here is the [link to the proposed terms](https://doimspp.sharepoint.com/:w:/s/NRRD/EWPv4NEOJ_VAnAszq56tjDsB5Y4mJeC9_Qy4HCSHJyni2Q?email=Maroya.Faied%40onrr.gov&e=ZM7nkB). I've discussed with @cthomasONRR and asked her to review as well.

**Comment by Maroyafaied** [comment]
@lpgoldstein Thanks, I think we should be adding other terms that will be useful to have in the glossary so users can hover over in the query tool and/or explore data and get a definitions. I know all the definitions are included in the download page but having them in the glossary will allow us to use an icon to hover over and get a definition. Some terms that I think will be useful are;

Transportation allowance
Processing allowance
RVLA
RVPA
Sales Volume
Sales Value

**Comment by cthomasONRR** [comment]
@lpgoldstein I made edits to the 2 definitions. I was a little confused with the sales year definition, but I think the confusing sentence can be deleted. I'm happy to review the additional definitions that should be in the glossary for the hover feature.

**Comment by cthomasONRR** [comment]
@lpgoldstein Thanks, I reviewed and made some edits/comments

**Comment by Maroyafaied** [comment]
@lpgoldstein looks good, we can add them to the PR for the download page. Thanks!
