### ISSUE TITLE
Start looking into build process diagram in sales data download page 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#2996]

**Comment by AlexandracmONRR** [comment]
[Prototype in Axure](https://xpospr.axshare.com/?id=h7m26w)

**Comment by greensomes** [comment]
Here's the [preview site.](https://nrrd-preview.app.cloud.gov/sites/2996-process-diagram-sales-data-download-page/downloads/sales-data/)

**Comment by Maroyafaied** [comment]
@greensomes This is looks so good! Here are a few minor edits/comments.

1. This is repeated twice, please delete. 
![image](https://github.com/DOI-ONRR/nrrd/assets/40175688/213b674c-0d03-447c-88e0-f95d10b7ae56)
2.Can you make these brackets instead of parenthesis
![image](https://github.com/DOI-ONRR/nrrd/assets/40175688/3fe38844-28fb-4793-8ded-fd4281843fb1)
3. Is it possible to add a line here as the division sign rather than the division symbol. This might not be a big deal but not sure if the equation reads the same if it's written that way, I can ask an SME. 
![image](https://github.com/DOI-ONRR/nrrd/assets/40175688/ce9afc86-b5d4-4fc4-8000-51a634f99c7d)
4. This is me being greedy, but is it possible to color the outline of the circles that have the mui components the same color as the boxes like the prototype does?
![image](https://github.com/DOI-ONRR/nrrd/assets/40175688/87018113-c9e0-4862-bc0a-8245cba54ab0)

**Comment by AlexandracmONRR** [comment]
1. Is it possible to align the top of the circle with the top of the box that it is associated with? 
![image](https://github.com/DOI-ONRR/nrrd/assets/122935097/059875dd-7ee8-4342-97dc-8db2616e181e)

I tried to mock it up here in paint:
![image](https://github.com/DOI-ONRR/nrrd/assets/122935097/ec105330-60e4-4420-9254-53b2f729d784)


2. I believe there is an extra space between the initial overview paragraph and the Data Download heading. Also, I think we should delete the color after "data download" to stay consistent with how the headings look.
![image](https://github.com/DOI-ONRR/nrrd/assets/122935097/d5762a7a-fe36-4abe-83f6-7e3707d9e273)

**Comment by Maroyafaied** [comment]
@greensomes I reviewed the updates and everything is looking great!! @AlexandracmONRR Jeff implemented your feedback , you can review using this link https://nrrd-preview.app.cloud.gov/sites/federal-sales-data/downloads/sales-data
