### ISSUE TITLE
Review OCIO Memo: Budget Year 2026 Information Management and Technology High Level Planning Objectives

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3008]

**Comment by Maroyafaied** [comment]
I'd like for everyone to review the memo and add any notes/questions to the doc below. Thanks
Link to memo: https://doimspp.sharepoint.com/:b:/r/sites/NRRD/Shared%20Documents/General/Admin/Digital%20Experience/OCIO%20Memo_BY%202026%20IMT%20High%20Level%20Planning%20Objectives_Signed%2011152023.pdf?csf=1&web=1&e=iyqgLh

Link to notes: https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Admin/Digital%20Experience/OCIO%20Memo%20Notes.docx?d=w3aa015a07fed43c4a143aedaf09b18e6&csf=1&web=1&e=mqDdr4

**Comment by cthomasONRR** [comment]
I reviewed the memo and added some notes to the document.

**Comment by AlexandracmONRR** [comment]
I've left notes below Christine's.

**Comment by eelzi-ONRR** [comment]
I've added my comments to the notes document

**Comment by Maroyafaied** [comment]
Thank you all for reading and documenting your notes, I also read and replied to a couple of comments. Feel free to close this issue tomorrow during sprint review if everyone has read the memo. Thanks

**Comment by Maroyafaied** [comment]
@greensomes if you haven't reviewed yet please open an issue just for you. Thanks
