### ISSUE TITLE
Restage applications 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3015]
cf target -o doi-onrr -s dev ; cf restage --strategy rolling dev-nrrd

  cf target -o doi-onrr -s prod ; cf restage --strategy rolling nrrd

  cf target -o doi-onrr -s prod ; cf restage --strategy rolling blog-nrrd

  cf target -o doi-onrr -s dev ; cf restage --strategy rolling dev-blog-nrrd

  cf target -o doi-onrr -s prod ; cf restage --strategy rolling doi-extractives-data

  cf target -o doi-onrr -s dev ; cf restage --strategy rolling dev-onrr-frontend

  cf target -o doi-onrr -s staging ; cf restage --strategy rolling onrr-preview

  cf target -o doi-onrr -s dev ; cf restage --strategy rolling dev-onrr-cms

  cf target -o doi-onrr -s dev ; cf restage --strategy rolling preview-onrr-frontend

  cf target -o doi-onrr -s prod ; cf restage --strategy rolling prod-onrr-cms

  cf target -o doi-onrr -s prod ; cf restage --strategy rolling onrr-psql-interface

  cf target -o doi-onrr -s prod ; cf restage --strategy rolling prod-onrr-frontend

  cf target -o doi-onrr -s prod ; cf restage --strategy rolling beta-onrr-frontend

  cf target -o doi-onrr -s dev ; cf restage --strategy rolling hasura-sandbox-interface

  cf target -o doi-onrr -s prod ; cf restage --strategy rolling hasura-dev-interface

  cf target -o doi-onrr -s prod ; cf restage --strategy rolling hasura-prod-interface

  cf target -o doi-onrr -s prod ; cf restage --strategy rolling ssh-app

**Comment by greensomes** [comment]
All except `cf target -o doi-onrr -s prod ; cf restage --strategy rolling prod-onrr-cms` succeeded. Looking into the issue.

```
cf target -o doi-onrr -s prod ; cf restage --strategy rolling prod-onrr-cms
API endpoint:   https://api.fr.cloud.gov
API version:    3.151.0
user:           Jeffrey.Schwartz@onrr.gov
org:            doi-onrr
space:          prod

Restaging app prod-onrr-cms in org doi-onrr / space prod as Jeffrey.Schwartz@onrr.gov...

Staging app and tracing logs...
   Downloading nodejs_buildpack...
   Downloaded nodejs_buildpack
   Cell 7a321e7b-f026-4f31-84b2-d36912f8ed11 creating container for instance 42339ab8-42f1-490e-bd1a-d8d2a1c2d72c
   Security group rules were updated
   Cell 7a321e7b-f026-4f31-84b2-d36912f8ed11 successfully created container for instance 42339ab8-42f1-490e-bd1a-d8d2a1c2d72c
   Downloading app package...
   Downloading build artifacts cache...
   Downloaded app package (433.6K)
   Downloaded build artifacts cache (180.6M)
   -----> Nodejs Buildpack version 1.8.20
   **WARNING** buildpack version changed from 1.8.14 to 1.8.20
   -----> Bootstrapping python
   -----> Installing python 3.11.6
   Download [https://buildpacks.cloudfoundry.org/dependencies/python/python_3.11.6_linux_x64_cflinuxfs4_9aa19c6d.tgz]
   -----> Installing binaries
   engines.node (package.json): 16.x
   engines.npm (package.json): 8.x
   **ERROR** Unable to install node: no match found for 16.x in [18.18.0 18.18.2 20.8.1 20.9.0]
   Failed to compile droplet: Failed to run all supply scripts: exit status 14
   Exit status 223
   Cell 7a321e7b-f026-4f31-84b2-d36912f8ed11 stopping instance 42339ab8-42f1-490e-bd1a-d8d2a1c2d72c
   Cell 7a321e7b-f026-4f31-84b2-d36912f8ed11 destroying container for instance 42339ab8-42f1-490e-bd1a-d8d2a1c2d72c
Error staging application: BuildpackCompileFailed - App staging failed in the buildpack compile phase
FAILED
```

**Comment by greensomes** [comment]
The code fix for this was implemented a few months back. I just noticed that config.yml only pushes the CMS to dev, so I had to do it manually. The restage completed successfully. 

I've created a separate issue to update config.yml to better handle cms pushes to any environment.
