### ISSUE TITLE
Review WCAG 2.2 new features

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3021]
https://www.w3.org/TR/WCAG22/#new-features-in-wcag-2-2

**Comment by eelzi-ONRR** [comment]
I started a sheet where we can track our notes as we review these: https://doimspp-my.sharepoint.com/:x:/g/personal/elzie_mms_gov/EXZ8Obc8gDNOp4nst6ZF-9gBC35kEqsKcy_iASNiBXWZiQ?e=k4RdXf

**Comment by eelzi-ONRR** [comment]
We identified what we need to do for each site and made issues accordingly
