### ISSUE TITLE
Look at analytics to understand why the high page views for the archived site

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3034]
In FY23 https://archive.revenuedata.doi.gov/ was among the top 10 page views. We want to look at more granular analytics to see if we can figure out what people are going to this site for

**Comment by eelzi-ONRR** [comment]
Some users have reported they have the archived site bookmarked instead of the live site - that might be one reasons for high page views. But we still should figure out why they have the archived site bookmarked in the first place instead of the live site.

**Comment by eelzi-ONRR** [comment]
@Maroyafaied Here are my findings and suggestions.

Overall it's about 50-50 direct and organic traffic. Direct means the user did not use a search engine (could have bookmarked or directly entered the url or clicked on a link someone shared in email, etc.) Organic came from search engine results. 

The homepage views are almost exclusively from direct traffic and makes up a large portion of the direct traffic.

Explore state pages have heavy use and some are much higher in organic traffic (especially Alaska) than direct.

Case studies have both organic and direct traffic, with spikes for certain studies with direct (which implies someone shared a link widely or it was published somewhere, etc.) After the home, about and archive pages, case studies have the most use.

Overall download pages have an equal number of organic and direct views, although each download page differs in whether it had more direct or organic traffic.

I've put analytics exports for this in teams so we can easily track if any changes we made reduces traffic by source: https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/NRRD/Archived%20site/Analytics?csf=1&web=1&e=H8N8x9

Suggestions: 
- Consider putting case studies on the live site. 
- Remove or rename the Archive page. It refers to the site as an archive, and the dual use of the word archive might be confusing (as a means of describing the site and as a means or indicating the site is no linger updated).
- Make the banner indicating this site is archived more obvious. The light blue and small text is easy to miss. Can we make it something the user has to x-out before they can view the page/site?
- Create a sitemap.txt and robots.txt file for NRRD (issues #2642 and #2641). Use the robots file to block the archived site from being crawled. 
- Once we have sitemap and robots files, set up a Google Search Console instance for NRRD so we can see what search terms are being used that lead users to NRRD. Are they using the word "archive" in their search?

**Comment by Maroyafaied** [comment]
@eelzi-ONRR Thank you for doing a thorough research and for providing recommendations. I do think we should work on the sitemap and robot.txt issues sooner than later. here's my responses/thoughts on other recommendations

- Consider putting case studies on the live site.

They are so outdated so not sure about publishing them again but maybe we should review what info is within these case studies that we can potentially provide to users with updated information. 

-Remove or rename the Archive page. It refers to the site as an archive, and the dual use of the word archive might be confusing (as a means of describing the site and as a means or indicating the site is no longer updated).

Not sure what you mean about the "Archive page", do you mean this section in the about page? 
![image](https://github.com/DOI-ONRR/nrrd/assets/40175688/7351481c-0f94-48e3-8187-bb55a42b6414)

-Make the banner indicating this site is archived more obvious. The light blue and small text is easy to miss. Can we make it something the user has to x-out before they can view the page/site?

I agree. Let's make an issue to do this.

**Comment by eelzi-ONRR** [comment]
@Maroyafaied I made issues to redesign the warning banner to set up Google Search Console and Bing Webmaster Tools once the robots and sitemap are done.

For the Archive page, I am referring to this page: https://archive.revenuedata.doi.gov/archive/ It has a lot of page views. I think the Archive section is meant to be a warning message, but since it's the page title it feels like it's describing the site as an archive.

**Comment by Maroyafaied** [comment]
@eelzi-ONRR oh ok, I didn't even know this page existed. Let's make an issue to rename it then.

**Comment by eelzi-ONRR** [comment]
@Maroyafaied I've created all the issues now so I'll go ahead and close out this one
