### ISSUE TITLE
Team goals to program manager due 12/6

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3035]
3-5 sentences for each of these items:

- Current Team Priorities/Activities/Objectives/Purpose
- Future (3-5 year) Team Vision
- Team needs, wants, hopes, and dreams to support the vision.

**Comment by cthomasONRR** [comment]
@Maroyafaied I'm done reviewing. Looks great! I added in a few comments and typo corrections. Feel free to remove the small additions I made if you think they're unnecessary.

**Comment by Maroyafaied** [comment]
@cthomasONRR Thanks for reviewing.
