### ISSUE TITLE
Add sales data download page content to process diagram prototype 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3043]
Nathan would like to show this to upper management and would like us to add the actual content that will be in the download page  https://nrrd-preview.app.cloud.gov/sites/err-download-page/downloads/sales-data/

**Comment by AlexandracmONRR** [comment]
Updated prototype can be found here: 
https://xpospr.axshare.com/?id=h7m26w&p=final_-_document_download
