### ISSUE TITLE
Create private GA4 account and add tracking code

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3054]
Since some settings & features are turned off for the gov account, let's create our own private account using either onrrweb@onrr.gov or nrrd@onrr.gov email and add the code snippet to both onrr and nrrd.  Below is the response from DAP

"If there are GA features that you would like to implement that are not available within the DAP-managed account, you can definitely set up an account that you managed. It is possible to update the DAP code snippet so that the same analytics data that is collected by DAP is sent to your account using our parallel tracking functionality. Please let me know if you'd like more information on this"

**Comment by eelzi-ONRR** [comment]
I've created a google account for ONRRWeb@onrr.gov and put the login in the shared password doc. I'll wait to create the properties until we hear more from DAP about their parallel tracking function.

**Comment by eelzi-ONRR** [comment]
The property has been created with 3 data streams - one for each site. 

@greensomes what is the best way to share the code you need - here? Slack? Or would you rather login to analytics and get it yourself? (I can show you where it is)

It's a different tag/ID for each site.
