### ISSUE TITLE
Draft User Testing Plan for Sales Data Prototypes

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/nrrd#3061]
User Testing Plan for Sales Data, considerations:

- Timeline
- User Participant Outreach/Recruitment
- Draft Questions
- More...

**Comment by AlexandracmONRR** [comment]
@Maroyafaied - please see/review the [drafted user research plan](https://doimspp.sharepoint.com/:w:/s/NRRD/Ef55FmUU_yFKh6lFFzdouZYB-hUhs1anYsoKuHbEHQDZ0A?email=Maroya.Faied%40onrr.gov&e=zYsK5o) by Erin, Lindsay, and I.

**Comment by Maroyafaied** [comment]
@AlexandracmONRR @eelzi-ONRR  Thanks for working on this, I added a few comments/suggestions. Thanks
