### ISSUE TITLE
Implement royalty equation updates - sales data process diagram

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3067]
Nathan mentioned that April wants to see the entire royalty equation displayed in the process diagram. I'm still trying to understand exactly what the changes should be.

**Comment by Maroyafaied** [comment]
@AlexandracmONRR I made the changes requested in [this word doc](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7BE613E8DD-9ECF-40CC-8793-159D18936A61%7D&file=sales%20data%20diagram%20-%20Maroya%20content.docx&action=default&mobileredirect=true&DefaultItemOpen=1&login_hint=faiedm%40mms.gov&ct=1702990375451&wdOrigin=OFFICECOM-WEB.START.EDGEWORTH&cid=3bf601b0-849c-4478-aca2-cc9c4f46fcda&wdPreviousSessionSrc=HarmonyWeb&wdPreviousSession=effb5234-25a0-44e2-b53c-27d9d6aabbba) based on my conversation with Nathan, can you make a prototype with these changes and I'll send to Nathan for review? let me know if anything doesn't make sense. Thanks

**Comment by AlexandracmONRR** [comment]
Prototype: https://xpospr.axshare.com/?id=gger9x&g=14

**Comment by Maroyafaied** [comment]
@AlexandracmONRR thanks for making the updates, looks great.
