### ISSUE TITLE
Get feedback on final explore data sales data prototype via survey

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3069]
Send a survey to design studio participants with version 1 and 2 of the explore data prototype for the last round of feedback

**Comment by eelzi-ONRR** [comment]
@AlexandracmONRR If you can review the survey for typos that would be great! https://forms.office.com/Pages/ResponsePage.aspx?id=urWTBhhLe02TQfMvQApUlCFfsAMLcWJFqjNmBrCRTAJUOEtZSVJZR0lES1JETE4wUlBNOUEzUFpEUi4u

**Comment by AlexandracmONRR** [comment]
Acronym is misspelled.

![image](https://github.com/DOI-ONRR/nrrd/assets/122935097/d68a9e4e-9f7d-475f-9e91-575c47df0355)

**Comment by AlexandracmONRR** [comment]
For consistency, Question 1 answers should have details after colon - not in parenthesis. 
![image](https://github.com/DOI-ONRR/nrrd/assets/122935097/b3be526a-eeff-4a55-8f49-9d61305ac5c7)

**Comment by AlexandracmONRR** [comment]
This is knit picky, but change "does include" to "includes".

![image](https://github.com/DOI-ONRR/nrrd/assets/122935097/b5654119-213a-442c-b825-761f5e6ed358)

**Comment by eelzi-ONRR** [comment]
Sent survey to design studio participants on 12/18. Survey will close on 12/27
