### ISSUE TITLE
Add FY24 metrics to wiki

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3072]

**Comment by lpgoldstein** [comment]
@Maroyafaied ready for your review

**Comment by lpgoldstein** [comment]
https://github.com/DOI-ONRR/nrrd/wiki/Goals-and-metrics

**Comment by Maroyafaied** [comment]
@lpgoldstein Looks good.  I made small edits and added line breaks in the goals and what we're measuring to make it easier to read. Feel free to close this issue if you don't have any other changes.
