### ISSUE TITLE
Social media planning

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3076]
Meet and plan social media posts

**Comment by AlexandracmONRR** [comment]
Meeting on 1/10/2024.

**Comment by lpgoldstein** [comment]
https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/Outreach/Social?csf=1&web=1&e=xbbSbE

@eelzi-ONRR @cthomasONRR @Maroyafaied This is the draft social media plan if you want to take a look before tomorrow's meeting.
