### ISSUE TITLE
add data dictionary tab to sales data excel 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3077]

**Comment by Maroyafaied** [comment]
@lpgoldstein please review the data dictionary tab. Thanks https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/General/NRRD/Data/Sales%20Data/Data/Federal%20Oil%20Gas%20and%20NGL%20Commodity%20Sales%20Year%20Data%20as%20of%2011-6-2023.xlsx?web=1

**Comment by lpgoldstein** [comment]
@maroyafaied reviewed and edited. Looks good! Also reviewed and revised the Notes tab.
