### ISSUE TITLE
Redesign the archive site warning message on the archived site to be more obvious

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3079]
The existing warning message is easy to miss with the light blue color that already used on the site, the and small text. 

https://archive.revenuedata.doi.gov/

Ideas for making the warning more obvious: 

- Require users to x-out of a warning message before proceeding to the site
- Make the warning color more noticeable and the text larger

**Comment by Maroyafaied** [comment]
closing since we'll be implementing the robots.txt file.
