### ISSUE TITLE
Set up Google Search Console and Bing Webmaster Tools for NRRD

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3080]
This is to be done after we create and robots.txt and sitemap.txt files.

**Comment by Maroyafaied** [comment]
Might need to contact DOI to verify we own the site since the nrrd has a doi domain.

**Comment by eelzi-ONRR** [comment]
No need to work with DOI unless we need to do it via cloudflare. Starting with trying the HTML verification method we used for onrr.gov. Add the html file to the static folder - PR #3347. If this works then we can use the option in Bing to verify via Google Search console instead of having to upload a second file to the site

**Comment by eelzi-ONRR** [comment]
Both are set up. It takes a few days for them to scan out site so I'll make an issue for next sprint to check both for any errors it finds that we can work on
