### ISSUE TITLE
Create a plan for UX course design

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3083]
Our class is on March 20th. This issue is to develop a timeline for the next two months think about and design the course, create activities and handouts, and practice the course. We can also start thinking about an outline this sprint.

**Comment by AlexandracmONRR** [comment]
[Folder for this training development](https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/Outreach/ONRR-UX-Training?csf=1&web=1&e=e7KpIb).

**Comment by AlexandracmONRR** [comment]
**3 modules for the 4 hour course:**
1.	Intro, Accessibility, & DEIA [**Erin**]
2.	User Research Methodologies [**Alex**]
3.	Communicating Findings & Application of User Research [**Lindsay**]
