### ISSUE TITLE
Get DAP account 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3084]
@eelzi-ONRR please add the link to the form for Jeff to create an account.

**Comment by eelzi-ONRR** [comment]
@greensomes Here's the info you need. You'll set up a google account with your onrr.gpv email, then email DAP and they will send you the form to complete. https://digital.gov/guides/dap/gaining-access-to-dap-data/

**Comment by greensomes** [comment]
I've created my google account and completed the DAP registration form. Just awaiting admin approval from DeRon Johnson.
