### ISSUE TITLE
Plan for Sales Data presence on NRRD homepage

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/nrrd#3085]
Brainstorm sales data presence on NRRD homepage during sync up on 1/2/2024. Then, consider who should be on this issue and when we can meet about adding/designing sales data presence on homepage.

**Comment by Maroyafaied** [comment]
We decided that we would have two headings in the "What's new" box. One heading will be "What's new" with a mui icon and links for sales data underneath it. Then we would like to add a line between the next heading which will be "Latest Release" with the links of the latest data underneath it. We need to make issues for the next steps.

**Comment by AlexandracmONRR** [comment]
Erin is prototyping the change in the "What's new" box.
