### ISSUE TITLE
Q1 Metrics - Accessibility

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3091]
[Document Q1 metrics (oct-dec)](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7B2FBE43D3-8EF5-4CDC-A8B4-F80B96CD3866%7D&file=FY%2024%20Goals.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1&login_hint=faiedm%40mms.gov&ct=1703716001929&wdOrigin=OFFICECOM-WEB.START.EDGEWORTH&cid=4102c5e7-4a81-44ef-a856-0f41c80ca1a9&wdPreviousSessionSrc=HarmonyWeb&wdPreviousSession=e0c5c814-0baf-42a1-bb6d-8ee21f2e4427) 

- [x] Any accessibility testing? (method, score, webpage)
- [x] # of issue identified/recommendation from accessibility testing
- [x]  # of issues resolved from accessibility testing
- [x] Identify efforts to promote accessibility and receive feedback

**Comment by eelzi-ONRR** [comment]
I do have a question we can discuss at our metrics meeting: how do we define testing? Because sometimes we make issues for accessibility improvements that we can see are there without doing formal testing

**Comment by Maroyafaied** [comment]
@eelzi-ONRR that's a good point, I suggest we change the word "testing" to "evaluating" , would that cover it? Please feel free to suggest how to change it to cover any types of accessibility issues identified whether through formal testing or evaluating/auditing.

**Comment by Maroyafaied** [comment]
@eelzi-ONRR that's a good point, I suggest we change the word "testing" to "evaluating" , would that cover it? Please feel free to suggest how to change it to cover any types of accessibility issues identified whether through formal testing or evaluating/auditing.

**Comment by eelzi-ONRR** [comment]
@Maroyafaied Yes! I think using the word evaluate works!
