### ISSUE TITLE
Q1 Metrics - Tech 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3092]
[Document Q1 metrics (oct-dec)](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7B2FBE43D3-8EF5-4CDC-A8B4-F80B96CD3866%7D&file=FY%2024%20Goals.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1&login_hint=faiedm%40mms.gov&ct=1703716001929&wdOrigin=OFFICECOM-WEB.START.EDGEWORTH&cid=4102c5e7-4a81-44ef-a856-0f41c80ca1a9&wdPreviousSessionSrc=HarmonyWeb&wdPreviousSession=e0c5c814-0baf-42a1-bb6d-8ee21f2e4427) 

- [x] # of tech enhancement issues 
- [x]  Number of open and valid reported vulnerabilities 
- [x]  Median time to remediate/mitigate a valid report (in days) 
- [x] # of tech issues resolved from user research
- [ ] Innovative tech solutions & result from implementation

**Comment by eelzi-ONRR** [comment]
One of my things to track is "Innovative tech solutions & result from implementation". I'm not certain what would fall into this category

**Comment by eelzi-ONRR** [comment]
@Maroyafaied Ah okay. My name is in the spreadsheet for that metric - I'll remove it

**Comment by Maroyafaied** [comment]
@greensomes please review the high level summary below that I wrote for Q1 metrics under "innovative tech solutions and results of implementation". Feel free to revise or re-write. 

- Database change management was implemented by migrating to Liquibase. This resulted in improved delivery performance by reducing the build time in CircleCi. Prior to this implementation, the database build process would take up to 30 minutes, the process now takes 15 minutes or less. Another advantage of the database change management is that we are now able to have version control for the database.

**Comment by greensomes** [comment]
@Maroyafaied, the summary above looks great!
