### ISSUE TITLE
Q1 Metrics - Customer Experience 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3093]
[Document Q1 metrics (oct-dec)](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7B2FBE43D3-8EF5-4CDC-A8B4-F80B96CD3866%7D&file=FY%2024%20Goals.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1&login_hint=faiedm%40mms.gov&ct=1703716001929&wdOrigin=OFFICECOM-WEB.START.EDGEWORTH&cid=4102c5e7-4a81-44ef-a856-0f41c80ca1a9&wdPreviousSessionSrc=HarmonyWeb&wdPreviousSession=e0c5c814-0baf-42a1-bb6d-8ee21f2e4427) 

- [x] Track planned usability studies and goal of study @lpgoldstein 
- [x] # of users recruited @lpgoldstein 
- [x] # of users accepted recruitment & participated in study @lpgoldstein 
- [x] Inclusive research (how we plan research and document in research plan) @eelzi-ONRR 
- [x] # of findings/recommendations resulting from user research @AlexandracmONRR 
- [x] Identify user-centered design efforts @AlexandracmONRR

**Comment by AlexandracmONRR** [comment]
**For # of findings/recommendations resulting from user research, there were very few with the issues labeled "Enhancement", "research"**

- not labeled but relevant, the user research consent for was updated based on user research done


**For identify user-centered design efforts, there were very few issues labeled "design", "enhancement", "metrics"**

- not labeled but relevant, completed RV issues
- not labeled but relevant, IDEA Act DX issues



**Questions for metrics meeting:**

- I'm thinking this is a yes, but should we go back and retroactively update labels that align with the instructed label criteria?

**Comment by lpgoldstein** [comment]
@AlexandracmONRR Please go back and retroactively update labels to align with the criteria - I've been trying to do it as I go through velocity but I'm sure I've missed some.
