### ISSUE TITLE
Add question mark glossary icon to query tool column headings - Sales data 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3106]

**Comment by greensomes** [comment]
@Maroyafaied, are we adding this for all column headings or just a specific subset? If a subset, which columns need to be included?

**Comment by Maroyafaied** [comment]
@greensomes I'd like to have it for all the highlighted terms. Basically all the column headings except commodity and for the land type filter heading. 
![image](https://github.com/DOI-ONRR/nrrd/assets/40175688/2465da23-25ee-4c7e-aead-ba095bd6506a)
