### ISSUE TITLE
Explore data: reduce height of comparison and nationwide summary button

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3113]
At 100% on large laptop screen dimension, this button blocks enough of the map so that Florida and Gulf of Mexico cannot be selected or hovered-over. Making the button wider and eliminating the line break is one possible solution. Or consider removing text from the button and just have the arrow

<img width="1393" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUNXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac546829d7739a0ecfc729f921e4870f6bfed1b3/image.png" alt="image.png" />

**Comment by greensomes** [comment]
@eelzi-ONRR, please [review the changes](https://nrrd-preview.app.cloud.gov/sites/3113-explore-data-button-size/explore) for this issue. I've reduced the button size and font size. Let me know if it looks good or if it needs to be further refined. Thanks!

**Comment by eelzi-ONRR** [comment]
@greensomes It looks and functions better now! Thank you!

One thing I notice though is that two of the states that the button previously covered - Florida and Alaska - while now the button doesn't cover them, the user has to click on a very specific spot within that state to select it - with all the other states the user can click on anywhere in the state boundary to select it.  At some levels of magnification the user can't click on those states at all.

I can show this at sync up tomorrow if that helps
