### ISSUE TITLE
Sales data: explore prototype hole poking

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3116]

**Comment by eelzi-ONRR** [comment]
@lpgoldstein @AlexandracmONRR @Maroyafaied @cthomasONRR @greensomes Here's what is hopefully the final set of prototypes to review for holepoking next week. If you can take some time to look at and think about them before our session, that would be great! 
There are 4 options - starting with Full page v.3.0.1: https://egyd9u.axshare.com/?id=hg5zun&p=full_page_v_3_0_1_-_legend_title__glossary_in_filt&g=1&sc=1

Things to note: 
- Each option has 3 screen sizes: Full, large/medium laptop, mobile. The only thing you need to pay attention to between the screen sizes is the map and filter area - everything below the map are patterns we already use so it will not be different from our existing responsiveness.
- Everything below the map section is the same across all 4 options. So if you look at what is below the map in v.3.0.1, no need to worry about what is below the map on the other options.
- The two things that change across the four options are the placement of the map title and key, and the format/placement of the glossary. The four options show the four combinations for changing each of those two things.
- The glossary expansion should work on all examples - hover just below the arrow for it to turn gray and then click to expand or close - using the same pattern as what's on other pages on NRRD
- Easy commands for Axure viewing: ctrl+mouse wheel for zoom, mouse wheel for vertical scroll, shift+mouse wheel for horizontal scroll

**Comment by eelzi-ONRR** [comment]
@Maroyafaied @cthomasONRR @greensomes @AlexandracmONRR @lpgoldstein I think I addressed everything we discussed today. If you have any other feedback let me know. https://egyd9u.axshare.com/?id=xhpay2&p=full_page_v_4&g=1&sc=1

**Changes:** 
- Moved map title higher and centered
- Emphasized the glossary is not a filter by using the existing button style

Using the existing button style definitely draws the eye to the glossary, but I don't necessarily think that's a bad thing

**Comment by AlexandracmONRR** [comment]
I like the changes you made; I think both are improvements. Design looks great!

**Comment by eelzi-ONRR** [comment]
@Maroyafaied Done! The prototype link is the same - here's the direct link to the full screen view only: https://egyd9u.axshare.com/?id=trl28l&p=full_page_v_4_full_screen_only&g=1&sc=1

**Comment by Maroyafaied** [comment]
@eelzi-ONRR You're awesome, thank you!
