### ISSUE TITLE
 Explore Data - Revenue - Nationwide Summary - "Other Revenues" and "Inspection Fees" definitions are mis-matched

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#3117]
I just noticed that in Explore Data - Revenue - Nationwide Summary, the "Other Revenues" and "Inspection Fees" definitions are mis-matched. We need to put the correct definition with the correct term.

<img width="579" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjZiQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fcae99a51f69bc6334b8899ccc8416e5eaf71e8e/image.png" alt="image.png" />

<img width="506" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0NiQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9766aa272c36bdb2847cd87f80e053c7f2b6a372/image.png" alt="image.png" />

**Comment by cthomasONRR** [comment]
I think the definitions should match what's in the download data page:

![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/9eca18fb-b0eb-45e5-89c4-698dfaf97c43)

**Comment by Maroyafaied** [comment]
@cthomasONRR I believe that you can change the code in line 78 and 80 within nrrd>src>components>sections>ExploreData>Revenue>RevenueNationalSummary.js <img width="1662" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHUrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--516150d001e89f6faf6eab4488d2c7be3845c8dc/image.png" alt="image.png" />

**Comment by cthomasONRR** [comment]
@Maroyafaied @greensomes 

This update is in the current data PR: https://github.com/DOI-ONRR/nrrd/pull/3115

Maroya, thanks for showing me where to update the text. It's corrected in the PR:
![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/b13e59dc-e1e6-4672-b6e3-3c6f6a78f5e7)
