### ISSUE TITLE
Bias-reduction activity: read article

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3119]
Prior to interviews for study 39_Sales Data. please read this article: 

https://www.userinterviews.com/blog/how-to-reduce-bias-in-ux-research

As our first "activity" of this kind, this is intended to be an introduction. We'll get into more details about bias types and actions to take in future activities.

**Comment by AlexandracmONRR** [comment]
I read this article and took notes - really good overview with practical examples of how to identify and reduce bias.

**Comment by Maroyafaied** [comment]
I read as well, great article!

**Comment by lpgoldstein** [comment]
Very easy read and easy to implement activities. Then I went down a rabbit hole following links to various articles. Thanks for sharing!

**Comment by cthomasONRR** [comment]
I read the article, good points and easy to read.

**Comment by greensomes** [comment]
Interesting article! Thanks for sharing!
