### ISSUE TITLE
Questions for Maroya

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3121]
Please start documenting any questions you have for me in [this doc](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Supervisory%20Info/Questions%20for%20Maroya.docx?d=web527de0cc1947b0b28fb750cd0e607f&csf=1&web=1&e=tPggvG), I will keep this issue open throughout my time here.

**Comment by greensomes** [comment]
I'd like to discuss, prioritize, and formulate a plan for taking care of some of the technical debt that has accumulated for both revenuedata.doi.gov and onrr.gov. This includes:

- Upgrading Gatsby/React
- MaterialUI -> USWDS components
- Postgresql Versions
- Fixing/maintaining automated browser tests
- Upgrading Directus
- Upgrading Vue.js

**Comment by Maroyafaied** [comment]
I answered the questions on the doc and happy to discuss any of them further. @greensomes I'm happy to discuss the tech debt with you. I believe everything you listed was included in FY24 high level goals so I'd encourage the new manager to keep these tech debts as a priority and to trust Jeff's  judgement as to what needs to be taken care of sooner than later as well as being upfront about how difficult/time consuming some of these upgrades will be.
