### ISSUE TITLE
Q1 metrics snapshot

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3124]
Nathan asked we create a snapshot with charts/tables/highlights for Q1 similar to what we provided at the end of FY23

**Comment by Maroyafaied** [comment]
@eelzi-ONRR would it be possible to create a timeline chart for Q1 similar to the one you did for FY23?
<img width="1308" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2pQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd25b176072122dedcf6ca193f8ff88607d062d9/image.png" alt="image.png" />

**Comment by Maroyafaied** [comment]
@lpgoldstein @AlexandracmONRR here's the draft I started, feel free to make any changes. https://doimspp.sharepoint.com/:p:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7B0815AA5B-4038-4A51-999B-B39FB44C854C%7D&file=Q1%20Metrics%20Highlights.pptx&action=edit&mobileredirect=true

**Comment by Maroyafaied** [comment]
@eelzi-ONRR Thanks for creating the analytics & outreach charts. I've added them to the power point.

**Comment by AlexandracmONRR** [comment]
@Maroyafaied [the updated PowerPoint can be found here.](https://doimspp.sharepoint.com/:p:/r/sites/NRRD/Shared%20Documents/General/Admin/Goals%20%26%20Accomplishments/FY%2024/ONRR-ODDD-Metrics-Q1-2024.pptx?d=we7a66aa2ed994795998d14d486829777&csf=1&web=1&e=H5UCEF) Please let Lindsay and I know if there is any additional changes you want us to make!

**Comment by Maroyafaied** [comment]
This looks great. Thank you both!
