### ISSUE TITLE
Submit speaking proposal to UXPA Boston

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3128]
Due February 4
http://conference.uxpaboston.org/?_ga=2.260193677.1655882405.1704983280-549985124.1704983280&_gl=1%2A13ztxlj%2A_ga%2ANTQ5OTg1MTI0LjE3MDQ5ODMyODA.%2A_ga_SK1Q0YNBSL%2AMTcwNDk4MzI4MC4xLjEuMTcwNDk4MzQzNS40OS4wLjA.

**Comment by AlexandracmONRR** [comment]
Meeting to discuss submission on Monday, Jan 22

**Comment by AlexandracmONRR** [comment]
Lindsay to develop proposal on consent form redevelopment.
Alex to repurpose proposal on participatory design.

Submission Deadline is Feb 4, 2024.

**Comment by AlexandracmONRR** [comment]
Presentation proposal drafted here: https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Outreach/Outreach%20Proposals%20%26%20Presentations/FY24/UXPA%20Boston%202024%20-%20May/UXPA-Boston-Conference-Submission-Template-2024.docx?d=wd3e3bb1080204a1eb47d1b65e8ddb7f3&csf=1&web=1&e=TeDDTK

**Comment by lpgoldstein** [comment]
Submitted the consent process topic.

**Comment by AlexandracmONRR** [comment]
Submitted the stakeholder engagement topic
