### ISSUE TITLE
Add mui icon for what's new box

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3130]
We want this icon to catch attention when we publish sales data. This can be done in this PR https://github.com/DOI-ONRR/nrrd/pull/2895

**Comment by greensomes** [comment]
@Maroyafaied, has the icon been selected? If so, please attach a screenshot. Thanks!

**Comment by Maroyafaied** [comment]
@greensomes Yes, I believe Erin has selected one that I'm good with. @eelzi-ONRR please attach the link or screenshot.

**Comment by Maroyafaied** [comment]
@greensomes I believe it's this one but @eelzi-ONRR please confirm. 
![image](https://github.com/DOI-ONRR/nrrd/assets/40175688/bbb87d03-181b-48d1-86bc-472f1eb22dc7)

**Comment by eelzi-ONRR** [comment]
@Maroyafaied @greensomes Yes - that's the correct icon!

I'll get the mock-up of the changes done by tomorrow

**Comment by greensomes** [comment]
Here's the  [preview site](https://nrrd-preview.app.cloud.gov/sites/3130-add-mui-icon-for-whats-new-box/).
