### ISSUE TITLE
What's new mock-up

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3134]
Mock up new format for What's new box - split what's new and regular releases, add mui icon for New

**Comment by eelzi-ONRR** [comment]
Got quick input from 4 people outside of ODDD. 

@greensomes Here's the mock-up <img width="1502" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnJkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d3c8c48575d2c7af2323eed79be8e6c3d251f6e/NRRD%20homepage%20what%27s%20new.png" alt="NRRD homepage what's new.png" />

**Comment by greensomes** [comment]
@eelzi-ONRR, the above mock-up has been implemented and can be [reviewed here](https://nrrd-preview.app.cloud.gov/sites/federal-sales-data/).

**Comment by eelzi-ONRR** [comment]
@greensomes Love it! It looks just as expected!
