### ISSUE TITLE
Review sales data for accuracy - query tool 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3142]
Please review the query tool against the [raw data](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/NRRD/Data/Sales%20Data/Data/Federal%20Oil%20Gas%20and%20NGL%20Commodity%20Sales%20Year%20Data%20as%20of%2011-6-2023.xlsx?d=w4e57402346d847b9aa5c311f77d37a30&csf=1&web=1&e=2VLYWt) and tag Jeff if you run into any issues.

https://nrrd-preview.app.cloud.gov/sites/federal-sales-data/query-data/

**Comment by cthomasONRR** [comment]
I think Nadia mentioned this already, but I agree that it looks weird that Gas for CA and CO has a processing allowance. Most processing allowances should be with the NGLs, but there could be a valid explanation via product codes and transaction codes that explains this. I just don't have that detailed info to understand.

2022-2020 only have Gas processing allowances for CA and CO. 2019-2013, many more states have processing allowances tied to Gas. So again, a bit weird that the reporting trends seem to change at 2019/2020 and I don't think it's associated with COVID.

![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/20a4c974-99ad-4645-80db-1d94f8e38846)

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks! Sorry I didn't realize Gas MMBtu has in a separate column instead of within commodity like Gas mcf, Oil and NGLs.

**Comment by cthomasONRR** [comment]
I don't know if this can be changed design-wise, but having 2 lateral scrolls (one within the dataset, one for the entire page) can be confusing. If you don't scroll all the way down, the users can't see that there's 2 lateral scrolls to control. The one within the dataset is hidden.

![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/cdab8442-a116-4274-9522-5cb9ba47a8fe)

**Comment by cthomasONRR** [comment]
In the raw data, are some years where NGLs and/or Oil have a Gas MMBtu Volume associated with them. Most of them are very small negative amounts but there is one line for GoM Oil in 2018 that looks really wrong:
![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/b73b8e72-cded-4ac5-8578-b5659743115c)

**Comment by Maroyafaied** [comment]
@cthomasONRR I emailed DORC about the gas processing allowances showing up.  I think it's probably a reporting error for the  MMbtu volume showing for oil in GOM in 2018 but we can also bring that up with DORC.

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks- I'm just trying to note anything that looks weird to me. So far all numbers are matching though!

**Comment by cthomasONRR** [comment]
@Maroyafaied Ok I think I'm done checking. I did the typical monthly check as shown below, but also went line-by-line for multiple years to check numbers, and reviewed the raw data for potential errors. I didn't find any discrepancies with numbers between the preview site and raw data. 

Query Data - Federal Sales - Calendar Year
   - [ ] One to three Commodities
   - [ ] One Land Type filter
   - [ ] One State 
   - [ ] One Offshore Region
   - [ ] Clear All and change grouping
   - [ ] Downloads matches filtered data

**Comment by lpgoldstein** [comment]
@Maroyafaied I've also finished checking and haven't found anything other than what has already been noted. I'll add "add a column" to the data checklist as well. If you and @cthomasONRR are in agreement I can add to the wiki.

**Comment by cthomasONRR** [comment]
@lpgoldstein I'm good with that, thanks!
