### ISSUE TITLE
Compile existing user research on onrr roles/teams and how they use our sites and data

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3146]
Review recent research for this info and come up with a place to compile it for easy reference. Maybe develop a system to do this after each user study

**Comment by eelzi-ONRR** [comment]
@lpgoldstein @AlexandracmONRR  I started a sheet and added info from the most recent studies for NRRD and onrr.gov. 

https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/NRRD/User%20Research/Site%20use%20by%20ONRR%20team.xlsx?d=wbc9049f47229484dba5872a5c35b2093&csf=1&web=1&e=sPIHRp&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMH0



Do you think we should add a column for user type?

 I was thinking once we get all the info in here we can decide if we want to organize it differently or write up summaries for each team, or attach teams to user types, etc.

**Comment by lpgoldstein** [comment]
@eelzi-ONRR I think so - then we can see if there are any patterns. If it gets too complicated we can always stop.

**Comment by AlexandracmONRR** [comment]
@lpgoldstein and @eelzi-ONRR - thanks for this spreadsheet. Yes, I think we should try to put in user types to identify patterns. Maybe we don't have to limit ourselves to user types that already exist, just in case we think some people may fall into another category.

**Comment by eelzi-ONRR** [comment]
For the NRRD studies: Alex 17-26, Lindsay 27-33, Erin 34-39
For onr.gov studies: Erin 1-4, Alex 5-10, Lindsay 11-14

**Comment by eelzi-ONRR** [comment]
I've finished the my assigned studies

**Comment by lpgoldstein** [comment]
No one is assigned to study 15 for onrr.gov so I'm doing that one too.

**Comment by lpgoldstein** [comment]
Done!

**Comment by AlexandracmONRR** [comment]
I finished NRRD studies, but still working on my onrr.gov studies. I will finish up tomorrow and close out the issue.

**Comment by AlexandracmONRR** [comment]
Completed ONRR studies 5-7, I will complete 8-10 next sprint.
