### ISSUE TITLE
Update Sales Data diagram's equations

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/nrrd#3156]

**Comment by Maroyafaied** [comment]
This was feedback given in user research study #39. Updated prototype: https://lgx2yt.axshare.com/?id=gger9x&p=uta_-_document_download

**Comment by Maroyafaied** [comment]
@AlexandracmONRR Management asked to change "Volume" to "Sales Volume", please let me know when the prototype is updated and I'll share it again with them. Here's a screen shot of both places to make that change. <img width="520" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1Q4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a200866f17164a5ee71f9ba9fdb51eb1d971cfb5/image.png" alt="image.png" />
