### ISSUE TITLE
Research Miro Board license

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/nrrd#3158]
1 license or multiple - how it would work for our team and the cost for 1 or multiple licenses

**Comment by AlexandracmONRR** [comment]
[Miro ](https://miro.com/pricing/
)$16 per month for 1 license
- Unlimited private and secure workspaces with unlimited boards for every team and client
- Securely collaborate outside your team with unlimited guests on private and team boards. Sign-in required
- Easily visualize processes and systems with 2000+ advanced diagramming shapes from BPMN, UML, AWS, Google, Azure, Cisco, and more
- Import and manage multiple issue types from Jira with Program Board, then draw connections between them with Dependencies AppNEW
- Elevate meetings and workshops with a suite of tools for managing content, setting agendas, and facilitating activities like breakouts and voting with Miro Activities
- Secure and simplify access with Single Sign On (SSO) through OKTA, OneLogin, Auth0, and more

**Comment by AlexandracmONRR** [comment]
Figjam $15 per month for 1 license (usually it's $5 per month, but more expensive bc agreement with federal gov)

- Org-wide libraries
- Open sessions for 24 hours
- Centralized content management
- Custom templates
- Custom color palettes
- Unified admin and billing
- Private plugins and widgets
- Single sign-on
- [Fedramp review is in process](https://marketplace.fedramp.gov/products/FR2311345531)
- Need a [plugin to go from excel to sticky notes](https://www.figma.com/community/plugin/1221892477305959368/table-to-sticky-notes)

**Comment by Maroyafaied** [comment]
I sent an email to the security team and included Alex. I will take myself off this issue and @AlexandracmONRR will follow up
