### ISSUE TITLE
Update glossary terms to sales data

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3166]
This was feedback given from user research study #39. Since the royalty due equation is updated, we need to add a definition to "Unit Value" and change the definition to sales value since it's very vague now.

- Unit Value: the price of each unit of production sold (note: this is a definition I made based on the definition used on RV's page in onrr.gov
- Sales Value: The value of a commodity when sales volume is multiplied by price. (note: this is a definition I made based on language from the handbook)

**Comment by Maroyafaied** [comment]
Updated in this branch https://nrrd-preview.app.cloud.gov/sites/federal-sales-data/

**Comment by Maroyafaied** [comment]
Need to this equation out from RVLA since it's different than the one that will be displayed. <img width="1063" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE1KQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fed6b4aef26e3b2664268378f9a0b5de84185aa3/image.png" alt="image.png" />

**Comment by Maroyafaied** [comment]
@cthomasONRR can you please review the definitions I updated for Unit Value, Sales Price, and RVLA. Thanks
https://nrrd-preview.app.cloud.gov/sites/federal-sales-data/

**Comment by cthomasONRR** [comment]
@Maroyafaied Are these definitions supposed to just be in the glossary or also the data dictionary?

I found them in the glossary, but I'm wondering if they also should all be in the data dictionary. The definitions look ok to me in the glossary. If we're taking out the equation for RVLA, should we do the same with RVPA? It looks odd for one to have an equation and not the other:

![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/475fe9d5-0c55-448e-9a52-5cd6c3d15db1)


In the data dictionary, sales value and RVLA are not updated, and unit value is not present.

**Comment by Maroyafaied** [comment]
@cthomasONRR Thanks for catching they need to be updated in the data dictionary, I'll do that and remove the equation from RVLA.  We only use "unit value" in the process diagram and it's not a field in the dataset itself so I don't think it needs to be added to the data dictionary since those terms are specific to what's in the dataset.
