### ISSUE TITLE
Communication Plan for sales data publication 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3170]
- [x] Social media post
- [x] ONRR wide email?
- [ ] Propose to IMPACT EXPO - demo NRRD new features
- [ ] Email data communities (if any)?
- [x] Email UX participants
- [ ] Other ideas

**Comment by eelzi-ONRR** [comment]
Lindsay had the idea of maybe a short Impact Expo session

**Comment by lpgoldstein** [comment]
Email user research participants too

**Comment by lpgoldstein** [comment]
@AlexandracmONRR Adding you since I'll be out next week. I think we can close once we find out about ONRR wide email. I'll post dataset to DOI econ community next week.
