### ISSUE TITLE
Prepare for ELT presentation on sales data 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3171]
Nathan asked we present to the ELT on our progress on sales data

**Comment by Maroyafaied** [comment]
@lpgoldstein @eelzi-ONRR @AlexandracmONRR  here is a draft of the outline for the presentation, feel free to make edits/suggestions. https://doimspp.sharepoint.com/:w:/r/sites/NRRD/_layouts/15/Doc.aspx?sourcedoc=%7BEE8A0ECF-EA35-471B-97C2-BD4BCCBC8788%7D&file=ELT%20Sales%20Data%20Outline.docx&action=default&mobileredirect=true&DefaultItemOpen=1&login_hint=faiedm%40mms.gov&ct=1706648128482&wdOrigin=OFFICECOM-WEB.START.EDGEWORTH&cid=db0f338b-b79b-4912-96b2-c94314af53e2&wdPreviousSessionSrc=HarmonyWeb&wdPreviousSession=4fb922b9-c818-4d5b-ad1d-d5a2331a9a6e

**Comment by eelzi-ONRR** [comment]
@Maroyafaied This looks good to me. How long do we have? Will they be able to ask questions? (Just mentally preparing myself!)

**Comment by Maroyafaied** [comment]
We have 30 minutes.

**Comment by lpgoldstein** [comment]
@Maroyafaied Looks good!
