### ISSUE TITLE
Downloading historical files sometimes adds an extra "downloads" to the URL

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3173]
User reported the historical download links taking them to the 404 page. We've found this happens because sometimes an extra "downloads" gets added in the URL. This might happen when the user clicks on the link multiple times in a short time period. Replicating the issue is inconsistent but we can replicate it. 

https://revenuedata.doi.gov/downloads

<img width="1244" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjREQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d30b240ca4388b5fb5c2d07c4754f495e4c1c95/image.png" alt="image.png" />

<img width="1333" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjhEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8172a896a27b9f116f1c7e3ca81ecfb60074c956/image%20%281%29.png" alt="image (1).png" />

**Comment by greensomes** [comment]
This was resolved on an ad hoc commit prior to the sales data release.
