### ISSUE TITLE
Final review of sales data preview branch

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3180]
I'll make a checklist but would like everyone to review before presenting & giving a demo to the ELT next week.

**Comment by Maroyafaied** [comment]
**What's new** @AlexandracmONRR 
- [ ] Grammar & Spelling
- [ ] Links work 

**Glossary** @AlexandracmONRR 
- [ ] Effective Royalty Rate
- [ ] MMBtu
- [ ] Processing Allowance
- [ ] Royalty Value Less Allowance
- [ ] Royalty Value Prior Allowances
- [ ] Sales Value
- [ ] Sales Volume
- [ ] Sales Year
- [ ] Transportation Allowance
- [ ] Unit Value
- [ ] Glossary definitions match data dictionary definitions 

**Download Page** @eelzi-ONRR 
- [ ] Content on main download page
- [ ] Into Paragraph
- [ ] Download links work
- [ ] Scope
- [ ] Data publication
- [ ] What is the difference between Sales Year and Accounting Year data?
- [ ] What are transaction codes (TC)?
- [ ] TC Table accuracy
- [ ] How are Quality Bank and Gravity Bank Adjustments calculated?
- [ ] What does “not tied to a commodity” mean?
- [ ] What is COVID royalty relief?
- [ ] Data dictionary
- [ ] All links work

**Process Diagram Content** @cthomasONRR 

Reporters submit royalty reporting
- [ ] Reporters submit royalty reporting
- [ ] A. Calculate federal royalty value with adjustments for royalty relief and/or quality gravity bank
- [ ] B. Deduct regulatory allowances
- [ ] Citations links work and consistency in capitalization 

ONRR aggregation sales data
- [ ] Content
- [ ] Citations links work and consistency in capitalization 

Calculation of Effective Royalty Rate
- [ ] Content
- [ ] Accuracy of equation
- [ ] Citations links work and consistency in capitalization 

**Query tool** @lpgoldstein 
Check data accuracy by doing the following 
- [ ] One to three Commodities
- [ ] One Land Type filter
- [ ] One State
- [ ] One Offshore Region
- [ ] Add a column

 

- [ ] Clear All and change grouping

- [ ]  Downloads matches filtered data

**Comment by cthomasONRR** [comment]
@Maroyafaied I made a bunch of typo and citation updates. I'm done with my review.

**Comment by Maroyafaied** [comment]
@lpgoldstein this link doesn't work <img width="1226" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUFmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5801bd7ad681938077d9c9933dd99dc9ca4b26e0/image.png" alt="image.png" />

**Comment by AlexandracmONRR** [comment]
The what's new box links to the old "sales data" download page.

<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd291QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--42273ff19dd4e0473c7a84ec761bfe584aa9f7a8/whatsnewbox.png" alt="whatsnewbox.png" />

**Comment by Maroyafaied** [comment]
@AlexandracmONRR good catch, I fixed it. Please review again!

**Comment by AlexandracmONRR** [comment]
Is it okay that the ERR defined in the glossary is different than the ERR defined on the data download page?

<img width="964" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVl5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a9b13edc19058c52e747d439b4fd8f43ebff653/image.png" alt="image.png" />

<img width="722" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWN5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--68f7fa943f2c70c000e351ac55a63f628ec8c866/image.png" alt="image.png" />

**Comment by eelzi-ONRR** [comment]
@lpgoldstein @Maroyafaied This should be one word for consistency: 
![image](https://github.com/DOI-ONRR/nrrd/assets/115593715/4b0a591b-b4b9-4c79-b9a9-d4dda2b3fe32)

**Comment by eelzi-ONRR** [comment]
@Maroyafaied Alex and Lindsay and I just met - Alex is going to make the edits in the PR

**Comment by AlexandracmONRR** [comment]
@lpgoldstein @eelzi-ONRR @Maroyafaied  - regarding Sales Volume, the glossary is a simple definition, but the DD page is very detailed and specific to the Federal Sales dataset.

--glossary--
![image](https://github.com/DOI-ONRR/nrrd/assets/122935097/3f0c336b-1cb2-4105-94c0-d623fad37e81)
--data download page--
![image](https://github.com/DOI-ONRR/nrrd/assets/122935097/8368bd36-1de5-4512-89c5-99d5dbeefb6e)

I propose we change the DD page definition to:

**Sales Volume**: The volume of the mineral/resource sold. Note: for federal sales, the volume of the product sold or removed from the lease or agreement and is attributable to the lease or to the lease-agreement combination, sales type code, product code, and sales month reported. The unit of measurement is located under the commodity column. The sales volume (or quantity, if geothermal) reported corresponds to the portion of the total production from the lease or from the lease-agreement combination. This is an industry reported value on the Form ONRR-2014.

**Comment by Maroyafaied** [comment]
@AlexandracmONRR I believe sales volume is one of the definitions that we need to look further into and a recommendation that came out of the study. There should be an issue open for it with a suggested definition from DORC. I believe we are leaving this definition enhancement to be done after publishing. @eelzi-ONRR please correct me if I'm wrong. We do need to make an issue for the ERR definition since Howard asked we enhance it and I think that should be done before publishing since the feedback came from the director.

**Comment by AlexandracmONRR** [comment]
@Maroyafaied and @eelzi-ONRR - yes, the sales volume improvement is issue #3204. 

I will make an issue for fixing the ERR definition now.

**Comment by eelzi-ONRR** [comment]
@Maroyafaied @AlexandracmONRR Yes - we rated the sales volume definition as medium impact and medium priority so we don't need to worry about it yet. We still have some that are are either high impact-medium priority or medium impact-high priority, and do not involve consulting with another team - we should focus on those first
