### ISSUE TITLE
Update User Research Process

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3184]
Add a checklist for running studies and any other process changes that come out of debrief

**Comment by eelzi-ONRR** [comment]
@AlexandracmONRR @lpgoldstein I made a draft of the user research process wiki update and the research checklist, based off our debrief meeting. Feel free to make comments of edits. Once we all three sign off I can put it on the wiki
https://doimspp-my.sharepoint.com/:w:/g/personal/elzie_mms_gov/Ecjtnt_OxgFGt8E9YGRToogB9ZFMeXRXnJA9YsVG2O7iDg?e=n4HSaW

https://doimspp-my.sharepoint.com/:w:/g/personal/elzie_mms_gov/EfT2XQu6YoxCnH2pSJjn9rUB3jtqvf3ykh9zIHJ5T2Ajzw?e=JpFRyR

**Comment by AlexandracmONRR** [comment]
It looks great! I reviewed and just made a couple of tracked changes and had a few comment exchanges.

**Comment by eelzi-ONRR** [comment]
@AlexandracmONRR @lpgoldstein I added these to the wiki - can you review one more time for typos? Thanks!

https://github.com/DOI-ONRR/research/wiki/User-research-study-checklist
https://github.com/DOI-ONRR/research/wiki/User-research-study-process

**Comment by eelzi-ONRR** [comment]
@AlexandracmONRR @lpgoldstein I added these to the wiki - can you review one more time for typos? Thanks!

https://github.com/DOI-ONRR/research/wiki/User-research-study-checklist
https://github.com/DOI-ONRR/research/wiki/User-research-study-process

**Comment by lpgoldstein** [comment]
@eelzi-ONRR @AlexandracmONRR I'm out of the wiki and just made a few little edits. @eelzi-ONRR looks great!

**Comment by AlexandracmONRR** [comment]
I made a simple edit to the check list. I think it looks great! Closing the issue.
