### ISSUE TITLE
Organize work needed for developing explore data for federal sales 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3185]
Open smaller issues for developing explore data based on Erin's final prototype.

**Comment by eelzi-ONRR** [comment]
@greensomes Here's the prototype - it includes all previous versions but this link opens to the latest/final version https://egyd9u.axshare.com/?id=xhpay2&p=full_page_v_4&g=1&sc=1

**Comment by eelzi-ONRR** [comment]
@greensomes Here's the final prototype. If you want to set up a meeting to go over any questions or walk through detail of functionality before you start working, let me know.

https://egyd9u.axshare.com/?id=llohbd&p=full_page_v_5&sc=1&c=1

**Comment by greensomes** [comment]
From `src/pages/explore/index.mdx`:

- Update context to include federal sales data and queries for federal sales
- Add `ContextProvider` section for Federal Sales similar to other data types
- Add Federal Sales section component
- Add FederalSalesMap component
- Add summary cards
- Add PageSubMenu and associated components
- Add DetailCards
