### ISSUE TITLE
Federal sales data download page updates from user research study 39 recommendations

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3188]
- [x] Add term   "onshore" to sentence about federal land in the scope section of DD   page
- [x] Change "NGL" to "NGLs"
- [x] Define acronym for "TC" before it is used in the Scope section

**Comment by AlexandracmONRR** [comment]
Small change but want to be consistent with the other download pages:
In regular text (not heading text) can it be: "Download federal sales data:"

<img width="1051" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUlTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df3859abd09784f0ca14c028378b9d55165f3982/image.png" alt="image.png" />

**Comment by Maroyafaied** [comment]
@lpgoldstein can you add "s" to liquid, and make these changes in the glossary and main download page. Can you please also add the sales data category to the glossary for the NGL term and add the glossary icon the first time we mention it in the download page. Let me know if you have any questions. Las thing, please add a space before download data and add ":" after it. Thanks
<img width="1084" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTBXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c3d7711926cf555c44b498b0202aaf5f8d3e250/image.png" alt="image.png" />

<img width="796" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG9XQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1cc19a5455e577da53a1490aab168fe609ae73f2/image.png" alt="image.png" />
<img width="792" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXNXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--27e2742f82be3752a4e8071a78804bf1d2422eb8/image.png" alt="image.png" />

**Comment by lpgoldstein** [comment]
@Maroyafaied what do you think about deleting the word "products" after NGLs? I don't think we need it.

**Comment by Maroyafaied** [comment]
@lpgoldstein that's fine with me.
