### ISSUE TITLE
Update DD page Process Diagram Hover Overs in 2 parts (Federal Sales data)

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/nrrd#3196]
These changes should occur in all 3 steps of the process diagram:
- [x] When **mouse hovers over the blue underline links and arrow**, the blue underline disappears under the link text to show the user that something happens when they click it.
- [x] Add a **blue underline to the References bulleted points.** But when the **mouse hovers over the References bulleted points**, this underline should disappear. 

[Preview](https://nrrd-preview.app.cloud.gov/sites/3250-sales-data-download-page-accessibility-fixes-contrast-table-names-svgs/downloads/federal-sales/)

#3250 - Link colors, hover styling, decorative SVGs with aria hidden attribute, aria-label attribute to layout tables

**Comment by AlexandracmONRR** [comment]
@greensomes  - i'm moving this to next sprint so we can meet and discuss.

**Comment by AlexandracmONRR** [comment]
For first bullet:
<img width="1358" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHFtQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a5a551cb7c214c987aca77e11b01618b7da7cf2b/image.png" alt="image.png" />


<img width="1361" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDZtQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20fd09faa791f9bb417d8f52a5e1995aad85211d/image.png" alt="image.png" />

**Comment by greensomes** [comment]
@AlexandracmONRR, I can't see the images above. Can you upload them again or email them to me Thanks!
