### ISSUE TITLE
Provide a hover definition in process diagram for quality bank and gravity bank (Study 39 Sales Data)

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/nrrd#3197]
In step 1 (green step):

- [x] Request definition from outside ODDD team.
- [x] Within the description include a **hover over definition** for quality bank and gravity bank.

Definitions will be provided in comments once we have them.

**Comment by AlexandracmONRR** [comment]
OIG report (page 7, footnote 18) for Gravity Bank

Gravity bank: Gravity bank adjustments are a way to account for differing qualities of oil in a transportation system used by multiple producers. The quality of the oil is measured by its specific gravity; oils of differing quality or value have a different specific gravity.

**Comment by AlexandracmONRR** [comment]
Quality Bank definition from RV

Quality bank: A quality bank is used along an oil pipeline to mitigate material increases or decreases in each shipper’s respective oil value due to the commingling of oil in the pipeline. The quality bank charges or pays each shipper depending on the comparison of the quality of the pipeline common stream and the quality of each shipper’s oil.

**Comment by AlexandracmONRR** [comment]
Discussion to help us later:

Comment on DD content
![image](https://github.com/DOI-ONRR/nrrd/assets/122935097/475cfb26-2576-414c-a159-6e4481cf5f6a)


Handbook chapter 4
![image](https://github.com/DOI-ONRR/nrrd/assets/122935097/54f9b964-e4fd-4987-9aca-ec9efc07daf0)

DD content
![image](https://github.com/DOI-ONRR/nrrd/assets/122935097/0ec61629-677f-4edf-8b57-9fb93b10f3a5)

**Comment by Maroyafaied** [comment]
This is the definition DORC provided but suggested checking it with SMEs. 
Quality Bank and Gravity Bank Adjustments: are positive or negative values that reflects the value of different streams of crude oil that are shipped in Trans-Alaska Pipeline System (TAPS). A quality bank calculates, collects, and remits monetary adjustments among all shippers for changes in gravity and sulfur which result from mixing crude oil in pipelines.

**Comment by AlexandracmONRR** [comment]
@lpgoldstein - what do you think about this re-write? It is simplifying the concept a lot, but I thought maybe that is better? Also, this is grade 9!

Gravity Bank and Quality Bank Adjustments:
A monetary adjustment that accounts for differing qualities of oil in a transportation system used by many producers. The quality of the oil is measured by its change in gravity or sulfur.

**Comment by AlexandracmONRR** [comment]
What about this?: 

"A change to the royalty value that accounts for differing qualities of oil in a transportation system used by many producers."

**Comment by AlexandracmONRR** [comment]
@cthomasONRR - please review the quality bank and gravity bank definition when you get the chance. In Hemingway we got a grade 10 level.

A change to the royalty value that accounts for differing qualities of oil in a transportation system used by many producers.

**Comment by lpgoldstein** [comment]
@AlexandracmONRR let's keep the link in there as well.

**Comment by cthomasONRR** [comment]
@AlexandracmONRR @lpgoldstein 

I'm a little confused why we don't just use the Quality and Gravity Bank definition in the OIG report (page 7 footnote 18). It's grade 8: 

"A way to account for differing quantities of oil in a transportation system used by multiple producers. The quality of the oil is measured by its specific gravity. Oils of differing quality or value have a different specific gravity."

![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/eddbe2a9-6585-453b-8593-ae524d6464fe)

**Comment by cthomasONRR** [comment]
@lpgoldstein This definition explains both the quality and gravity components, which I think it important.

**Comment by AlexandracmONRR** [comment]
@cthomasONRR and @lpgoldstein - i'm also okay with that. The only thing that I think is unclear about this definition is that it is a change in the monetary value... "a way to account" is very vague and doesn't actually explain that it is a change in how much reporters pay. That could just be me though? I'm okay if you both think that it is fine the way it is.

My proposed definition:
"A change in value that accounts for differing quantities of oil in a transportation system used by multiple producers. The quality of the oil is measured by its specific gravity. Oils of differing quality or value have a different specific gravity."

**Comment by lpgoldstein** [comment]
@AlexandracmONRR How about adding "royalty" before value

**Comment by cthomasONRR** [comment]
@lpgoldstein @AlexandracmONRR I'm ok with that. Final definition: 

"A change in royalty value that accounts for differing quantities of oil in a transportation system used by multiple producers. The quality of the oil is measured by its specific gravity. Oils of differing quality or value have a different specific gravity."

![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/e0b8174d-fc90-4324-92f3-1ca391790d47)

**Comment by AlexandracmONRR** [comment]
@lpgoldstein and @cthomasONRR - im adding it into the federal sales data product codes PR now.

**Comment by AlexandracmONRR** [comment]
Added to PR.
