### ISSUE TITLE
Add query link to download page, study #39 Rec #8

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3201]
"A stakeholder of major importance would like sales data query tool in the data download page itself, not just in the top menu"

**Comment by Maroyafaied** [comment]
@eelzi-ONRR @AlexandracmONRR please review and let me know if you think this satisfies recommendation #8. Please feel free to suggest other way to incorporate the query link in the download page. Thanks 
https://nrrd-preview.app.cloud.gov/sites/federal-sales-data/downloads/federal-sales/

<img width="1218" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2drQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6dda1ae6c6a2fb51cbc14294f4046a03a9e250f9/image.png" alt="image.png" />

**Comment by AlexandracmONRR** [comment]
@Maroyafaied yes, it does. 

FYI, Lindsay and I will fix the note about the XLSX that appears just about the query link.

**Comment by eelzi-ONRR** [comment]
@Maroyafaied I think we can take out the first line: Query federal sales data:
@AlexandracmONRR can you move the XLSX note above the download links? It's not helpful for screen reader users to have it after the links.

**Comment by AlexandracmONRR** [comment]
@eelzi-ONRR and @Maroyafaied and @lpgoldstein - I just made these 2 changes.

**Comment by Maroyafaied** [comment]
@AlexandracmONRR Thanks!
