### ISSUE TITLE
Add product code table to Data Download page 

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/nrrd#3203]
- [x] Request included product codes in dataset from DORC
- [x] Include subheading in About the data section "What are product codes?"
- [x] Write 1-2 sentence descriptive text about product codes.
- [x] Include table of product codes (from DORC)

![image](https://github.com/DOI-ONRR/nrrd/assets/122935097/78611b51-bf50-4829-a974-11887f380d03)

**Comment by lpgoldstein** [comment]
[Product List.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0ltQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5779a7c88c9acf0361da60552b5d7278eb33cca3/Product%20List.xlsx)

**Comment by AlexandracmONRR** [comment]
Text for before table: 

**What are production codes?**
Production codes define the product or commodity on Form ONRR-2014. This dataset does not include all production codes reported on all Form ONRR-2014s. This dataset only includes production codes related to the product and byproducts of oil, gas, and NGLs.

**Comment by AlexandracmONRR** [comment]
PR was created federal-sales-data-productcodes to add product code info and table to the DD page. Christine reviewed and will merge it after Lindsay does her review of the PR.
