### ISSUE TITLE
Sales volume and Sales value definition, study #39 Rec #6

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3204]
Findings that we need to enhance the definitions. This is the definitions DORC recommended but advised we consult SMEs

Please see the definitions that DORC came up for your request. We did not have a definition prior to use. I did reach out to Wendy today to see if she has any thoughts. Maybe we should ask some SMEs as well?

Sales Volume: is a reported field on the ONRR-2014 form and refers to the quantity and quality of production as measured at the approved royalty measurement point which is then sold. The Bureau of Land Management (BLM) or Bureau of Safety and Environmental Enforcement (BSEE) approve measuring points.

Sales Value: is a reported field on the ONRR-2014 form. Reporters calculate this data by multiplying the volumes sold by the agreed upon unit price for each product based on pricing contracts and approved valuation guidelines.

**Comment by lpgoldstein** [comment]
@cthomasONRR Thanks for revisiting. This looks good to me. 

We can update with GOMESA tomorrow since it's not a data update?
