### ISSUE TITLE
Explore relevance and possibility of adding BLM serial register page links to citations - recommendation from user study #39

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3207]
In and other user research studies, users have expressed interest in learning more about ONRR and BLM connection. One user requested a link the citations section of the process diagram to the BLM serial register. https://reports.blm.gov/reports/MLRS

Conduct further user research

**Comment by AlexandracmONRR** [comment]
Could cause more confusion to include BLM serial register page link to the process diagram. @eelzi-ONRR - please review and close if you agree.

In further research, ask user participants if they would like to see more links and reassess if others request BLM serial register page.
