### ISSUE TITLE
SF-182 Code for America

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3217]
Fill out information for CFA Summit and submit SF-182. 

Link to the spreadsheet with costs: 

https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/Outreach/Outreach%20Proposals%20%26%20Presentations/FY24/Code%20for%20America?csf=1&web=1&e=ZYmvjX

https://summit.codeforamerica.org/

Assigning to current sprint but not essential to be done now.

**Comment by lpgoldstein** [comment]
I've left the note that several of us are speaking at the conference as a good luck charm but deleted in the sheet that I sent to Maroya to send on for approval. Hopefully we know soon if we are speaking.

**Comment by eelzi-ONRR** [comment]
Submitted mine

**Comment by lpgoldstein** [comment]
Also done.

**Comment by cthomasONRR** [comment]
Submitted SF-182

**Comment by greensomes** [comment]
@lpgoldstein, yes! I'll complete the SF-182.

**Comment by greensomes** [comment]
Done!
