### ISSUE TITLE
Update the Effective Royalty Rate definition, study #39

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/nrrd#3219]

**Comment by AlexandracmONRR** [comment]
@lpgoldstein and @eelzi-ONRR - what do you think about this definition?

Effective Royalty Rate  The term was created by the Office of Inspector General (OIG) and the calculation of the effective royalty rate is recommended by OIG Report 2021-CR-042 June 2023.

**Comment by eelzi-ONRR** [comment]
@AlexandracmONRR Thanks for starting this. Can we break it up so it's not just one long sentence? 

The calculation of the effective royalty rate is recommended by OIG Report 2021-CR-042 June 2023.  The term and concept of effective royalty rate was created by the Office of Inspector General (OIG).

**Comment by Maroyafaied** [comment]
@AlexandracmONRR @eelzi-ONRR Let's switch out the order of the sentences, here's my suggestion "The term and concept of effective royalty rate was created by the Office of Inspector General (OIG). The calculation of the effective royalty rate is defined by the OIG in [Report 2021-CR-042 June 2023](https://www.doioig.gov/reports/inspection-evaluation/us-department-interior-does-not-analyze-effective-royalty-rates)."

**Comment by lpgoldstein** [comment]
@AlexandracmONRR @eelzi-ONRR @Maroyafaied Let's make it active voice. The Office of Inspector General (OIG) created the term and concept of effective royalty rate The OIG defines the calculation of the effective royalty rate in [Report 2021-CR-042 June 2023](https://www.doioig.gov/reports/inspection-evaluation/us-department-interior-does-not-analyze-effective-royalty-rates).

**Comment by AlexandracmONRR** [comment]
@lpgoldstein @eelzi-ONRR @Maroyafaied - I think the final definition that Lindsay shared is great. I will make the change in NRRD tomorrow morning.

**Comment by AlexandracmONRR** [comment]
The ERR definition has been updated.
