### ISSUE TITLE
Check on ZenHub free usage account 

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3223]
Previously applied for  and granted free usage due to open source project [using this form  ](https://share.hsforms.com/1b0YheYwIQySbalBG94qEdA4t0dy?__hstc=246532251.a7db6689f60dbb9ef83fde5fbc0be0d4.1680121356424.1680121356424.1680121356424.1&__hssc=246532251.2.1680121356424&__hsfp=862196976) . I will email to make sure that I'm not listed as the account owner and that we will still have free usage since there's a notification about unlimited license trail ending. 
<img width="632" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnc0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24c9686a0f72e0776fb0ad0254b5b9b0e55561fc/image.png" alt="image.png" />

<img width="241" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnM0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--55febe06b99d7a65f8646bf188778ff9c7cc9737/image.png" alt="image.png" />

**Comment by lpgoldstein** [comment]
Email sent. Working with ONRR to purchase licenses.
