### ISSUE TITLE
Voyageurs

### ISSUE THREAD

**Issue by Maroyafaied** [DOI-ONRR/nrrd#3236]

**Comment by eelzi-ONRR** [comment]
**NRRD**
Review website accessibility statements
Plan for adding metadata to data.gov
Set up google search console and bing webmaster tools
Continue GA4 & 360 comparisons
Revenue true-up file
Glossary improvements
Sales data download - review for writing quality and plain language
Update NRRD database in cloud.gov
Bug fix - historical downloads
Start to build explore page
Accessibility fixes for process diagram
Review documentation for security assessment
Plan development of building explore for sales data
Implement user research recommendation  with M prority and impact
Hallway testing for explore prototypes
Plan user research for explore
SME update on sales data design process (present)
Compile existing user research on onrr roles/teams 
Social media post for sales data
Write user research agreement/consent blog
Digital.gov community summit
Communicate publication of sales data
DOI User Research Course
Write GA4 blog or wiki
Meet with NuAxis on GovCX collective
Meet with NASA and GSA on blog
Figure out Zenhub approval or another tool

**ONRR**
Review website accessibility statements
Continue GA4 & 360 comparisons
WYSIWIG Requirements
Fix bug - search link in edge mobile menu
Test WYSIWYG implementation options
Inline link editor fixes
Present 508 report at all-hands
Publish content blog
