### ISSUE TITLE
Submit Impact Expo talk

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/nrrd#3257]
Deadline: March 1, 2024
Email: onrrinternalcommunications@onrr.gov
Present days: April 2, 16, 30

What do we want to provide employees with during these awesome presentations?
- Mission-related presentations about ongoing efforts happening in different parts of the organization.
- Engaging lunch-n-learns on personal growth and wellness.
- Team building opportunities.
- Opportunities to recognize colleagues!
- Recorded presentations for those who might miss any part of the series.

**Comment by eelzi-ONRR** [comment]
We're scheduled for April 16th, at 10:00 – 10:30 am.

**Comment by eelzi-ONRR** [comment]
Sent them our topic on 2/27 and let them know we won't have a set of slides.
