### ISSUE TITLE
Revenue true-up: Replace monthly revenue data for 1/2014 to 12/2023

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/nrrd#3259]
Attached please find the revenue true-up file for publication to the NRRD.  This data will replace the monthly revenue data for January 2014 through December 2023.  Here is a summary of what is changing from what is currently published:

1.	In 2015, the bonus revenue is decreasing by $27,202.03 due to a state coal lease bonus payment being reversed
2.	In 2016, the other revenue is decreasing by $4,508.19 due to a code change to our total revenue query 
3.	In 2017, the other revenue is increasing by $4,508.19 due to a code change to our total revenue query
4.	In 2019-2023 the rent revenue is increasing each year by $1,853.50 due to a state oil shale lease that has 50% federal interest and has a legit rent obligation

Also, there are minor changes (less than $1) to most years.

[File attached in 2/21/2024 email]

Submitted by Stacey Kaiser

**Comment by greensomes** [comment]
There were discrepancies identified caused by incorrect/inconsistent location data. Specifically, Pointe Coupee, LA was submitted as "Pt. Coupee" and "Point Coupee". This has been resolved, but additional work is needed to transform the source data.
