### ISSUE TITLE
Remove query links from comparison cards

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3276]
Included with the federal sales explore data update.

Most of them don't work and removing them will help simplify the cards

<img width="620" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjJVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--151c31ad8324b0e6a87059a93910e3ad29516bd0/image.png" alt="image.png" />

<img width="583" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjZVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6200a86ddc0a8b412610700485516005b9d2fec/image.png" alt="image.png" />

<img width="425" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMitVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--91f5468f5d9dfc3369c4859f767a3a7904ec4d99/image.png" alt="image.png" />

<img width="266" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0dVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--052e5a286c4f64bb23adef9458778f5e4729852c/image.png" alt="image.png" />

**Comment by greensomes** [comment]
@eelzi-ONRR Done! The build with fixes is running and will be available in [preview](https://nrrd-preview.app.cloud.gov/sites/explore-data-comparison-card-updates/) shortly.

**Comment by greensomes** [comment]
Changes have been merged into the `AccessibilityStatement` branch and will go with the next release.

**Comment by eelzi-ONRR** [comment]
Looks good! I'll close this issue
