### ISSUE TITLE
Fix spacing on state comparison cards and cut off of federal card (disbursements)

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3277]
This update can be included with federal sales explore data update.

State cards have weird spacing for disbursements in Chrome (Edge seems okay)
Federal Card gets cut off in Chrome (Edge seems okay)

We able to replicate the Chrome issues on multiple computers and on both Mac/PC

<img width="632" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzJVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1628c1a1f0cb1b034e4425828adffbf0ce4cf643/image.png" alt="image.png" />

Federal card bottom in Chrome
<img width="184" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzZVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f70b9392d27e3b50130392f27c5304491331f78/image.png" alt="image.png" />

Federal card bottom in Edge
<img width="272" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEdVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e0af04f0925a4120a7a0a0a2199af1ba39487a4/image.png" alt="image.png" />

**Comment by AlexandracmONRR** [comment]
Jeff removed greater than symbol.

**Comment by greensomes** [comment]
@eelzi-ONRR , the build containing the fix is running and will be available in [preview](https://nrrd-preview.app.cloud.gov/sites/explore-data-comparison-card-updates).

**Comment by greensomes** [comment]
Changes have been merged into the `AccessibilityStatement` branch and will go with the next release.
