### ISSUE TITLE
Review VSFS applications 

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3281]
- [ ] Set up review spreadsheet 
- [ ] Review resumes
- [ ] Schedule interviews

**Comment by lpgoldstein** [comment]
@eelzi-ONRR I created review sheets for both of us in the [intern folder](https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/Admin/Interns/2024-2025?csf=1&web=1&e=ClCaYT)

We can start reviewing on Friday since tomorrow is the deadline. I'll add any additional applicants as they come in. I'll set up a meeting to discuss.

**Comment by eelzi-ONRR** [comment]
@lpgoldstein The post says the deadline is March 8. We're both out the 8th and 9th I propose we move to next sprint

**Comment by lpgoldstein** [comment]
@eelzi-ONRR They changed the deadline! That makes sense then.

**Comment by lpgoldstein** [comment]
emails sent for interviews
