### ISSUE TITLE
Find OOUX materials to share with team

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3283]
Looking at videos, podcasts, readings

**Comment by AlexandracmONRR** [comment]
Podcast of OOUX in Government (more for people with an intermediate knowledge of OOUX): https://open.spotify.com/episode/2UXoZch5I0iHGPtKhKcmba?si=ec58fd3243234c10&nd=1&dlsi=99b79b66f40f45e1

YouTube video of intro to OOUX (start at 15:36):
https://www.youtube.com/watch?v=KoyGruAB-iI

**Comment by AlexandracmONRR** [comment]
15 minute introduction to object mapping:
https://www.youtube.com/watch?v=JeATj5NO_ZU

**Comment by eelzi-ONRR** [comment]
https://www.ooux.com/what-is-ooux

Min 2:28-12:47 is a good intro
https://www.youtube.com/watch?v=hNb1wgXML1U
