### ISSUE TITLE
Finish and Practice DOI UX course

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3289]

**Comment by AlexandracmONRR** [comment]
@eelzi-ONRR @lpgoldstein - please [see pre-course email to participants](https://doimspp.sharepoint.com/:w:/s/NRRD/EZPtb2M07jNKrufyZ23sADMBE6gzjG9CXeiDatVa-nzotQ?e=BJNje9) and make your revisions.
