### ISSUE TITLE
DOI digital week presentation materials due April 8

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3297]
April 8
headshot
bio
draft presentation (accessible)
3 questions and answers for the presentation

**Comment by eelzi-ONRR** [comment]
@lpgoldstein Do you remember the context of sending them 3 questions and answers? Are these chat/poll questions or are they canned questions in case we don't get any from the audience?

**Comment by lpgoldstein** [comment]
@eelzi-ONRR It's for the chat/poll questions

**Comment by eelzi-ONRR** [comment]
Submitted everything for my and Alex's session via email on 4/2/24
