### ISSUE TITLE
A-123 narratives draft for FY24

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3347]
Review FY23 A-123 and Howard's guidance sent on March 20, 2024 to make updates for FY24 A-123. Due in July 

Reorg might affect ours.

**Comment by lpgoldstein** [comment]
wrote draft narratives. Will set up meeting to go over with group and also IROC before making flow charts.

**Comment by cthomasONRR** [comment]
@lpgoldstein are we good to close this issue?
