### ISSUE TITLE
Review FY23 renewable fact sheets

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3355]

**Comment by eelzi-ONRR** [comment]
@cthomasONRR @lpgoldstein let me know if I'm not reviewing these correctly. I didn't include the things from FY22 that Christine marked as being changed with the April PR

FY21 - pdf says 11 states, spreadsheet says 10 <img width="452" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTlhQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--459cf4daab312f61c75abfaf566c0b5000a7b415/image.png" alt="image.png" />
FY21 - none of the geothermal production numbers match the spreadsheet
FY20 - only some of the geothermal production numbers match the spreadsheet
FY18 - factsheet says 12 locations, sheet says 11, wind and geothermal percentages don't match the sheet, state vs treasury percentages don't match sheet, geothermal production numbers don't match sheet

**Comment by eelzi-ONRR** [comment]
@cthomasONRR @lpgoldstein  Rechecked using the 3 other spreadsheets. The same error exists on all fact sheets. For FY23/22 I used the PDFs in the Teams folder, for all others I used the PDFs on the live site

FY 2018 - Revenue says 12 states/regions but only 11 listed on data check sheet
FY 2019 - Revenue says 11 states/regions but only 10 listed on data check sheet
FY 2020 - Revenue says 11 states/regions but only 10 listed on data check sheet
FY 2021 - Revenue says 11 states/regions but only 9 listed on data check sheet
FY 2022 - Revenue says 11 states/regions but only 10 listed on data check sheet
FY 2023 - Revenue says 11 states/regions but only 10 listed on data check sheet

**Comment by cthomasONRR** [comment]
Example with 2018. There are 12 localities, which includes Native American as one locality:

![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/472db2be-024c-4080-b9c2-78def2a65471)

**Comment by eelzi-ONRR** [comment]
@cthomasONRR Can I close this issue then?
