### ISSUE TITLE
Complete workload impact assessment

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3371]
- [x] Finish filling in spreadsheet
- [x] Analyze and agree on workload for Q3 and 4 FY24
- [x] Create visuals
- [x] Write the narrative
- [x] Turn it in

**Comment by eelzi-ONRR** [comment]
Still waiting on response from Christa for the info we need for current state and summary

**Comment by lpgoldstein** [comment]
Sent to IDM manager
