### ISSUE TITLE
Add navigation for getting to state pages

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3376]
Right now these can only be accessed via search results. WCAG requires more than one way to get to all pages 

This should involve user research to figure out the best way to work these into the architecture and navigation

Examples: 
https://revenuedata.doi.gov/explore/states/OK/
https://revenuedata.doi.gov/explore/states/NE/

**Comment by AlexandracmONRR** [comment]
Completed hallway feedback sessions on 5/1/2024.
