### ISSUE TITLE
Add H1 to homepage

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3378]
https://revenuedata.doi.gov/ homepage needs an H1 for best practices regarding with SEO and indexing

**Comment by greensomes** [comment]
@lpgoldstein , ready for validation in [preview](https://nrrd-preview.app.cloud.gov/sites/add-h1-to-homepage/).

**Comment by lpgoldstein** [comment]
@greensomes looks great, thanks!
