### ISSUE TITLE
Continue product framing

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3380]
Initial update of goals/risks, and user type analysis is complete

Need to: reformat tasks to be bullet points instead of paragraphs, use user type analysis to help clarify what the goals/framing specific are for each major part of the site (query, explore, data downloads, how revenue works, fact sheets).

**Comment by eelzi-ONRR** [comment]
@AlexandracmONRR, @lpgoldstein , @cthomasONRR @cthomasONRR This is ready for review on the wiki if anyone has time this sprint. It's no rush: https://github.com/DOI-ONRR/nrrd/wiki/Product-framing

**Comment by cthomasONRR** [comment]
@eelzi-ONRR 

I think this is great! I really appreciate how organized and easy to read it is. I also really appreciate the updated risks reflect what we're dealing with now. I maybe found one typo- not sure if this asterisks is needed: 

![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/49b248af-3f1f-4df3-bbab-08a3f35ee4f1)

**Comment by lpgoldstein** [comment]
@eelzi-ONRR I had a few minor changes and questions - I turned on track changes and explained where necessary. Thank you so much for doing this! It looks great.
