### ISSUE TITLE
Create DOI econ workshop presentation

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3397]
User-centered data design is the title
presentation is may 22

**Comment by cthomasONRR** [comment]
@lpgoldstein @eelzi-ONRR Is there anything I can do to help right now? I'm happy to contribute to an outline or powerpoint. Thanks!

**Comment by eelzi-ONRR** [comment]
@cthomasONRR There's a very rough outline and brainstorming doc in the presentation folder. Feel free to add anything. We should meet but that will have to wait until Lindsay is back - the topic was her idea so I imagine she has some vision for it

**Comment by eelzi-ONRR** [comment]
@cthomasONRR @lpgoldstein Okay I'm done with it for now. I'll work on it some more tomorrow afternoon if no one else is but I can also finish up the slides for my section next week. https://doimspp.sharepoint.com/:p:/r/sites/NRRD/Shared%20Documents/General/Outreach/Outreach%20Proposals%20%26%20Presentations/FY24/DOI%20Econ%20Workshop/User-centered%20Data%20Design.pptx?d=w98c79d91e2fa4aeb9e84a6e5c5bf144e&csf=1&web=1&e=mkojIv

**Comment by cthomasONRR** [comment]
@lpgoldstein @eelzi-ONRR I'm done as well

**Comment by eelzi-ONRR** [comment]
I'm done. And I ran the accessibility checker and did all the fixes

@lpgoldstein can you add alt text for the image on slides 11 & 12? I think those are ones you added

**Comment by lpgoldstein** [comment]
@eelzi-ONRR thank you and done.

**Comment by eelzi-ONRR** [comment]
@lpgoldstein @cthomasONRR I fixed my blurry images and hopefully fixed the bullet points. 

Ends up if you copy an entire slide then the images lose quality, which is what I had done. But if you copy and paste just images then they're okay

**Comment by eelzi-ONRR** [comment]
@lpgoldstein @cthomasONRR I fixed my blurry images and hopefully fixed the bullet points. 

Ends up if you copy an entire slide then the images lose quality, which is what I had done. But if you copy and paste just images then they're okay

**Comment by lpgoldstein** [comment]
@eelzi-ONRR I fixed my image as well and fixed the bullets. I'm ready to upload the presentation whenever you all give the word.

**Comment by cthomasONRR** [comment]
@lpgoldstein @eelzi-ONRR I'm good to upload!

**Comment by eelzi-ONRR** [comment]
@lpgoldstein Good to upload unless you wanted to review participant pool sign-up form and add a slide with the link.

**Comment by lpgoldstein** [comment]
@eelzi-ONRR I'll do that and send in tomorrow.
