### ISSUE TITLE
Provide 3 questions/answers for DOI Digital Week presentation

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/nrrd#3408]
Sid requested that we make 3 questions and answers (multiple choice or true/false) related to our presentations for DOI Digital week. These would just be a knowledge check that people would answer in DOI talent.

At the end of the course, we can read these questions out and their answers so that people can remember them for the knowledge check.

Submit by 4/29

**Comment by AlexandracmONRR** [comment]
@eelzi-ONRR - I've drafted 3 questions/answers for the testing presentation. Please take a look in this [text document](https://doimspp.sharepoint.com/:t:/r/sites/NRRD/Shared%20Documents/General/Outreach/Outreach%20Proposals%20%26%20Presentations/FY24/DOI%20Digital%20Week/Testing%20-%20Question%20and%20Answers%20-%20Knowledge%20Check.txt?csf=1&web=1&e=S9J2Ve) and make any changes.

**Comment by eelzi-ONRR** [comment]
@AlexandracmONRR In the doc I suggested two different questions for 2 & 3 so they are more obvious in their answer and not about how our team does things.

**Comment by AlexandracmONRR** [comment]
Erin and Alex submitted questions via email on 4/26.

**Comment by lpgoldstein** [comment]
Sent 4/29
