### ISSUE TITLE
Create list of custom events to track with GTM

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3420]

**Comment by cthomasONRR** [comment]
Ideas discussed:
- Differentiate links between top menu nav and regular links
- Footer activity
- Get more details from Explore Data - possibly clean/refine URLs? It's very hard to tell the users activity right now.
- Get more details from Query Data - can see what data type applied but nothing else.

**Comment by eelzi-ONRR** [comment]
- Track as many things as possible in explore and query in a way that makes them events and not just jumbled URLs - including use of filters, how users select a location (map, add a location tab, comparison cards), use of add a column, etc.

We'll bring these ideas up to the rest of the team at sync-up next week. Some of these might be beyond the scope of GTM but maybe we can figure out other solutions

**Comment by eelzi-ONRR** [comment]
Did not discuss at sync-up this sprint, but @cthomasONRR I think we can close this issue and discuss at sync-up next week
