### ISSUE TITLE
Create user research participant pool sign-up form

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3433]

**Comment by eelzi-ONRR** [comment]
@lpgoldstein @AlexandracmONRR Let me know what you think: [User Participant Pool Sign-Up Form](https://forms.office.com/Pages/DesignPageV2.aspx?origin=NeoPortalPage&lang=en-US&subpage=design&id=urWTBhhLe02TQfMvQApUlE9F1z2Bp09BtvG20Q-ttkpUNzhNTTJBWjFEOENUQVVVVkQyWDNDM1U4RCQlQCN0PWcu)

I think we're okay to share it during presentations, but I think we might need more levels of approval to post a link on our wiki or website (since it's a form collecting personal info, even if we're avoiding PII)

**Comment by lpgoldstein** [comment]
@eelzi-ONRR looks good.

**Comment by lpgoldstein** [comment]
@eelzi-ONRR is there anyway we can get a shortened url?

**Comment by AlexandracmONRR** [comment]
@eelzi-ONRR - the only thing I think that could be helpful, would be to ask if they would need any time of accessible accommodation. Then, we may be able to ask for participation by users that utilize a screen reader or another type of accommodation.
