### ISSUE TITLE
Review A-123 narratives

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3440]

**Comment by lpgoldstein** [comment]
@cthomasONRR @eelzi-ONRR @AlexandracmONRR ready to review! https://doimspp.sharepoint.com/:f:/r/sites/NRRD/Shared%20Documents/General/Admin/A-123/FY24?csf=1&web=1&e=gjkfOB

**Comment by cthomasONRR** [comment]
@lpgoldstein Attached are my content audit flow charts. Still waiting on Visio, so I did them in Excel. I had no additional changes to the narratives.

[A123-ContentAuditFlow.pptx](https://github.com/DOI-ONRR/nrrd/files/15419626/A123-ContentAuditFlow.pptx)

**Comment by eelzi-ONRR** [comment]
@lpgoldstein Done reviewing. I made some more comments - mostly for small edits, but I did have a question about the document testing steps (it's in a comment). In the addendums I made direct edits to fix some spacing and capitalization, and changed a few places where it said "his or hers" to "theirs"

**Comment by AlexandracmONRR** [comment]
@lpgoldstein - i made a couple of comments, but overall i think it looks great. I don't have any big changes.
