### ISSUE TITLE
Review: DX Indicators: May 2024 Update (V2 Test Data Available for Review

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3465]

**Comment by AlexandracmONRR** [comment]
Asked them (via survey) to remove the following sites from the DX spreadsheet:  beta.onrr.gov; onrr-connection.onrr.gov; preview-onrr-frontend.app.cloud.gov; prod-onrr-frontend.app.cloud.gov 

For next meeting on Thursday (6/13) we will submit survey responses for the DX indicators for specific websites:

- Lindsay: Blog and NRRD
- Alex: ONRR.gov

We can also submit any additional feedback about this data collection process afterwards.

**Comment by AlexandracmONRR** [comment]
Switched the next meeting to next sprint, so I'll push this issue to next sprint too.

**Comment by AlexandracmONRR** [comment]
ONRR.gov (current scoring):

- Average across policy requirements: 92%
- _Average across best practice categories: 14%_
- _Average across all categories: 59%_

.

- Analytics category: 100%
- Accessibility: 100%
- **Mobile Friendliness: 67%**
- Security: 100%
- **Feedback: 0%**
- **Design Consistency: 0%**
- **Search Optimization: 43%**

**Comment by AlexandracmONRR** [comment]
- Lindsay to submit feedback for nrrd
- Alex to submit feedback for onrr.gov
- Alex to create project in github
- Lindsay to add action items to project in github for nrrd and blog
