### ISSUE TITLE
Zion

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3473]

**Comment by lpgoldstein** [comment]
**NRRD:**
Follow up with DG on data.gov meeting
Set up custom events in GA4
**Blog:**
Implement blog user research
M-23-22 blog
work priorities blog
federal sales blog
**Outreach/Misc**
Q3 metrics tracking and snapshot
Annual 508 assessment
**ONRR**
Fix ambiguous links
implement feedback on pdf link targets
Continue GA4 &360 comparisons
Global accessibility fixes
Osage content and prototype
Plan for Indian handbook
Plan for USWDS
Deploy CMS changes
**ONRResource**
Determine resources
