### ISSUE TITLE
Review State Navigation Page

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/nrrd#3474]
[Homepage](https://nrrd-preview.app.cloud.gov/sites/individual-state-navigation/)
[State Nav Page](https://nrrd-preview.app.cloud.gov/sites/individual-state-navigation/data-by-state-offshore-region/)

Reviews

- [x] Accessibility Manual check (Lindsay)
- [x] Accessibility Automated check (Alex, Wave, Lighthouse)
- [x] Content Review (Christine)
- [x] Link Review (Christine)

**Comment by AlexandracmONRR** [comment]
@lpgoldstein and @cthomasONRR - I've added you to this review, please let me know if you prefer a different part to review!

**Comment by cthomasONRR** [comment]
@AlexandracmONRR 

- Could you make the homepage link sentence case? These highlighted uppercase letters can be lower case.

![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/97e4005e-1a19-4edb-a70a-4e3e2361ba2e)

- Can you make content on the state nav page be in sentence case? These highlighted uppercase letters can be lower case. Since explore data and query data links are within a sentence and they're not really proper nouns, they can also be lower case.
- Also, should this say "explore data AND query data"?
![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/29f2b031-7327-4844-98c3-77f744bc1d3f)
![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/84289ca9-718b-4162-9398-1c9024d7b19f)

**Comment by cthomasONRR** [comment]
@AlexandracmONRR 

This isn't really an issue, more of a question. Is there a reason why the states are 4 to a row and the offshore regions are only 3 to a row? Is it that the text length of each offshore region name prevents them from being 4 in one row? If possible, it would be nice to have all 4 offshore regions in one row, but not super necessary/important.

![image](https://github.com/DOI-ONRR/nrrd/assets/72526208/7018b44d-3f6b-4bfa-aa23-3556c1139622)

**Comment by AlexandracmONRR** [comment]
I think that has to do with screen size and the margin/padding around each button. For me it is showing up as 4 buttons across the screen:

<img width="1104" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0J6QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--afc569c7cf08e414aa5c7f39203ac0b60ab7148b/image.png" alt="image.png" />

**Comment by cthomasONRR** [comment]
@AlexandracmONRR All links look good! Let me know when you have content corrections made and I'll review those again. Great work, thanks!

**Comment by lpgoldstein** [comment]
homepage - SVG should be hidden
![image](https://github.com/DOI-ONRR/nrrd/assets/39419003/c342ad6c-8211-4241-9fba-e7a7453d731a)

here is an example of how the other links next to "Data by state and offshore region appear"
![image](https://github.com/DOI-ONRR/nrrd/assets/39419003/22b1dd24-5a8f-4800-9c79-5a41e583729a)

**Comment by AlexandracmONRR** [comment]
@CthomasONRR - i made the [corrections ](https://nrrd-preview.app.cloud.gov/sites/individual-state-navigation/data-by-state-offshore-region/)the casing that you found 
@lpgoldstein - I will need to ask jeff to hide the svg

**Comment by AlexandracmONRR** [comment]
Passed the WAVE check. 

The only errors or alerts found were not related to the state nav page. They were related to the search box (missing form label), contrast errors in footer (footer doesn't present correctly in preview site), and 4 alerts related to images in the footer (footer doesn't present correctly in preview site).

**Comment by AlexandracmONRR** [comment]
Passed Lighthouse check.

100 in Accessibility.

68 in Performance. Warning for total blocking time and speed index. Diagnostics alerted us to minimize main-thread work, reduce javascript execution time, and reduce unused javascript.

**Comment by cthomasONRR** [comment]
@AlexandracmONRR The content updates look good! Thanks!

**Comment by AlexandracmONRR** [comment]
@cthomasONRR and @lpgoldstein - thank you for your review and feedback!

I've created a separate issue for jeff to hide the svg for when he gets back and then this will be ready to merge.

This issue will be closed!
