### ISSUE TITLE
Q3 Metrics - Customer Experience (CX)

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#3479]
- [x]  Track planned usability studies and goal of study @lpgoldstein
- [x]  # of users recruited @lpgoldstein
- [x]  # of users accepted recruitment & participated in study @lpgoldstein
- [x]  Inclusive research (how we plan research and document in research plan) @eelzi-ONRR
- [x]  # of findings/recommendations resulting from user research @AlexandracmONRR
- [x]  Identify user-centered design efforts @AlexandracmONRR

**Comment by lpgoldstein** [comment]
@alexandracmONRR I didn't work on the last user study - could you please help me with the user study metrics?

**Comment by AlexandracmONRR** [comment]
@lpgoldstein - yes I'll work on these metrics tomorrow
