### ISSUE TITLE
Update DAP Code after June 24

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#3485]
DAP is making major code updates and it will be released on June 24. 
The code needs to be updated within NRRD, ONRR, Blog, and ONRResource for our self-supported ODDD property.

Code will be on their GitHub https://github.com/digital-analytics-program/gov-wide-code.

Let me know if you'd like separate issues for each website.

**Comment by greensomes** [comment]
@cthomasONRR , because the script tag we use for all three sites links to the file on DAP's central hosting server, we do not need to update anything on our end. I'm going to go ahead and close this issue.
