### ISSUE TITLE
State Navigation Page - hide the SVG for the map icon

### ISSUE THREAD

**Issue by AlexandracmONRR** [DOI-ONRR/nrrd#3494]
In code, "ExploreRevenue.js", "ExploreProduction.js", "ExploreDisbursements.js", please hide the SVG for the map icon (an accessibility fix).

Image of code:

![image](https://github.com/DOI-ONRR/nrrd/assets/122935097/7b1951bb-a510-40c7-805e-039cf3e40ddb)

Image of accessibility flag:
![image](https://github.com/DOI-ONRR/nrrd/assets/122935097/2fe8b40f-0f22-452e-a719-f97c4f7dcc2e)

Preview:
[Homepage](https://nrrd-preview.app.cloud.gov/sites/individual-state-navigation/)
[State Nav Page](https://nrrd-preview.app.cloud.gov/sites/individual-state-navigation/data-by-state-offshore-region/)

**Comment by greensomes** [comment]
Hey @AlexandracmONRR , this is ready for review on your preview branch. The icon file had a title tag in it. I just removed it.
