### ISSUE TITLE
Plan touchpoints form

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3502]

**Comment by lpgoldstein** [comment]
https://www.usaspending.gov/
<img width="1047" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNld4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d49de116893530ce67391bb69e0d8ca33bdb3949/image.png" alt="image.png" />
<img width="1232" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmF4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0749dbe01866201af53bae9c65ae778a1f3cebc8/image.png" alt="image.png" />

**Comment by lpgoldstein** [comment]
<img width="444" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm14QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3ca0b17e2aa7b109735f73eb294b977de9029ea/image.png" alt="image.png" />
usa.gov popup from bottom side of page

**Comment by AlexandracmONRR** [comment]
https://fws.gov/


<img width="446" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkMvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--98a747d92d667ae6483ede42c2627c9e2a418d92/image.png" alt="image.png" />


<img width="391" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNksvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--48bc8ff7339d1867e843d976544db2fbd54c8ada/image.png" alt="image.png" />


extra

<img width="352" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlMvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d5d353316db5387691f014f25ee204d1c9cf1553/image.png" alt="image.png" />

<img width="382" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlcvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a64141c162a6f7342271d6d6517fd35ed4bc41ac/image.png" alt="image.png" />

**Comment by AlexandracmONRR** [comment]
Notes from meeting: 

**Question for team:**
Stays in bottom right corner so always visible? Or, goes in footer or close to?


**What we could put in feedback survey:**

How satisfied are you with this site?
	- Try the stars (visual)
	   OR
	- Try thumbs up or thumbs down (visual)


Did you complete your task?
What task were you trying to do today?
OR
Did you find what you're looking for?
Please explain.

Do you have any suggestions to improve the site?

Do you want to participate in user research? Input your email below.

**Comment by AlexandracmONRR** [comment]
@lpgoldstein - here are two options for us to review with team:

Option 1: https://touchpoints.app.cloud.gov/touchpoints/14e2a803/submit

Option 2: https://touchpoints.app.cloud.gov/touchpoints/0d220a83/submit

**Comment by lpgoldstein** [comment]
@alexandramonrr Thanks for working on this - I like option 2!

**Comment by AlexandracmONRR** [comment]
Next Steps:

- Talk with NPS about how they are tracking pages
- Talk with FWS about how they decided to choose the questions they did
- Talk with Haley about DOI guidance on feedback mechanism
- Talk with GSA developer, Ryan, about page tracking


Note:
If put in footer, may require developer help to track query string related to the submission of the feedback.

**Comment by AlexandracmONRR** [comment]
Response from Ryan at GSA Touchpoints:


Hi Alex,

* Thumbs up/down is only available in the template. But the question should be editable. If not, let's chat!
* Tracking responses across each page:  embedded forms should track the host and path from where the feedback was submitted (across pages)
* The button and modal are scanned for 508 accessibility and compliance and use USWDS accessible components.  We do have a couple improvements and enhancements coming to improve accessibility, specifically around the modal.  You can tab to the tab button and trigger the modal via keyboard, and we've had our Section 508 team review the feedback flow as well.
* Touchpoints doesn't offer much in the way of customization, but happy to chat.  Typically, agencies can use CSS style overrides on their time.

Thanks for your questions, and happy to chat more or hop on a call.

- Ryan
