### ISSUE TITLE
Update link

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3523]
@cthomasONRR - not urgent. Found while doing accessibility checking.
AML page
https://revenuedata.doi.gov/how-revenue-works/aml-reclamation-program

Link needs to be updated

<img width="990" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVh1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a6da8bae0b7dcef654a95336287e7f01e232f4c/image.png" alt="image.png" />

current link:
https://www.govinfo.gov/app/details/USCODE-2011-title30/USCODE-2011-title30-chap25-subchapIV-sec1232

new link:

https://www.govinfo.gov/app/details/USCODE-2023-title30/USCODE-2023-title30-chap25-subchapIV-sec1232

**Comment by cthomasONRR** [comment]
@lpgoldstein Completed, in PR #3525
