### ISSUE TITLE
Get annual datasets' metadata in JSON file

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#3529]

**Comment by eelzi-ONRR** [comment]
Here's the JSON template: https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/NRRD/Data/data.gov%20project/json%20structure%20for%20EDI.docx?d=wddcbd82cc6034e9fbeb2bb4199ff643c&csf=1&web=1&e=WwMNd0

**Comment by cthomasONRR** [comment]
I added all annual datasets from the Excel to the Word doc in preparation for the JSON file.

**Comment by cthomasONRR** [comment]
@eelzi-ONRR and I had a synch up- all the JSON updates were in the header and do no affect the individual datasets that I put in the Word doc. DOI is currently blocked from merging their PR which would get our JSON file set in digital.gov. Once this block is fixed, we will be able to update the JSON. Erin is working with Jennifer, but if this is not resolved by the time she leaves, she will transfer communication to us.

**Comment by cthomasONRR** [comment]
Moving to next sprint- need to follow up with Jennifer about the status of the original JSON with just disbursements before we add more metadata to it.

**Comment by cthomasONRR** [comment]
Before we add new metadata for the other annual datasets, we'll need to add the identifier for this set to the json file (there's a comment about it in the doc) and that won't get added until it's live. Right now it's still in staging.

This identifier will make sure that every time new sets are added that we are matching up the sets we've already loaded, otherwise the already loaded sets will load as new, unique sets every time there's a harvest

We'll have to do this iteration with the identifier for the other datasets as well. 

Jennifer will let us know when the disbursements json is live then we can work on these next steps.

**Comment by cthomasONRR** [comment]
Annual disbursements is now on data.gov!
https://catalog.data.gov/dataset/fiscal-year-disbursements-of-u-s-natural-resources-revenue

We can close this issue and create new ones for the next datasets.
