### ISSUE TITLE
Add language to accessibility statement that explicitly says we follow DOI 508 and accessible ICT policies

### ISSUE THREAD

**Issue by eelzi-ONRR** [DOI-ONRR/nrrd#3538]
Required by M-24-08 and govt-wide assessment that we have these publicly posted. ONRR mostly follows DOI policies in this area instead of having our own: https://www.doi.gov/ocio/information_management/section-508-policies

Can add to the DOI Section 508 Program  section. The [DOI accessibility statement](https://www.doi.gov/accessibility) has updates in this section that ours don't reflect - we can copy that and add that we use the DOI policies

**Comment by cthomasONRR** [comment]
Updated: https://dev-onrr-frontend.app.cloud.gov/accessibility

**Comment by cthomasONRR** [comment]
@lpgoldstein This is ready for your review:
https://nrrd-preview.app.cloud.gov/sites/August24Uploads/accessibility/

You can compare to the live site: https://revenuedata.doi.gov/accessibility
