### ISSUE TITLE
ODDD FY25 high level goals

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3564]
Lindsay draft, send to everyone for review and meet to discuss week 2 of sprint.

**Comment by lpgoldstein** [comment]
[FY25 goals](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/Admin/Goals%20%26%20Accomplishments/FY%2025/[FY25goalsnew.xlsx](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/Admin/Goals%20%26%20Accomplishments/FY%2025/FY25goalsnew.xlsx?d=wffe61b8e8504409783d3bdfe491961f0&csf=1&web=1&e=wUHXG3)?d=wffe61b8e8504409783d3bdfe491961f0&csf=1&web=1&e=wUHXG3)

@greensomes @cthomasONRR @AlexandracmONRR After thinking about it some more, we are taking our goals and FY planning back to basics. I've started a new fresh spreadsheet for our goals and I've only added a few. Next week we can talk about what we want to accomplish for the year and how we can do that. Then we can add in our routine tasks later and break down goals into tasks. Then decide how we want to categorize and measure our work.

**Comment by cthomasONRR** [comment]
@lpgoldstein I'm getting a 404 for that link... could you point us to its location?

**Comment by cthomasONRR** [comment]
Oh wait, just found it!
![image](https://github.com/user-attachments/assets/40f3cc5e-6f34-433f-b357-13692e2aa52d)

**Comment by lpgoldstein** [comment]
Let's try again: [FY25goalsnew](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/Admin/Goals%20%26%20Accomplishments/FY%2025/[FY25goalsnew.xlsx](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/Admin/Goals%20%26%20Accomplishments/FY%2025/FY25goalsnew.xlsx?d=wffe61b8e8504409783d3bdfe491961f0&csf=1&web=1&e=uTi0gi)?d=wffe61b8e8504409783d3bdfe491961f0&csf=1&web=1&e=uTi0gi)

**Comment by lpgoldstein** [comment]
![image](https://github.com/user-attachments/assets/fd2c8e43-98c5-492f-98cc-983eba7e894f)

**Comment by lpgoldstein** [comment]
Closing - our doc is set up and we have a plan.
