### ISSUE TITLE
Axe-Con accessibility conference proposal Due October 11

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3565]
https://www.deque.com/axe-con/call-for-speakers/

**Comment by cthomasONRR** [comment]
@lpgoldstein My proposal is ready to review (no rush though)
Document [here](https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Outreach/Outreach%20Proposals%20%26%20Presentations/FY25/Axe-Con%2025/AxeConProposal_CLT.docx?d=w7ec810f21ea54122be6ab9c9f1437be0&csf=1&web=1&e=F2rNq0)

**Comment by lpgoldstein** [comment]
@cthomasONRR Just a few comments but looks great!

**Comment by AlexandracmONRR** [comment]
I will put together a proposal for accessibility and testing. Reach out to Erin too.

**Comment by cthomasONRR** [comment]
I submitted my proposal. Submission page says "We’ll get back to you with a decision by Monday, November 18th. Keep checking your email."
