### ISSUE TITLE
CY Production Json file - data.gov metadata

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3595]
prep rest of metadata for release in FY 25

**Comment by cthomasONRR** [comment]
@lpgoldstein 
The next dataset in the Word doc is CY Production. I made sure I added the "@id" and "identifier" in the correction locations. They are highlighted in yellow. I have a comment boxes on each bracket that marks the start of the new dataset. Once we create a dummy entry to get the "@id" and "identifier" info, we should be able to add that in the Word doc, then copy+paste the CY Production metadata into the json.

I also added the "@id" and "identifier" to all the other datasets in the Word doc as well.

**Comment by lpgoldstein** [comment]
https://catalog.data.gov/dataset/calendar-year-production-of-u-s-natural-resources-revenue
