### ISSUE TITLE
Add FY production metadata to data.gov

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3606]

**Comment by cthomasONRR** [comment]
Shell record: https://datainventory.doi.gov/object-editor/view/f83e3c59c6be4c94913583d2d5bb5c32

**Comment by cthomasONRR** [comment]
FY Production now on data.gov! https://catalog.data.gov/dataset/fiscal-year-disbursements-of-u-s-natural-resources-revenue
