### ISSUE TITLE
onboard Jodie!

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3608]
In order to get `Jodie` productively contributing to the Open Data, Design, & Development (ODDD) team, `Lindsay/Christine` should help `Jodie` complete a prescribed set of tasks that will bring them up to speed.

# Directions

**`Lindsay`:** If you can’t complete any of the items on your checklist personally, you are responsible for ensuring that someone with the correct access completes that item.

**`Jodie`:** Take judicious notes on what about this onboarding process or the websites are confusing or frustrating. If you notice a problem (especially with things like documentation), you are more than welcome to fix it! At the very least, please share this information with your buddy so we can make the team/platform better. You can also file issues and pull requests as soon as you feel comfortable doing so.

## Get access to GitHub so that you can complete this checklist
  - [x] Follow [our instructions](https://github.com/DOI-ONRR/nrrd/wiki/How-to-join-DOI-ONRR-GitHub) to get a license so you can access our GitHub. 

  - [x] Follow [18F’s setup instructions](https://handbook.18f.gov/github/#setup) to create a GitHub account, or link an existing account to your government work. (Skip steps #4 and #5)

  - [x] Let the Product Manager (or anyone who is an admin) know when your account has been created, and what your username is. Ask them to add you as a member or contributor to the project repository so that you can make contributions, and to add you to the ONRR GitHub organization.

  - [x] Subscribe to the [NRRD repository](https://github.com/DOI-ONRR/nrrd) and [ONRR.gov repository](https://github.com/DOI-ONRR/onrr.gov-site) (through the [GitHub watch feature](https://help.github.com/articles/watching-and-unwatching-repositories/)) to get notifications of project activity. We also have separate repos for [user research](https://github.com/DOI-ONRR/research) and the [blog](https://github.com/DOI-ONRR/blog-nrrd), that you should subscribe to.

## Get access to other project tools and services that the team uses to communicate

- [x] `Lindsay`: **Invite `Jodie` to the Slack nrrd-workspace using government email**</strike>
  - [x] `Jodie`: Accept the invitation via email, and set up your account with 2-factor authentication. Set up your profile with your name, location, and any other information you wish to provide.</strike>

- [x] `Lindsay`: **Invite `Jodie` to [ZenHub](https://app.zenhub.com/workspaces/nrrd-portal-5464fa79c3cc8d7f4c384eaf/board?repos=21627244&showPRs=false&showPipelineDescriptions=false) after they have accepted the GitHub invite**
  - [x] `Jodie`: Once you have access, have someone show you how we use the project planning board. We use ZenHub as a project management tool to track tasks. ZenHub connects to GitHub and displays the issues from the the project’s repository in columns that show its progress—Unprioritized, Product Backlog, Sprint Backlog, In Progress, Awaiting Review, or Done.

## Learn about the project background and how the team works

- [x] Read the [NRRD Product Framing](https://github.com/DOI-onrr/nrrd/wiki/product-framing) document

- [x] Read the [ONRR.gov Product Framing](https://github.com/DOI-ONRR/onrr.gov-site/wiki/Product-framing) document

- [x] Read about the current status of the project on the [homepage of the wiki](https://github.com/DOI-ONRR/nrrd/wiki/home)

- [x] `Christine`: Add `Jodie` to the  [humans.txt](https://github.com/DOI-ONRR/nrrd/blob/dev/humans.txt) project team list.

- [x] Read the [Basics for making distributed work work](https://github.com/DOI-ONRR/nrrd/wiki/Basics-for-making-distributed-work-work)

- [x] Meet with the Product Manager for an introduction to project routines, expectations, and rituals
  - [x] Discuss [project meetings](https://github.com/DOI-ONRR/nrrd/wiki/Joining-the-Natural-Resources-Revenue-Data-project-team#meetings): what they are, how they are run, and how the new person is expected to participate at each
  - [x] Review the most recent [ODDD team roadmap](https://app.zenhub.com/workspaces/data-display-5464fa79c3cc8d7f4c384eaf/roadmap)

## Familiarize yourself with the new onrr.gov CMS
- [x] Read through the [CMS user guide](https://github.com/DOI-ONRR/onrr.gov-site/wiki/CMS-user-guide)
- [x] Read the new method for [releasing changes to production](https://github.com/DOI-ONRR/onrr.gov-site/wiki/Releasing-changes-to-production-for-the-new-CMS)

## Data Checklist

- [x] Learn about the different data sets in our NRRD website by visiting the [download page](https://revenuedata.doi.gov/downloads/)
- [x] Learn about the [data types](https://github.com/DOI-ONRR/nrrd/wiki/Data-Overview) within NRRD as well as which data sets tie into which features
- [x] Learn about the different data visuals on our NRRD website by visiting the [Explore Data Page](https://revenuedata.doi.gov/explore)
- [x] Learn about the [Query data page](https://revenuedata.doi.gov/query-data)
- [x] Review the [how to upload data checklist](https://github.com/DOI-ONRR/nrrd/wiki/Releasing-changes-to-production#how-to-upload-monthly-datasets)
- [x] Review the [checklists for reviewing newly uploaded data](https://github.com/DOI-ONRR/nrrd/wiki/Releasing-changes-to-production#appendix-things-to-check-while-reviewing-changes)

## Design checklist

- [x] **Learn about [what you need to know about doing design and research in the federal government](https://github.com/DOI-onrr/nrrd/wiki/What-you-need-to-know-about-doing-design-and-research-in-the-federal-government)**  

- [x] **Learn about our user research practice**  
Our research plans and findings are documented in the open as part of our GitHub repository. You can find the research at any time by changing the branch in the repo to the “research” branch.
  - [x] Read about NRRD's [Research norms and processes](https://github.com/DOI-ONRR/nrrd/wiki/Research-norms-and-processes)
  - [x] Learn about [NRRD's user types](https://github.com/DOI-ONRR/research/blob/main/nrrd-research/00_UserTypes/00_UserTypes.md)
  - [x] Learn about [onrr.gov's user types](https://github.com/DOI-ONRR/onrr.gov-site/wiki/Product-framing#key-scenarios)

- [x] **Read through the research work:**
  - [x] [NRRD research and findings](https://github.com/DOI-ONRR/research/tree/main/nrrd-research)
  - [x] [onrr.gov research and findings](https://github.com/DOI-ONRR/research/tree/main/onnr-dot-gov-research)

- [x] **Review the style guides to get a sense of how to write and talk about content**
  - [x] [NRRD content guide](https://github.com/DOI-ONRR/nrrd/wiki/Content-style-guide) 
  - [x] [onrr.gov content guide](https://github.com/DOI-ONRR/onrr.gov-site/wiki/Content-guide) 

- [x] **Read the [design principles for the NRRD site](https://github.com/DOI-ONRR/nrrd/wiki/Design-Standards#design-principles-for-the-nrrd-site)**  

- [x] **Browse the [onrr.gov design folder](https://doimspp.sharepoint.com/sites/NRRD/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=KVSp1z&cid=4eb1a5b0%2Dcb90%2D487d%2Da5ff%2D485bb99cbeb2&FolderCTID=0x01200044BDC74607AB0342BAC14F3B92EB1E28&id=%2Fsites%2FNRRD%2FShared%20Documents%2FGeneral%2FONRR%2Egov%2FDesign&viewid=144f35a1%2D90d4%2D4ed2%2D9f31%2D521ec6887304) to get a feel for the work involved in the website redesign**  

- [x] **Link to the [Axure cloud folder](https://app.axure.cloud/app/fs/manage/60e31095-504c-4ed4-9cf8-d4613c9075d7/5d339fef-2e4b-4d7e-a470-25041f66cadd) where redesign prototypes and widget libraries are stored**

- [x] **Read about [how to design with NRRD data](https://github.com/DOI-ONRR/nrrd/wiki/Little-rules-for-designing-with-data)**  

- [x] **Read about [onrr.gov's accessibility policy](https://github.com/DOI-ONRR/onrr.gov-site/wiki/Accessibility-guidance) and [accessibility resources](https://github.com/DOI-ONRR/nrrd/wiki/Accessibility)**  

## Development checklist
**Get access to:**
- [x] Github repos
- [x] CircleCi?
- [x] cloud.gov?

## General
- [x] **If you are new to GitHub, learn about how it works, and how to make it work for you**  
GitHub is traditionally a development tool, not a design tool. It may take some time and experimenting to figure out how to work within its framework as a designer. Some places to start:
  * **Download GitHub desktop and [add our repositories](https://docs.github.com/en/desktop/adding-and-cloning-repositories/cloning-a-repository-from-github-to-github-desktop)**
  * **Understand the [GitHub workflow](https://guides.github.com/introduction/flow/) that code-based changes to the website go through.**  
    Even if you won’t be contributing code changes, it helps to share the same vocabulary as your team.  
  * **Learn about [GitHub issues](https://guides.github.com/features/issues/)**  
    Issues are how the team tracks tasks to work on or bugs to fix.
  * **Understand the basics of writing in [Markdown](https://guides.github.com/features/mastering-markdown/)**  
    Markdown is a lightweight way of creating formatting for text. Using certain characters tells the text to render as headlines, bullets, etc. It will be helpful to know the basics of Markdown because GitHub uses it as the default syntax for writing issues (although they have recently implemented a WYSIWYG toolbar that helps!)
     * Try this [Markdown tutorial](https://www.markdowntutorial.com/)

- [x] **Get access to any software needed (Axure, Adobe Pro, GitHub Desktop, VSX, etc.)**  
    Check that the IT Non-Core Software request form lists the most recent version of a software. If it does not, double check with an ODDD team member which software version we use before placing the request.  

- [x] Get access to the ODDD Teams Group and ODDD Outlook team calendar.
- [x] **Join the [UX Community of Practice](https://digital.gov/communities/user-experience/#) email listserv and any other [digital.gov communities](https://digital.gov/communities/) you are interested in joining** (optional)  
A mailing list of fellow UX designers across government. Useful for sharing resources and learning about challenges shared by other practitioners.

**Comment by jpetersononrr** [comment]
Suggest bookmarks for workflow of web pages go into CMS user guide.

**Comment by jpetersononrr** [comment]
I've signed up for Axure...not sure what to do to connect to the folder.

Also I think the owner has to set me up with the ODDD calendar and inbox....
