### ISSUE TITLE
Epic: Channel Islands

### ISSUE THREAD

**Issue by lpgoldstein** [DOI-ONRR/nrrd#3622]
**HIGH LEVEL GOALS:**

**Blog**: 
- Implement USWDS components [completed]
- Update Gadsby to v5 [completed]
- Publish federal sales blog [completed]

**NRRD**: 
- Implement USWDS components
- Update Gatsby [started]
- Publish annual datasets to data.gov [completed]
- Publish monthly & FY data [completed]

**ONRR**: 
- Implement USWDS components [completed]
- Clean up cloud.gov and maximize resources [completed]
- Resolve issues between front end and CMS [started]
- Remove extra graphql call [completed]
- Liaison with GSA for Touchpoints pilot [completed]
- Begin Touchpoints pilot [completed]
- Update Directus [started]
- Monthly updates [completed]

**ONRResource**:
- Clean up ONRResource [started]
- Content governance audit [completed]
- Decide on CMS [started]

**Admin**: 
- Post digital services specialist position [completed]

**Comment by cthomasONRR** [comment]
HIGH LEVEL GOALS:

Blog: Implement USWDS components, Update Gadsby to v5, Publish federal sales blog

NRRD: Implement USWDS components, Publish annual datasets to data.gov, Publish monthly data

ONRR: Implement USWDS components, Clean up cloud.gov and maximize resources, Liaison with GSA for Touchpoints pilot, Update Directus, Monthly updates

ONRResource: Clean up ONRResource, Content governance audit, Decide on CMS
