### ISSUE TITLE
Code for America proposals

### ISSUE THREAD

**Issue by cthomasONRR** [DOI-ONRR/nrrd#3642]
Call for breakout session and lightning talk proposals will be open November 14–25, 2024.
https://summit.codeforamerica.org/call-for-proposals/

**Comment by cthomasONRR** [comment]
@lpgoldstein Want to review before I submit?
https://doimspp.sharepoint.com/:w:/r/sites/NRRD/Shared%20Documents/General/Outreach/Outreach%20Proposals%20%26%20Presentations/FY25/CFA%2025/Thomas_CFA25.docx

**Comment by lpgoldstein** [comment]
@cthomasONRR reviewed

**Comment by cthomasONRR** [comment]
Submitted!
